### ISSUE TITLE
What is this file?

### ISSUE THREAD

**Issue by frenchLineCigar** [mplushnikov/lombok-intellij-plugin#1000]
### Short description
_Provide a short description of the issue here. Do not include stacktraces in this sectrion_

Whenever I run my IntelliJ, this jar file is always created in the temp folder sub-path.
I am curious about what this file is.
Can you explain this?

![image](https://user-images.githubusercontent.com/66771063/105192383-60ea3980-5b7b-11eb-9450-b01b6d2e14c8.png)
![image](https://user-images.githubusercontent.com/66771063/105192552-90994180-5b7b-11eb-9bb1-2235f0e6fb0b.png)
![image](https://user-images.githubusercontent.com/66771063/105193675-15845b00-5b7c-11eb-9fe8-a2cf8af14796.png)

### Expected behavior
_Is there a specific expected behavior?_

### Version information

 * **IDEA Version:** _Please provide full IntelliJ IDEA Version - available from About view_

What is this file?

 * **JDK Version:** _What is your JDK version, including update level?_
 * **OS Type & Version:** _Are you on Mac/Windows/Linux? Provide as much information as possible about versions_
 * **Lombok Plugin Version:** _What is the version of the plugin installed?`_
 * **Lombok Dependency Version:** _What version of lombok.jar are you using?_

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. ???
 2. ???
 3. ???

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

STACKTRACE HERE (inside code markup)

```

**Comment by mplushnikov** [comment]
It's used to provide experimental support for @ExtensionMethod, see:
https://github.com/mplushnikov/lombok-intellij-plugin/pull/968 and https://github.com/mplushnikov/lombok-intellij-plugin/issues/21
