### ISSUE TITLE
@SneakyThrows causes incorrect errors in IntelliJ 14

### ISSUE THREAD

**Issue by rick-kilgore** [mplushnikov/lombok-intellij-plugin#101]
I haven't been able to update my lombok plugin for several versions, because every time I do, it incorrectly marks catch clauses as impossible.  Here is an example that captures the gist of what my code looks like:

    @SneakyThrows
    private void hideIt() {
        try {
            itThrows(true);
        } catch (IOException e) {   // <=== IntelliJ flags this catch as an error
            e.printStackTrace();
        }
    }

    private void itThrows(boolean foo) throws Exception {
        if (foo) {
            throw new IOException("test");
        } else {
            throw new Exception("test2");
        }
    }

Since somewhere around plugin version 0.9.0, IntelliJ marks the catch in itThrows() as impossible ("Exception 'java.io.IOException' is never thrown in the corresponding try block").  But it is clearly possible, and javac is fine with this code.  If I remove the @SneakyThrows annotation on hideIt(), the error goes away (and it complains that I need to catch or declare Exception).

**Comment by mplushnikov** [comment]
Should be fixed in the next release 0.9.3
