### ISSUE TITLE
Make Lombok Intellij Plugin compatible with JDK 16

### ISSUE THREAD

**Issue by sblantipodi** [mplushnikov/lombok-intellij-plugin#1019]
Hi,
using IntelliJ Ultimate 2020.3.3 with AdoptJDK 16 and Lombock maven plugin 1.18.18.

Using the Lombok plugin bundled 203.7717.56

When I try to build my project I get this errore:
java: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x68773699) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x68773699

It worked well with JDK 15.

Thank you.

**Comment by leccelecce** [comment]
FYI a temporary (but fairly horrible) workaround has been posted here which involves configuring maven-compiler-plugin: https://stackoverflow.com/a/65382080/1613795

**Comment by sblantipodi** [comment]
> FYI a temporary (but fairly horrible) workaround has been posted here which involves configuring maven-compiler-plugin: https://stackoverflow.com/a/65382080/1613795

Too terrible for my tastes but thanks.

**Comment by bainesap** [comment]
Lombok 1.18.20 was [just released ](https://github.com/rzwitserloot/lombok/issues/2681)with Java 16 support

**Comment by sblantipodi** [comment]
Ok thanks.

**Comment by kuil09** [comment]
So still not fully supported, am I right?

**Comment by sblantipodi** [comment]
it works for me
