### ISSUE TITLE
Lombok plugin should tell developer that old lombok.jar is used on classpath

### ISSUE THREAD

**Issue by novoj** [mplushnikov/lombok-intellij-plugin#103]
I suspect IntelliJ Idea plugin that it causes weird errors if old lombok jar is located on classpath. It would be very nice if Lombok plugin would notify me when I use old (and deprecated) JAR version on classpath (usually in Maven/Gradle config).

This would propably prevent a lot of problems develpers run at.

**Comment by mplushnikov** [comment]
How would you want to define "old" version? Is it anything != current version, or version - x releases?

**Comment by novoj** [comment]
Ideally any version that is incompatible with used IntelliJ Idea plugin. I'm only guessing, but I've experienced weird IntelliJ errors and index corruptions when I had lombok 1.14.2 jar on classpath and 0.9.2 version of the IntelliJ plugin.

Is it possible that there are some dependencies between versions of IntelliJ plugin and JAR on project classpath? Or I was just guessing wrong?!
