### ISSUE TITLE
@SuperBuilder failed to generate builder method with latest IDEA EAP 2021.3

### ISSUE THREAD

**Issue by tchiotludo** [mplushnikov/lombok-intellij-plugin#1071]
This class : https://github.com/kestra-io/kestra/blob/097547fa2d08dcbad3b4a303dfe6743eafd47bb2/core/src/main/java/io/kestra/core/tasks/scripts/Bash.java is totally valid and mark as invalid in the latest EAP :

![image](https://user-images.githubusercontent.com/2064609/136824531-bf50eb2f-9fad-4ce2-bdde-772d5bff7ac7.png)

and don't generate the builder() method :

![image](https://user-images.githubusercontent.com/2064609/136824552-ac043e01-9ca9-4a3c-bef6-4aa13c14460a.png)

**Comment by enveraltin** [comment]
This seems to have broken things in 2021.3 release as well.

**Comment by mzatko** [comment]
temporary workaround is to add @AllArgsConstructor

**Comment by tchiotludo** [comment]
Seen that, but I couldn't in my case since it need to change with `@AllArgsConstructor` all implementation of Based Class. 
I wait for the fix in order to upgrade to last idea so.

**Comment by Kidlike** [comment]
Backlink to the Jetbrains issue report: https://youtrack.jetbrains.com/issue/IDEA-279075

**Comment by tchiotludo** [comment]
fix by intellij idea team
