### ISSUE TITLE
How to build Lombok for use with Android Studio

### ISSUE THREAD

**Issue by jpage4500** [mplushnikov/lombok-intellij-plugin#1079]
### Short description
Several times throughout the years I've updated to the Preview version of Android Studio only to find out that Lombok wasn't compatible with it. 

Eventually by the time the production version of Android Studio is released, Lombok is supported.. but, is there a way to manually build it instead? 

Looking at some of the [pull requests](https://github.com/mplushnikov/lombok-intellij-plugin/pull/1078) it seems like it's fairly easy to get it working on newer versions.. is that right? If it's fairly easy to build the library ourselves, could some details be added to the main README.md?

**Comment by DevDengChao** [comment]
I copied lombok from IDEA 2021.3.1 to Bumblebee 2021.1.1 and it works too. Thanks @jpage4500 .

**Comment by radiorz** [comment]
I copied lombok from IDEA to Android Studio (latest) and it works too. Thanks all.
