### ISSUE TITLE
Getter/Setter wrong after last Update

### ISSUE THREAD

**Issue by virtualmarc** [mplushnikov/lombok-intellij-plugin#108]
Since the last Update to Version 0.9.3.14 the getter and setter are wrong.

I have Attributes like this:

```java
private double dValue;
```

Lombok generates this Getters and Setters:

```java
public double getDValue();
public void setDValue(double dValue);
```

The last Version of this Plugin did the same.

Since the Update the Plugin shows this Getters and Setters which are wrong:

```java
public double getdValue();
public void setdValue(double dValue);
```

This causes auto completion to not correctly work and IntelliJ to mark all Getter and Setter Calls as wrong (Method not exist).

**Comment by mplushnikov** [comment]
This will be fixed in the next release (0.9.4)
