### ISSUE TITLE
Plugin not compatible with IntelliJ IDEA 2021.3.1

### ISSUE THREAD

**Issue by ayoub96anbara** [mplushnikov/lombok-intellij-plugin#1097]
I get the message "Not compatible with the version of your running IDE (IntelliJ IDEA 2021.3.1)" from [https://plugins.jetbrains.com/plugin/6317-lombok/versions](https://plugins.jetbrains.com/plugin/6317-lombok/versions)

**Comment by tonyzheng121** [comment]
I also have this issue

**Comment by ayoub96anbara** [comment]
I think IntelliJ has integrated Lombok without this plugin
