### ISSUE TITLE
@Builder on constructors/methods is not recognized in Android Studio

### ISSUE THREAD

**Issue by WonderCsabo** [mplushnikov/lombok-intellij-plugin#111]
It seems the plugin does not recognize the `@Builder` annotation on constructors. That works similarly to `@Builder` on static methods.

```java
public class Test {
    private  int a;

    @Builder
    private Test(int a) {
        this.a = a;
    }
}
```

**Comment by mplushnikov** [comment]
Can't reproduce any errors, Builder on constructor is supported.
What is your environment? What kind of error do you see?

**Comment by WonderCsabo** [comment]
I a using Android Studio 1.2, which is based on IntelliJ 1.2. 
```java
Test.builder().a(2).build();
```
This codes gets an error in the editor, because the `builder()` static method is not generated. Also *Refactor* -> *Delombok* does not shows the `@Builder` annotation is enabled.

Finally looking at your source code, i only see `BuilderProcessor` and `BuilderMethodProcessor` but no `BuilderConstructorProcessor`.

**Comment by mplushnikov** [comment]
Constructor is a special case of method, there are no need for extra processor.
I have to look on Android Studio, with IntelliJ there are no problems.

**Comment by WonderCsabo** [comment]
I see. It seems `@Builder` on static methods are not working either.

```java
public class Test {
    private  int a;

    private Test(int a) {
        this.a = a;
    }

    @Builder
    static Test create(int a) {
        return new Test(a);
    }
} 
```

I imported the original project to IntelliJ, and it worked well. 
However, my college working on the same project does not experience this in AS.

I also tried this on a brand-new AS installation, and i can still repro. :disappointed_relieved:

**Comment by mg6maciej** [comment]
Just tried it on AS 1.2 with the latest lombok plugin and have no errors shown in the IDE.

`Test.builder().a(6).build();`

Works with both `@lombok.Builder` and deprecated `@lombok.experimental.Builder`.

**Comment by mplushnikov** [comment]
What is your OS? Windows/Linux/MacOs?

**Comment by WonderCsabo** [comment]
@mplushnikov i am not sure this question is pointed to me, but i am using Windows 8.1 x64 (my collegue has the same setup).

**Comment by mplushnikov** [comment]
I can reproduce it with fresh installation of Android Studio also.
Strange error, AS can not determine fully qualified name of the annotation, what breaks the plugin.
You can try a workaround: replace @Builder with fully qualified name "lombok.experimental.Builder"/"lombok.Builder" for example.

**Comment by WonderCsabo** [comment]
Thanks, i can verify that your workaround fixes the problem.

Any idea why is this happening? Should we raise a ticket against AS? And why @mg6maciej and my collegue cannot repro. :confused:

**Comment by mg6maciej** [comment]
I can also reproduce it. I may have used FQCN when switching between experimental and main version.

**Comment by mplushnikov** [comment]
I am not quite sure, it looks like a problem with recursive calls during resolution of class hierarchie. I have changed search for annotation, it should be a little bit more stable now.

**Comment by WonderCsabo** [comment]
Thanks for the fix! I will test this as soon as you publish a version with that change.

**Comment by WonderCsabo** [comment]
Do you plan to release 0.9.5? I really need this feature. I tried to build the plugin myself, but i failed both from IntelliJ and by ant. Needles to say, i do not have expereience of IntelliJ plugins. :disappointed: So actually the proper build instructions would also help.

**Comment by mplushnikov** [comment]
Version 0.9.5 should be available now, please verify it if you can.
