### ISSUE TITLE
[File sharing] Lombok files compatible with Android Studio

### ISSUE THREAD

**Issue by DevDengChao** [mplushnikov/lombok-intellij-plugin#1111]
This is not an issue indeed. I'm just sharing files extracted from IDEA plugins folder.

File | From | Compatible AS versions
---|---|---
[lombok-231.9011.34.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/11671700/lombok-231.9011.34.zip) | IDEA 2023.1.2 | Hedgehog 2023.1.1 Canary 7 +
[lombok-223.8617.56.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/11013424/lombok-223.8617.56.zip) | IDEA 2022.3.2 | Giraffe 2022.3.1 Canary 9
[lombok-223.8214.52.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/10348720/lombok-223.8214.52.zip) | IDEA 2022.3.1 | uncertain
[lombok-223.8214.27.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/10348719/lombok-223.8214.27.zip) | IDEA 2022.3.1 RC | uncertain
[lombok-223.7571.182.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/10241901/223.7571.182-lombok.zip) | IDEA 2022.3 | Giraffe 2022.3.1 Canary 2
[lombok-222.4459.24.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/10284657/lombok-222.4459.24.zip) | IDEA 2022.2.4 | Flamingo 2022.2.1 Canary 10 +
[lombok-222.4345.14.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/9953233/lombok-222.4345.14.zip) | IDEA 2022.2.3 | Flamingo 2022.2.1 Canary 7 ~ 9
[lombok-222.2680.4.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/8794707/lombok-222.2680.4.zip) | IDEA 2022.2 EAP | uncertain
[lombok-222.2270.31.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/8775292/lombok-222.2270.31.zip) | IDEA 2022.2 EAP | uncertain
[lombok-221.6008.13.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/9458098/lombok-221.6008.13.zip) | IDEA 2022.1.4 |  Electric Eel 2022.1.1 Canary 10 +
[lombok-213.7172.25.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/8561180/lombok-213.7172.25.zip) | IDEA 2021.3.3 | Dolphin 2021.3.1 Canary 9+, Electric Eel 2022.1.1 Canary 1 +
[lombok-213.6777.52.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/8130582/lombok-213.6777.52.zip) | IDEA 2021.3.2 | Dolphin 2021.3.1 Canary 4 +
[lombok-212.5712.43.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/8561242/lombok-212.5712.43.zip) | IDEA 2021.2.4 | Chipmunk 2021.2.1 RC 1, Patch 1 +
[lombok-211.7628.21.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/8130713/lombok-211.7628.21.zip) | IDEA 2021.1.3 | Bumblebee 2021.1.1 Patch 2

## How to use

1. Download the zip that is compatible with your Android Studio
2. Install it as a plugin from disk, see tutorial here: https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

## Reference

+ IDEA history versions: https://www.jetbrains.com/idea/download/other.html

## Note

~~Somehow I cannot upload anymore zip files to this comment, see: https://github.com/orgs/community/discussions/31303.~~

~~Maybe there's some kind of limitation that the users cannot attach too much files within a single comment.~~

I can upload files to this comment directly now 🤣

**Comment by DevDengChao** [comment]
Comment if you guys have working lombok files.

**Comment by shipofsea** [comment]
it works well
thanks

**Comment by alexkourtis98** [comment]
Worked for me too : )

**Comment by UnTalRenan** [comment]
lombok-212.5712.43.zip in
Android Studio Chipmunk | 2021.2.1
Build #AI-212.5712.43.2112.8512546, built on April 28, 2022

works well , thanks

**Comment by reason-github** [comment]
> lombok-212.5712.43.zip in Android Studio Chipmunk | 2021.2.1 Build #AI-212.5712.43.2112.8512546, built on April 28, 2022
> 
> works well , thanks

me too

**Comment by Devansh-Maurya** [comment]
Thanks! This is very helpful. 🙌🏽

**Comment by firsthubgit** [comment]
Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 19, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64

not work

**Comment by DevDengChao** [comment]
@firsthubgit Updated, please use [lombok-211.7628.21.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/8130713/lombok-211.7628.21.zip) instead.

Thanks for reporting.

**Comment by DevDengChao** [comment]
Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 19, 2022
Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Non-Bundled Plugins: Lombook Plugin (212.5712.43)

@firsthubgit 212.5712.43 works fine for me, can you please try again ?

**Comment by firsthubgit** [comment]
![image](https://user-images.githubusercontent.com/10082460/174588836-cc875701-6a80-49c0-883f-39e136bd8238.png)
是这个版本，
但是我的lombok还是飘红
![image](https://user-images.githubusercontent.com/10082460/174588934-b8fcee37-0e56-4176-960b-8dd95a34c523.png)
可能我需要重装一下studio吧

**Comment by kopihao** [comment]
plugin posted here works well on my AS. thanks 

<img width="499" alt="image" src="https://user-images.githubusercontent.com/8252002/182526654-05c5e635-4e2c-48ff-887e-f83cbadf8950.png">

**Comment by DISSIDIA-986** [comment]
IntelliJ IDEA 2022.2.1
Build #IU-222.3739.54, built on August 16, 2022
Plugin 'Lombok' (version '0.34.1-2019.1') is not compatible with the current version of the IDE, because it requires build 191.* or older but the current build is IU-222.3739.54

**Comment by DevDengChao** [comment]
File | From | Compatible AS versions
---|---|---
[lombok-222.2680.4.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/8794707/lombok-222.2680.4.zip) | IDEA 2022.2 EAP | not released yet
[lombok-222.2270.31.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/8775292/lombok-222.2270.31.zip) | IDEA 2022.2 EAP | not released yet
[lombok-221.6008.13.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/9458098/lombok-221.6008.13.zip) | IDEA 2022.1.4 |  Electric Eel 2022.1.1 Canary 10+

**Comment by RyanHu** [comment]
老哥给力！

**Comment by wozaihu** [comment]
nice

**Comment by BrunoJay** [comment]
IntelliJ IDEA 2022.2.2
Plugin 'Lombok' (version '222.2270.31') is not compatible with the current version of the IDE, because it requires build 222.2270.31 or older but the current build is IU-222.4167.29

**Comment by diegonz** [comment]
I created a feature request on Google's Issue Tracker requesting to include the plugin directly bundled into Android Studio builds.

Whoever agrees, please click <kbd>+1</kbd> (and maybe add a comment too) to give visibility to the request. Let's hope we're lucky and they take it into account. [Lombok plugin support on Google's Issue Tracker](https://issuetracker.google.com/issues/266333624)

For now, we can track current plugin development in [IntelliJ Community Edition repo](https://github.com/JetBrains/intellij-community). Simply download the proper published IntelliJ release, extract it, and zip the [lombok plugin folder](https://github.com/JetBrains/intellij-community/tree/master/plugins/lombok) to install it from disk.

Hope this helps.

**Comment by GitHubWebb** [comment]
VeryGood

Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 21, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.3
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.intellij.plugins.macoskeymap (221.6008.13)
    com.intellij.marketplace (221.6008.18)
    com.jaeger.findviewbyme (1.4.3)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    Lombook Plugin (221.6008.13)
    zielu.gittoolbox (500.0.2+213)
    com.developerphil.adbidea (1.6.8)

**Comment by zhaoZhao0213** [comment]
NB

**Comment by DevDengChao** [comment]
> I created a feature request on Google's Issue Tracker requesting to include the plugin directly bundled into Android Studio builds.
> 
> Whoever agrees, please click +1 (and maybe add a comment too) to give visibility to the request. Let's hope we're lucky and they take it into account. [Lombok plugin support on Google's Issue Tracker](https://issuetracker.google.com/issues/266333624)
> 
> For now, we can track current plugin development in [IntelliJ Community Edition repo](https://github.com/JetBrains/intellij-community). Simply download the proper published IntelliJ release, extract it, and zip the [lombok plugin folder](https://github.com/JetBrains/intellij-community/tree/master/plugins/lombok) to install it from disk.
> 
> Hope this helps.

---

News: 

+ Marked as fixed. The Lombok IntelliJ Plugin should be bundled in Android Studio 2023.1.1.8. (Editor note: Maybe one of the
Hedgehog RC)
+ FTR Yuriy Artamonov from JetBrains mentioned that eventually the Lombok plugin will be published to the plugin marketplace (in order to make IntelliJ IDEA more lightweight), at which point we will be able to safely unbundle Lombok again.

**Comment by sw-tt-tusharojha** [comment]
@DevDengChao 
I have tried all zip you provided above but Not working for Android Studio Giraffe | 2022.3.1 version. Can you please provide the same. Which One I have to use? Details are as below:-

Android Studio Giraffe | 2022.3.1
Build #AI-223.8836.35.2231.10406996, built on June 29, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.highlighting.mode.essential=true
    documentation.show.toolbar=true

Non-Bundled Plugins:
    Dart (223.8950)
    wu.seal.tool.jsontokotlin (3.7.4)
    idea.plugin.protoeditor (223.8214.6)
    com.robohorse.robopojogenerator (2.4.0)
    mobi.hsz.idea.gitignore (4.4.4)
    io.flutter (74.0.3)

**Comment by DevDengChao** [comment]
@sw-tt-tusharojha 
![image](https://github.com/mplushnikov/lombok-intellij-plugin/assets/16363180/df9e52b0-3443-4c9b-a90d-bc8570b52701)
![image](https://github.com/mplushnikov/lombok-intellij-plugin/assets/16363180/951e0c48-b197-4f27-941f-02fbabec29fc)

It looks like Android Studio Giraffe 2022.3.1 Build 223.8836.35 is based on a custom build other than any released version of IDEA.
You'll need to modify the plugins' supported IDEA version manually as described in https://github.com/mplushnikov/lombok-intellij-plugin/issues/1163 .

**Comment by sw-tt-tusharojha** [comment]
Hi 
@DevDengChao 
it showing error:- Fail to load plugin descriptor from file lombok.jar. Anything I am missing.

**Comment by sahilasopa** [comment]
update 😭😭

**Comment by karthickvasudev** [comment]
Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation

manual plugin support

**Comment by harismiftahulhudha** [comment]
> Android Studio Giraffe | 2022.3.1 Patch 1 Build #AI-223.8836.35.2231.10671973, built on August 17, 2023 Runtime version: 17.0.6+0-b2043.56-10027231 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Windows 10 10.0 GC: G1 Young Generation, G1 Old Generation
> 
> manual plugin support

how to do manual install ?

**Comment by DevDengChao** [comment]
Good News: You can install Lombok plugin by JetBrains from Marketplace on Android Studio Iguana | 2023.2.1 Canary 1 now.

**Comment by Xinghui-Wu** [comment]
> > Android Studio Giraffe | 2022.3.1 Patch 1 Build #AI-223.8836.35.2231.10671973, built on August 17, 2023 Runtime version: 17.0.6+0-b2043.56-10027231 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Windows 10 10.0 GC: G1 Young Generation, G1 Old Generation
> > manual plugin support
> 
> how to do manual install ?

You may try to download the zip file ([lombok-223.8617.56.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/11013424/lombok-223.8617.56.zip)), unzip it and copy the whole folder to the Android Studio plugins directory.

This solution works for me.

**Comment by karthickvasudev** [comment]
@Xinghui-Wu  awesome its working

**Comment by Suchbear** [comment]
> > > Android Studio Giraffe | 2022.3.1 Patch 1 Build #AI-223.8836.35.2231.10671973, built on August 17, 2023 Runtime version: 17.0.6+0-b2043.56-10027231 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Windows 10 10.0 GC: G1 Young Generation, G1 Old Generation
> > > manual plugin support
> > 
> > 
> > how to do manual install ?
> 
> @harismiftahulhudha
> 
> You may try to download the zip file ([lombok-223.8617.56.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/11013424/lombok-223.8617.56.zip)), unzip it and copy the whole folder to the Android Studio plugins directory.
> 
> This solution works for me.

It works,thanks!!!

**Comment by PrithivirajAuckloo** [comment]
Hi, 

I require the Lombok plugin for Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973

Regards
Prithiviraj

**Comment by H-Lo** [comment]
2023-11-30
HELP!!!!

---

Android Studio Giraffe | 2022.3.1 Patch 2
Build #AI-223.8836.35.2231.10811636, built on September 14, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.intellij.marketplace (223.8836.56)
    com.dguner.lombok-builder-helper (1.5.0)

**Comment by ganaaz** [comment]
Not working for this version of Android Studio

Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 9, 2023
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.experimental.ui=true

Non-Bundled Plugins:
    Dart (231.9409)
    io.flutter (77.1.2)

**Comment by H-Lo** [comment]
@ganaaz  Try tuhs one: https://file.io/izIqZVL7DhXo
This is originally "lombok-231.9011.34.zip".
The only thing I did is changed versions range in META-INF: from 200.0000.00 to 250.0000.00.
Now it works with my Hedgehog version.
