### ISSUE TITLE
@Getter annotation functions not recognised in latest Android Studio preview (1.3 Preview 5)

### ISSUE THREAD

**Issue by tom-bell** [mplushnikov/lombok-intellij-plugin#115]
As of Android Studio preview 1.3, methods generated with @Getter and @Setter annotations are not recognised. This could be due to the recent changes under the hood for IntelliJ (C++/C support from Clion) which I think is based off IntelliJ 14.2?

**Comment by mplushnikov** [comment]
Can you verify it with last plugin version (0.9.5) please?

**Comment by tom-bell** [comment]
Apologies for the delay. This appears to be fixed in the latest combination of Android Studio AI-141.2090522 and Lombok plugin 0.9.6.14
