### ISSUE TITLE
Sometimes it works / sometimes doesn't

### ISSUE THREAD

**Issue by fedotxxl** [mplushnikov/lombok-intellij-plugin#117]
Most of features (`@Slf4`j, `@AllArgsConstructor`, `val`, `@Getter`, `@Builder` etc) sometimes work / sometimes don't - IDEA can't resolve method. Manual resaving source file temporary fixes the problem.

This makes hard to use Lombok - it's easier to generate getters/constructors than have troubles with IDE.

**Comment by Janmm14** [comment]
did you enabled annotation processing in the settings?

**Comment by fedotxxl** [comment]
Yes, it's enabled - source code are correctly compiled

**Comment by mplushnikov** [comment]
New plugin version 0.9.5 is available now, can you please verify your problem with new version?

**Comment by mplushnikov** [comment]
I can't reproduce it after 0.9.5 any more. Will close this issue as done. Feel free to open new issue, if you find the problem again.
