### ISSUE TITLE
Lombok plugin 0.34.1 breaks code completion in Android Studio Electric Eel | 2022.1.1

### ISSUE THREAD

**Issue by ykrapiva** [mplushnikov/lombok-intellij-plugin#1171]
### Short description
After installing the plugin 0.34.1 from disk with the patched version in META-INF/plugin.xml as "AI-221.*" code completion stops working, no methods show up after CTRL+SPACE

### Expected behavior
Code completion should work as usual

### Version information

 * **IDEA Version:** Build #AI-221.6008.13.2211.9477386, built on January 11, 2023
 * **JDK Version:** OpenJDK 64-Bit Server VM by JetBrains s.r.o. 11.0.15+0-b2043.56-8887301 aarch64
 * **OS Type & Version:** MacOS Ventura 13.0.1 (22A400)
 * **Lombok Plugin Version:** 0.34.1
 * **Lombok Dependency Version:** 1.18.24

### Steps to reproduce
1. Take plugin 0.34.1, edit the version in META-INF/plugin.xml to "AI-221.*"
2. Install "from disk" in Android Studio Electric Eel | 2022.1.1
3. Add the following into your build.gradle file:
`compileOnly 'org.projectlombok:lombok:1.18.24'
annotationProcessor 'org.projectlombok:lombok:1.18.24'`

5. Try code completion on any class
<img width="576" alt="Screenshot 2023-02-01 at 21 55 02" src="https://user-images.githubusercontent.com/2013690/216149862-f5be2c9b-94c3-43d4-a6c2-ac317cc9e5ca.png">

**Comment by XiaoGuo227** [comment]
Hello, can you upload a plugin

**Comment by ykrapiva** [comment]
[lombok-plugin.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/10609810/lombok-plugin.zip)

Here it is

**Comment by homayoonahmadi** [comment]
Hi there, this worked for me:

[lombok-electric eel.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/10610533/lombok-electric.eel.zip)

**Comment by ykrapiva** [comment]
@homayoonahmadi This is strange, this version works.
Probably my version was corrupted by macos commands I used to patch the plugin.
Thank you !
