### ISSUE TITLE
Android StudioAndroid Studio Electric Eel | 2022.1.1 Support

### ISSUE THREAD

**Issue by XiaoGuo227** [mplushnikov/lombok-intellij-plugin#1172]
[lombok-plugin.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/10579451/lombok-plugin.zip)

**Comment by XiaoGuo227** [comment]
[Related Links](https://blog.csdn.net/ymq267/article/details/127636494)

**Comment by homayoonahmadi** [comment]
The plugin you provided had some problems in code completion. This worked for me:

[lombok-electric eel.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/10610541/lombok-electric.eel.zip)

**Comment by XiaoGuo227** [comment]
> The plugin you provided had some problems in code completion. This worked for me:
> 
> [lombok-electric eel.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/10610541/lombok-electric.eel.zip)

I have no problems during use, you can try to reinstall Android Studio

**Comment by XiaoGuo227** [comment]
> The plugin you provided had some problems in code completion. This worked for me:
> 
> [lombok-electric eel.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/10610541/lombok-electric.eel.zip)

Thank you for your reply and the plugin provided
