### ISSUE TITLE
Plugin doesnt work when build is done with IntelliJ

### ISSUE THREAD

**Issue by tollrakesh** [mplushnikov/lombok-intellij-plugin#124]
We had a Maven project and the project heavily utilizes lombok project. Within the IDE we use the lombok plugin, so that the IDE understands the "implicit" code generated by the plugin. Everything worked fine.

Now, after converting to Gradle builds, though Gradle builds are successful, the "make project" from the IDE doesnt seem to be evaluating the results from lombok plugin anymore. It used to work correctly during a maven build. But, the IDE is still able to recognize the auto generated variables and methods when we view the classes.

**Comment by michaelbannister** [comment]
Does it work if you explicitly enable Annotation Processors? I've found I have to do that (despite the readme saying that's only needed if you're using the Eclipse compiler)
