### ISSUE TITLE
Support for lombok.getter.noIsPrefix

### ISSUE THREAD

**Issue by daytona01** [mplushnikov/lombok-intellij-plugin#125]
We have a Maven Projekt in which it is necessary to get the values from the boolean properties by getProperty and not by isProperty. So we used the lombok.getter.noIsPrefix in the lombok.config file. This worked well for the compilation but  IntelliJ and the Plugin does not recognize that the boolean getProperty method exists.

**Comment by mplushnikov** [comment]
New version (0.11) of plugin was released today. It contains many improvements for configuration system of lombok. This issue should be fixed now.
