### ISSUE TITLE
@XArgsConstructor don't show error when used on a subclass that requires non-empty super call

### ISSUE THREAD

**Issue by toadzky** [mplushnikov/lombok-intellij-plugin#130]
`@XArgsConstructor`s aren't allowed when a parent class requires `super(...)`. In the example below, the second class should have an error because it won't compile.

Example:
```java
@AllArgsConstructor
public class Parent {
   private String name;
}

@AllArgsConstructor 
public class Subclass extends Parent {
   private String value;
}
```

**Comment by Janmm14** [comment]
Your example is missing the ```extends```

**Comment by toadzky** [comment]
Thank you

**Comment by mplushnikov** [comment]
I'll add new validation for this behavior in the next release!

**Comment by mplushnikov** [comment]
Pluginversion with changes for this issue was released today

**Comment by jonathanhandoyo** [comment]
with this additional validation, the above example should be fixed like such?

``` java
@AllArgsConstructor
@NoArgsConstructor //added this one
public class Parent {
   private String attribute1;
}

@AllArgsConstructor 
public class Child extends Parent {
   private String attribute2;
}
```

but in the case where we are extending from a class inside a library?
my current problem is with enums actually. intellij reported an error

``` java
public class EncapsulatingClass {
    @AllArgsConstructor
    @Getter
    public enum SomeEnum {
        ITEM_1 ("item-1"),
        ITEM_2 ("item-2");
        
        private String name;
    }
}
```

it is reporting: `Lombok needs a default constructor in the base class`.
but unlike the top example, i cannot add `@NoArgsConstructor` to the parent class.
am i approaching this wrongly?

**Comment by toadzky** [comment]
does it compile and work when not in intellij?

**Comment by toadzky** [comment]
I don't think adding `@NoArgsConstructor` will fix anything. The child constructor would still need to invoke it, but AFAIK lombok doesn't do that.

**Comment by toadzky** [comment]
I also don't see any parent class on the enum. Did you forget to extend something?

**Comment by jonathanhandoyo** [comment]
The reason i added `@NoArgsConstructor` at the `Parent` class is because the message said `Lombok needs a default constructor in the base class`. Adding `@NoArgsConstructor` made the reported error goes away.

`enum` cannot extend anything, right? internally it always extends `java.lang.Enum<E>` and abstracted with the keyword `enum`.

**Comment by jonathanhandoyo** [comment]
apparently it was a new bug introduced in 0.9.7.
https://github.com/mplushnikov/lombok-intellij-plugin/issues/172
i don't think it creates compilation problem aside from the reported error.
so, i've already uninstalled 0.9.7 and installed 0.9.6.
