### ISSUE TITLE
Make @EqualsAndHashCode(callSuper = true) default

### ISSUE THREAD

**Issue by novoj** [mplushnikov/lombok-intellij-plugin#132]
I alway revrite @EqualsAndHashCode(callSuper = false) generated by intention on @Data annotation on a POJO with a superclass to callSuper = true. I think its the more natural case than the opposite.

Would you consider changing the default settings for this intention, please?

**Comment by mplushnikov** [comment]
Good point!

**Comment by mplushnikov** [comment]
Should be available in the next release!

**Comment by novoj** [comment]
Thanks!

**Comment by mplushnikov** [comment]
Pluginversion with changes for this issue was released today
