### ISSUE TITLE
"Cannot infer arguments" with @RequiredArgsConstructor

### ISSUE THREAD

**Issue by ractive** [mplushnikov/lombok-intellij-plugin#136]
The following code generates a "Cannot infer arguments" error in the IDE although it compiles fine:
```
package ch.local.storage;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

public class LombokBug {
	@Getter
	@RequiredArgsConstructor
	public class Foo<T> {
		private final T object;
		private final int i;
	}

	private <T> Foo<T> createFoo(T t, int i) {
		return new Foo<>(t, i); // "Cannot infer arguments"
	}
}
```

![cannot-infert-argument](https://cloud.githubusercontent.com/assets/783861/9627153/7a0831a2-5162-11e5-9553-c0e3919248ed.png)

**Comment by ractive** [comment]
BTW: The same with @AllArgsConstructor

**Comment by mplushnikov** [comment]
New version 0.10 of the plugin was released today and contains fixes and improvements for this issue.
