### ISSUE TITLE
Private visibility added by @Value not respected by IDE. 

### ISSUE THREAD

**Issue by sfitts** [mplushnikov/lombok-intellij-plugin#137]
The `@Value` annotation will convert all the fields of a class to private.  However, inside the IDE these fields retain their explicitly given visibilty (meaning that it doesn't show a compilation error if you attempt to directly access them).  When you actualy complile the code the error is show, but not prior to that point.

**Comment by mplushnikov** [comment]
Transparent changing of modifiers of existing fields is unfortunately not possible in IntelliJ at the moment.

**Comment by Janmm14** [comment]
Theoretically could you check all field accesses and issue an error yourself at that point?
