### ISSUE TITLE
IDE highlights val as an error if it had reparsed code before the line was completed

### ISSUE THREAD

**Issue by GloomyFolken** [mplushnikov/lombok-intellij-plugin#142]
Intellij IDEA reparses code to highlight errors 300 ms after the last character was typed (this delay can be changed in Settings -> Editor -> General -> Autoreparse delay). If user stops typing after something like "val foo =", IDE will reparse code and highlight val. However, val still will be highlighted after the line is completed. So, the only way to use val is to increase autoreparse delay.
![0](https://cloud.githubusercontent.com/assets/4989473/10245522/e07468f0-6910-11e5-81a9-39cdd61a4f76.png)
![default](https://cloud.githubusercontent.com/assets/4989473/10245523/e2a63310-6910-11e5-9ec2-125ff002a70e.png)

**Comment by mplushnikov** [comment]
@akozlova Maybe you can give me a hint, how we can solve this kind of problem?

**Comment by akozlova** [comment]
That's a core problem, caused by cached type inside PsiTypeElementImpl. We are working on it. Thanks

**Comment by mplushnikov** [comment]
Great! Do you have some issue number to track the progress in youtrack.jetbrains.com?

**Comment by akozlova** [comment]
There are a number of exceptions, youtrack issue is welcome

**Comment by mplushnikov** [comment]
Ok, I'll create some issues in Youtrack.
https://youtrack.jetbrains.com/issue/IDEA-147214

**Comment by mplushnikov** [comment]
Jetbrains guys means: It is fixed in builds 144.839, 143.708  of IntelliJ

**Comment by mplushnikov** [comment]
Looks to work very well with IntelliJ 15.0.3!

**Comment by leduold** [comment]
@mplushnikov IntelliJ 15.0.3 has the problem too.......................

**Comment by akozlova** [comment]
please provide details in IDEA's issue. Thanks
