### ISSUE TITLE
Support UtilityClass

### ISSUE THREAD

**Issue by punkratz312** [mplushnikov/lombok-intellij-plugin#143]
Hi Michail,

first of all thanks for the nice plugin, it´s really nice.

I noticed that the UtilityClass Feature isn´t supported ATM.
How long would it take to support this nice feature?
I know its experimental (ATM), but it seems to be stable and we use it as well.
(https://projectlombok.org/features/experimental/UtilityClass.html)

Looking forward & Best Regards
Vincent

**Comment by Sheigutn** [comment]
I'm currently trying to implement it and going to make a pull request once I'm finished.

**Comment by Sheigutn** [comment]
So, I added basic support for the annotation now:
https://github.com/Sheigutn/lombok-intellij-plugin/commit/13b8665112744936e301f1480d3e6ba430bbf799
The only thing is: I can't add the static modifier while the elements are generated cause I'm not on the event dispatch thread... Maybe @mplushnikov himself can help?

**Comment by Punkratz312** [comment]
@Sheigutn oh wow great, thank you very much. Hopefully @mplushnikov will help you.

**Comment by mplushnikov** [comment]
Thank you Florian, I  will look on your code next days. Transparent changing of modifiers of existing fields is unfortunately not possible in IntelliJ at the moment

**Comment by Sheigutn** [comment]
@mplushnikov Yeah, I also found that out. Maybe it would be possible to add a feature request to IntelliJ that lets plugin developers transparently remove PsiFields and PsiMethods from the ClassInnerStuffCache? (PsiAugmentProvider works by adding its PsiElements in this class)

**Comment by Techcable** [comment]
+1 a very useful feature

**Comment by Punkratz312** [comment]
Hopefully IntelliJ helps us, to make this nice feature working.

**Comment by nabedge** [comment]
+1 please!

**Comment by Scrayos** [comment]
+1 Just ran into this aswell.

**Comment by bannmann-incub8** [comment]
+1

**Comment by rapguit** [comment]
+1

**Comment by Sheigutn** [comment]
I just added support for this annotation in my fork, would be great if @mplushnikov could test it. :)

**Comment by AlexejK** [comment]
@Sheigutn , Im currently changing a little bit in the structure of the project to provide better/cleaner way of doing modifier processing. We shall see what @mplushnikov thinks about it but it would seem that the only conflict there would be `LombokAugmentProvider`part (which is tiny). If you are interested, take a look here: https://github.com/mplushnikov/lombok-intellij-plugin/compare/master...AlexejK:modifier-processor

**Comment by Sheigutn** [comment]
@AlexejK Great, that makes the whole modifier processing easier. :+1:

**Comment by AlexejK** [comment]
@Sheigutn, Do you mind updating your fork for supporting `@UtilityClass` as per the changes in #204? The latter has been merged as you can see and you should be able to adopt to the changes quite nicely.

Feel free to send a PR then as well :)

**Comment by punkratz312** [comment]
Nice, thanks a lot.
