### ISSUE TITLE
Find usages on field should find usages of builder/wither methods

### ISSUE THREAD

**Issue by jkwatson** [mplushnikov/lombok-intellij-plugin#144]
It would be fantastic if the IDEA find-usages worked with `@Builder` and `@Wither` classes, and the fields in them.  There is currently no easy way to find the builder/wither usages of the fields without doing a text search through a project.

**Comment by daniphp** [comment]
This is really a show stopper for me. Can you please increase the priority? Are there other workarounds than text search?

**Comment by Janmm14** [comment]
I don't know wherher the generated mezhods are shown in the file outline, but if they're shown, you can search from there as far as I know.

**Comment by ati90ati** [comment]
I have the same problem. Search not working in IntelliJ IDEA and it's really needed. Could somebody fix this issue?

**Comment by dumont89** [comment]
1. Anywhere in the file invoke "File structure" action (Ctrl + F12 on linux)
2. Select the desired element (constructor, but also works for Lombok generated builder() method when @Builder is present).
3. Invoke "Find usages" action (Alt + F7 on linux)

source: https://stackoverflow.com/a/42394857/648665
