### ISSUE TITLE
Overriding builder() method for @Builder shows false compilation error in Intellij

### ISSUE THREAD

**Issue by alexandervikstrom** [mplushnikov/lombok-intellij-plugin#145]
When overriding the builder() method for the sake of setting default values to a builder, intellij complains:

`'MyBuilderBuilder' is not public in 'path.to.my.package'. Cannot be accessed from outside package.`

``` java
package path.to.my.package;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class MyBuilder {

    private String myString;  
    public static MyBuilderBuilder builder() {
        return new MyBuilderBuilder().myString("my default value");
    }
}
```

However, the code compiles and runs just as expected.

**Comment by slnowak** [comment]
+1, had similar problem few months ago, I thought it's already fixed.

**Comment by pitaatip** [comment]
+1, could you fix it in the next release?

**Comment by regnarock** [comment]
+1, Currently facing the same issue

**Comment by fluxroot** [comment]
+1

**Comment by mikeholler** [comment]
Also having this issue.

**Comment by jelmo** [comment]
Also suffering from this issue.

**Comment by mplushnikov** [comment]
Problem with "multiple newBuilder() methods" should be fixed now by plugin 0.9.8+
Another one ("error on new Builder()") is still under investigation....

**Comment by markalanrichards** [comment]
+1

**Comment by rmittal1105** [comment]
Facing the same issue with new Builder().

**Comment by mbocek** [comment]
+1

**Comment by drcypher** [comment]
My (obvious) workaround is to rename the auto-generated builder method and wrap it with my own version. Unfortunately, I cannot hide this auto-generated method since there's no option to define the visibility of the builder method:

```java
package path.to.my.package;

import lombok.Builder;
import lombok.Data;

@Data
@Builder(builderMethodName = "_builder") // Change method name
public class MyBuilder {

    private String myString;  

    public static MyBuilderBuilder builder() {
        return _builder().myString("my default value"); // Replace Builder constructor with _builder()
    }
}
```

**Comment by jmmoore** [comment]
+1

**Comment by ghost28147** [comment]
+1

**Comment by jtcotton63** [comment]
+1

**Comment by raycursif** [comment]
I have the same issue.
+1

**Comment by tricoman** [comment]
+1 same issue

**Comment by EmhyrVarEmreis** [comment]
+1

**Comment by d0x7** [comment]
+1

**Comment by mitshubh** [comment]
+1. Still facing the issue

**Comment by CreaRo** [comment]
+1. This seems silly. I'll try to send a PR to fix it, if no ones working on it already?
