### ISSUE TITLE
@FieldDefaults(makeFinal = true) and bitwise operators produce an error message

### ISSUE THREAD

**Issue by drusin** [mplushnikov/lombok-intellij-plugin#147]
This is fine:

```java
class A {
	final short s1 = 2;
	final short s2 = 4;

	void foo() {
		short s3 = s1 ^ s2;
	}
}
```

This compiles and runs but produces an error message when looking into the class:
```java
@FieldDefaults(makeFinal = true)
class A {
	short s1 = 2;
	short s2 = 4;

	void foo() {
		short s3 = s1 ^ s2;
	}
}
```

Same with this:
```java
@FieldDefaults(makeFinal = true)
class A {
	short s1 = 2;
	short s2 = 4;

	void foo() {
		short s3 = 1;
		switch (s3) {
			case s1 | s2:
				break;
		}
	}
}
```

It looks like the compiler does not see that the fields are final when checking bitwise operators.

**Comment by mplushnikov** [comment]
Unfortunately, this cannot easily be fixed:( It's the same problem, like in #137 and #56. There are no extension points in Intellij, to change the visibility of existing fields or methods.

**Comment by drusin** [comment]
Thank you for the insightfull comment :)

**Comment by zaretskyy** [comment]
+1
