### ISSUE TITLE
Idea cannot generate another constructor when @NoArgsConstructor is used

### ISSUE THREAD

**Issue by orange-buffalo** [mplushnikov/lombok-intellij-plugin#149]
Assuming we have a class:
```java
@NoArgsConstructor
public class NoArgsConstructorTest {

    private String field;

}
```
Try to generate a constructor with `field` argument (`Code -> Generate -> Constructor`). Error message `Constructor already exists` appears. 

![image](https://cloud.githubusercontent.com/assets/4532247/10573746/0d16fa5a-7652-11e5-9cfd-60b43240b1e7.png)

If you execute the same action with manually written no-args constructor, Idea opens a dialog to select fields to initialize in a new constructor:

![image](https://cloud.githubusercontent.com/assets/4532247/10573778/3e620eb0-7652-11e5-8651-176cc8ba004b.png)

**Comment by Janmm14** [comment]
An issue, for now you can either type yourself or use ```@AllArgsConstructor```

**Comment by orange-buffalo** [comment]
Btw, I believe the following issue is also related to this. 

When one has a class with `@Getter`:
```java
public class GetterTest {
    
    @Getter
    private String filed;
        
}
```
and tries to generate a constructor, Idea inserts the no-args one without a dialog to choose fields to initialize in a constructor.

**Comment by mplushnikov** [comment]
I hope, I found a cause of the problem. Fix should be available in the next release.

**Comment by orange-buffalo** [comment]
Great, thank you! Looking forward to the new release :)

**Comment by mplushnikov** [comment]
Pluginversion with changes for this issue was released today

**Comment by orange-buffalo** [comment]
I've checked the new plugin version, this problem is not reproducible, code generation is working as usual.
Thank you for the fix!

**Comment by orange-buffalo** [comment]
This is again an issue with Version: 0.11.16

**Comment by terryBaz** [comment]
still an issue `0.28-2019.3`

**Comment by TaskStorage** [comment]
Same problem with @Entity annotation in 2019.3.1 but all works fine in 2019.2.4
