### ISSUE TITLE
Builder issues with Accessors

### ISSUE THREAD

**Issue by AsturaPhoenix** [mplushnikov/lombok-intellij-plugin#151]
Builder with Accessors doesn't seem to work right when the field has consecutive caps after the prefix.

Example code:

    import lombok.Builder;
    import lombok.Getter;
    import lombok.experimental.Accessors;

    @Accessors(prefix = "m")
    @Builder
    @Getter
    public class Example {
        private final String mAField;

        public static void main(String[] args) {
            builder().aField("a").build().getAField();
        }
    }

Gradle build works fine, but IntelliJ/Android Studio thinks the method should be called "AField" instead. Fields with 0 or 1 caps right after the prefix are fine, and fields with more caps right after the prefix exhibit this issue.

**Comment by AsturaPhoenix** [comment]
Accessors also seems to interfere with field overriding within the builder:

    import lombok.Builder;
    import lombok.experimental.Accessors;
    
    @Builder
    @Accessors(prefix = "m")
    public class Example {
        public static class ExampleBuilder {
            private String field = "default";
        }
    
        private final String mField;
    }

reports "Variable 'field' is already defined in the scope" (Gradle build succeeds). Removing `@Accessors` and renaming the outer field to `field` gets rid of the issue.

This also calls into question whether the inner field should instead be named `mField`, possibly in response to an inner `@Accessors` annotation, but that might be a discussion for Lombok itself.

**Comment by mplushnikov** [comment]
The are several problems, in fact. For the first I have already implemented a solution. For the others it has yet to be found ...

**Comment by mplushnikov** [comment]
Plugin 0.9.8 was released today
