### ISSUE TITLE
Intellij fails to infer type for constructor defined with @RequiredArgsConstructor

### ISSUE THREAD

**Issue by amisarca** [mplushnikov/lombok-intellij-plugin#157]
I have the following class:
```java
@RequiredArgsConstructor(staticName = "of")
public class Foo<T, E extends Exception> {
    private final Bar<T, E> bar;

    public Bar<T, E> buildBar() {
        // ...
        return bar;
    }
}
```

When I am doing 
```java
Bar<Type, SomeException> bar = Foo.of(new Bar<Type, SomeException>(...)).build();
```
Intellij thinks that the types of bar are ```<Object, Exception>``` instead of ```<Type, SomeException>```, and also if I call ```bar.call()```, it gives an error that Exception is not caught (even though SomeException is; ```bar.call()``` will raise the exception provided as a generic type). Compiling and executing both work fine without any error.

**Comment by mplushnikov** [comment]
Duplicate of #136
