### ISSUE TITLE
Annotation processing is not supported for module cycles. 

### ISSUE THREAD

**Issue by SharpMan** [mplushnikov/lombok-intellij-plugin#161]
you should think about it

**Comment by daniv** [comment]
have the same issue after upgrading intellij 2016.3.5

**Comment by mayworld** [comment]
any solution?

**Comment by atorstling** [comment]
AFAICU this is a limitation in IntelliJs annotation processor support.
If you can live with disabling annotation processing in the modules involved in the cycle - do as follows:

In IntelliJ, go to `Settings -> Build, Execution, Deployment -> Compiler -> Annotation Processors`.
Click the plus icon to create a new profile, say "Disabled".
Uncheck "Enable annotation processing" for the new config.
Select the modules involved in the cycle, click the move icon to move those to the "Disabled" profile.

**Comment by dengjiancai** [comment]
thanks for @atorstling  very much ，i do it and solve the same problem

**Comment by jjmolinera** [comment]
thank you!!

**Comment by SZMOFEI** [comment]
thanks for @atorstling very much ，i spend about two days to solve the same problem,but last find the answer here  .^v^

**Comment by ghostcodelover** [comment]
thanks a lot

**Comment by rafaelspaesleme-ads** [comment]
Obrigado!

**Comment by ruemee** [comment]
thank you it worked

**Comment by yunchaosuper** [comment]
still not work

**Comment by yunchaosuper** [comment]
still not work

**Comment by Gamer08YT** [comment]
Thanks :D

**Comment by SiouWang** [comment]
Thank you very much for telling us! @atorstling

**Comment by tishk** [comment]
thank you very much

**Comment by ZJRui** [comment]
> 

if you set the module  disabled annotation processor ,   the lombok will not work.  and  the get /set method can not be found  when you run it .  so how to solve this problem ?

**Comment by atorstling** [comment]
> > 
> 
> if you set the module disabled annotation processor , the lombok will not work. and the get /set method can not be found when you run it . so how to solve this problem ?

I did put in a disclaimer about this. The real fix is to break the cycle.

**Comment by znerd** [comment]
As @atorstling said, the real fix is to break the cycle.

It wasn't clear to me at first, but the message:
> Annotation processing is not supported for module cycles.
…indicates there is a cyclical dependency between modules, which is causing the issue in the first place.

**Comment by AlessioDiFazio** [comment]
Same here. I fixed it by breaking the maven dependency cycle added by mistake
