### ISSUE TITLE
Can't correctly resolve multiple @Builder methods in same class having partial implementations

### ISSUE THREAD

**Issue by sg-ad** [mplushnikov/lombok-intellij-plugin#165]
It seems that the plugin doesn't correctly process the `@Builder` annotation when it's applied to a second method in the same class _and_ there are already partial implementations of the builders.

Here are two screenshots of the same class with the Builder definitions inverted:

<img width="885" alt="person_builder" src="https://cloud.githubusercontent.com/assets/10407766/11764364/bfa4b734-a0fa-11e5-8fdb-d11b68328243.png">
method declaration reversed:
<img width="896" alt="pet_builder" src="https://cloud.githubusercontent.com/assets/10407766/11764365/cdbfe898-a0fa-11e5-8963-9d2689b58dc4.png">
Similarly, trying to resolve method declarations from an external class (when `PersonBuilder` is the one correctly generated):
Resolving `PersonBuilder`:
<img width="736" alt="screen shot 2015-12-12 at 6 06 35 pm" src="https://cloud.githubusercontent.com/assets/10407766/11764385/3fbe4138-a0fb-11e5-8974-72f502cd2e59.png">
Resolving incorrectly for `PetBuilder`:
<img width="696" alt="screen shot 2015-12-12 at 6 07 02 pm" src="https://cloud.githubusercontent.com/assets/10407766/11764387/4e9bc054-a0fb-11e5-8aff-9b83e520c2ea.png">

Thanks!

**Comment by mplushnikov** [comment]
Thank you for good description/example. I'll investigate this issue.

**Comment by mplushnikov** [comment]
Found the cause of the problem and I'll provide correct behaviour in the next version!

**Comment by sg-ad** [comment]
Great!  Thanks!

**Comment by mplushnikov** [comment]
Plugin 0.9.8 was released today

**Comment by jl4347** [comment]
@sg-ad I was trying to use two @Builder for two different methods, aBuilder and bBuilder, in a single TestUtils class, but when I call the bBuilder and run the test, aBuilder was called instead? Have you run into this problem?

**Comment by Gwendal-LE-CREN** [comment]
I run into the same issue as the one from jl4347 :
With multiple @Builder methods in same class having same return type and same buildMethodName, whatever builder I call, only the first one is called.

**Comment by agibsonccc** [comment]
I'm running in to this as well with 2 different method names.

**Comment by aviadpines** [comment]
Not sure that it's still relevant, but I've encountered the same issue and resolved this by specifically setting the `builderClassName`

```
@Builder(builderMethodName = "relaxedBuilder", builderClassName = "RelaxedBuilder") 
private MyClass( ... )

@Builder(builderMethodName = "builder") 
private MyClass( ... )
```

and usage:

```
MyClass.builder()

MyClass.relaxedBuilder()
```
