### ISSUE TITLE
IntelliJ doesn't find unused declaration when @NoArgsConstructor, @RequiredArgsConstructor or @AllArgsConstructor annotations are used

### ISSUE THREAD

**Issue by JessevanAssen** [mplushnikov/lombok-intellij-plugin#166]
I have the following class:

```
@NoArgsConstructor
public class Test {
	private static final String UNUSED = "unused";
}
```

IntelliJ doesn't warn me that `UNUSED` is not used. The "Unused declaration" inspection also doesn't find anything suspicious. If I remove the `@NoArgsConstructor` annotation, both IntelliJ and the inspection notice that `UNUSED` isn't used.

Plugin version: 0.9.6.14
IntelliJ version: 15.0.2

**Comment by mplushnikov** [comment]
Please verify current plugin version 0.9.7. I think changes for other issue (#149) have fixed this too.

**Comment by JessevanAssen** [comment]
0.9.7 indeed fixes it, at least in the provided test case. Thanks!
