### ISSUE TITLE
val does not work with generic method calls as the initializer expression

### ISSUE THREAD

**Issue by jimmec** [mplushnikov/lombok-intellij-plugin#168]
I'm creating a seperate issue for this because I think it can be fixed without work from JetBrains.

This case seems to be caused by incorrect type inference in the plugin's [ValProcessor implementation](https://github.com/mplushnikov/lombok-intellij-plugin/blob/e66bdbeafa8fa00b2af487f0ef355bcae5c915e0/lombok-plugin/src/main/java/de/plushnikov/intellij/plugin/processor/ValProcessor.java) when the variable initializer expression is a generic method call expression. 

Here's the bug, using Intellij 15.0.2 and Lombok plugin 0.9.6.14:
```java
class Demo {
        public static <T> List<T> forClass(Class<T> clazz) {
            return new ArrayList<T>();
        }

        public static void main(String[] args) {
            val myList = Demo.forClass(Integer.class);
        }
    }
```
Where Intellij highlights val with error message 'Unknown class: java.lang.Object'. So it looks like the lombok plugin wasn't able to figure out the type of the expression ```Demo.forClass(Integer.class)``` which the java8 compiler should be able to.

And to illustrate why I think this is a plugin issue, not IDEA bug:
If we start with this code:
```java
class Demo {
        public static <T> List<T> forClass(Class<T> clazz) {
            return new ArrayList<T>();
        }

        public static void main(String[] args) {
            Demo.forClass(Integer.class);
        }
    }
```
Then pressing ```CMD+ALT+V```[ref](http://blog.jetbrains.com/idea/2010/11/smarter-and-faster-introduce-variable-in-java/) on the line
```java
Demo.forClass(Integer.class);
```
Intellij correctly refactors the line to 
```java 
List<Integer> aClass = Demo.forClass(Integer.class);
```
So Intellij is able to perform the correct type inference, but the plugin cannot. This is a little inconvenient as it's blocking me from using val with things like Mockito's ArgumentCaptor.forClass() factory methods.

**Comment by RawToast** [comment]
I am having similar issues after upgrading to the latest intellij (15.0.2), but this was working for me on the last version v14 I was using.

For example I have code using the javax.ws.rs.core.Response class using this method:
public abstract <T> T readEntity(Class<T> entityType);

Which used to work without warnings on intellij 14, but now is highlighted as en error 'Unknown class: java.lang.Object'.

**Comment by jimmec** [comment]
Yep I realized I had written code in 15.0.1 where this issue didn't occur. I wonder what changed in 15.0.2? 

I still feel like a plugin change could address it since IDEA is able to do the type inference.

**Comment by leduold** [comment]
which version will get the problem solved???

**Comment by mplushnikov** [comment]
New version 0.10 of the plugin was released today and contains fixes and improvements for this issue.
