### ISSUE TITLE
Doesn't work with intellij15, JDK8 and Maven

### ISSUE THREAD

**Issue by MarcinMilewski** [mplushnikov/lombok-intellij-plugin#171]
After add dependency to pom, enable plugin and enable annotations, compilation with Maven fails with 'cannot find symbol ' on generated getters and setters.

**Comment by mplushnikov** [comment]
Please verify your project on command line build with "mvn clean install". If it doesn't work with maven build, then you have some other issues (nothing with intellij-plugin) and can try to ask for help by lombok community: https://groups.google.com/forum/#!forum/project-lombok
