### ISSUE TITLE
"Lombok needs a default constructor in the base class" error in enum

### ISSUE THREAD

**Issue by tafit3** [mplushnikov/lombok-intellij-plugin#172]
After updating the plugin to 0.9.7 there are errors in enum classes that use lombok annotations. The non-enum classes show no errors. There were no problems with the previous version of the plugin (0.9.6).

![lombok_needs_a_default_constructor_in_the_base_class](https://cloud.githubusercontent.com/assets/1242852/12237256/200be3f0-b87e-11e5-91b9-e3aa887804d6.png)

IntelliJ IDEA 15.0.2 (IU-143.1184)
JRE: 1.8.0_65 amd64 (Oracle Java HotSpot 64-bit Server VM), Windows 7

**Comment by AgentLV** [comment]
Can confirm this error. Also had this after updating to 0.9.7 from 0.9.6.
I can build the project, but I also get this error.
IntelliJ IDEA 15.0.2 (IU-143.1184)
JRE: 1.8.0_66 amd64 (Oracle Java HotSpot 64-bit Server VM), Windows 7

**Comment by Sangdol** [comment]
For someone who doesn't want to wait until 0.9.8 to be released, 

1. Remove Lombok plugin
2. Download 0.9.6.14 from https://plugins.jetbrains.com/plugin/6317
3. Install the jar by clicking 'Install plugin from disk...'

**Comment by vict0r81** [comment]
Same thing with IDEA 15.0.2 & 0.9.7.15

**Comment by agilisticdev** [comment]
The workaround works very well. Thanks guys!

**Comment by mplushnikov** [comment]
Plugin 0.9.8 was released today
