### ISSUE TITLE
@Getter does not support noIsPrefix

### ISSUE THREAD

**Issue by clayreimann** [mplushnikov/lombok-intellij-plugin#173]
![screen shot 2016-01-14 at 9 48 40 am](https://cloud.githubusercontent.com/assets/930039/12329049/053f5c14-baa4-11e5-87b4-6190abf282e3.png)

**Comment by mplushnikov** [comment]
@Getter doesn't have such value.
https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/Getter.java

**Comment by clayreimann** [comment]
Then what are they talking about on [the website](https://projectlombok.org/features/GetterSetter.html)?

> lombok.getter.noIsPrefix = [true | false] (default: false)
If set to true, getters generated for boolean fields will use the get prefix instead of the defaultis prefix, and any generated code that calls getters, such as @ToString, will also use get instead of is

**Comment by mkochenough** [comment]
This is a key for a configuration file. This is described at https://projectlombok.org/features/configuration.html
