### ISSUE TITLE
Add support for @Tolerate for @Getter and @Setter

### ISSUE THREAD

**Issue by Lekanich** [mplushnikov/lombok-intellij-plugin#175]
From Small print:
`` If the generation of a method is skipped for this reason, a warning is emitted instead. Varargs count as 0 to N parameters. You can mark any method with @lombok.experimental.Tolerate to hide them from lombok.``
https://projectlombok.org/features/GetterSetter.html
Example:
```java
public class T {
    @Setter
    int some = 1;

   @Tolerate
   public void setSome(String some) {}
}
```
Plugin doesn't generate setter, but lombok (annotation processor) creates it.

**Comment by mplushnikov** [comment]
Ok, I think you are right. At the moment plugin only look for @Tolerate by @Data and @Value processing.
I will add @Getter and @Setter handling too.

**Comment by mplushnikov** [comment]
I added support for Tolerate with Getter/Setter just now. The next build of plugin 0.9.8 should contains it.

**Comment by mplushnikov** [comment]
Plugin 0.9.8 was released today
