### ISSUE TITLE
Unchecked warning when using static constructor for @Data and @Value on parameterized class 

### ISSUE THREAD

**Issue by rs3vans** [mplushnikov/lombok-intellij-plugin#176]
Say I have a simple `@Value` class:

```java
@Value(staticConstructor = "of")
public class ValueObject<T> {

    private T name;
    private int count;
}
```

When using the static method `of` to create instances, IntelliJ marks the line with an "Unchecked assignment" warning:

```java
ValueObject<String> valueObject = ValueObject.of("thing1", 10);  // warning on the call to "of"
```

When compiled, there is no warning generated.

**Comment by mplushnikov** [comment]
New version 0.10 of the plugin was released today and contains fixes and improvements for this issue.
