### ISSUE TITLE
@Wither and inherited properties

### ISSUE THREAD

**Issue by RAnders00** [mplushnikov/lombok-intellij-plugin#178]
Consider the following scenario:

```java
@Getter
@RequiredArgsConstructor
public class MyBaseClass {
    private String baseProperty;
}
```

```java
@Getter
public class MySuperClass extends MyBaseClass {

    public MySuperClass(@NonNull String baseProperty, @NonNull String superProperty) {
        super(baseProperty);
        this.superProperty = superProperty;
    }

    @Wither
    private String superProperty;
}
```

Expected: A `withSuperProperty(String s)` is generated that creates a new object with the same inherited `baseProperty` (by using the provided constructor).

Actual: The code does not compile, since no appropriate constructor with only the parameter `java.lang.String` is found.

---

I am not sure whether this it's right to start resolving this issue at `@Wither` - `@XArgsConstructor` for example does not support these inherited properties as well. Maybe, if the issue is first resolved there, it may be easier for `@Wither`? I haven't had a look at the codebase, so this is only a thought. If it's nonsense, just ignore it, please.

**Comment by mplushnikov** [comment]
You are right, this is impossible at the moment. This is restriction of lombok, like [here](https://github.com/rzwitserloot/lombok/issues/182) 
Wither looks only for a constructor with parameters for all fields of the current class. It doesn't look for fields/constructors from the inherited classes. 
Maybe you ask lombok authors (@rzwitserloot, @rspilker ) if they could make it possible. At the moment intellij-lombok-plugin can't do anything.

**Comment by RAnders00** [comment]
Oh wow. I actually wanted to post this on the lombok tracker and not here and never noticed. Thank you for explicitly pointing that out, I would not have noticed that otherwise. Wow.
