### ISSUE TITLE
Low performance of @Builder analysis

### ISSUE THREAD

**Issue by orange-buffalo** [mplushnikov/lombok-intellij-plugin#180]
When Idea performs code analysis for the first time (file is opened after restart), it takes much time to analyze the `@Builder`.
According to the CPU profiling, `de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments` is called recursively, total executions for a class with one Builder of 6 arguments is around 120k times. 
![image](https://cloud.githubusercontent.com/assets/4532247/12702507/b14a9836-c82b-11e5-98e1-d431bcb594a2.png)
I am not sure if the root cause is in this particular method, this is the rough analysis of YourKit CPU snapshot. But it really looks like `@Builder` is slow, because
* classes with other lombok annotations are processed much faster
* we have a "mother" class which calls around 20 different builders, and it takes 40s on i7 to analyze this class.

**Comment by mplushnikov** [comment]
Hello Bogdan!

Can you provide some code to verify this issue please? 

All my own  Test-Builder-Classes are possible too small to show such dramatically performance failing.

**Comment by orange-buffalo** [comment]
Hi Michail!

I am facing this on the code base of large project. I've [prepared the simplified version of the classes](https://gist.github.com/orange-buffalo/327073f3b238643fcd42) (jaxb and mapping annotations removed). CPU profiling from ticket's description was taken during `AddressImpl` analysis.  I hope this will be enough to check the issue. If not, apparently it means that the reason of performance degradation is the combination of huge source code base and annotation processing (we are using lombok very intensively)...

**Comment by mplushnikov** [comment]
I have changed a little bit, can you test provided build in your environment?
https://github.com/mplushnikov/lombok-intellij-plugin/releases/download/test_preview_issue_180/lombok-plugin-0.10.15.preview.zip

Unfortunately, I cannot reproduce bad performance on my setup. I think it can have something with your other annotations defined on Builder-classes. Can you provide more data from your project? You can write me email directly.

According to you profiler: 
The number of invocations looks OK:
119000 of getAugments() results to 1800 invocations of cached processing. The question is still why the real only 475 invocations of plugin-logic are so slowly...
Maybe you can provide some snapshot data from yourkit for me to deeper look on?

**Comment by orange-buffalo** [comment]
I've tested this build, it looks very promising! The performance of the slowest class analysis is improved from 40s to 12s (with lombok plugin disabled it takes 3-4s to analyze this class). 

I also sent you an email with details and profile snapshot link.

**Comment by mplushnikov** [comment]
Thank you very much, I'm happy being on the right way! 40s to 12s is already huge improvement.:)
I have deeper look on your snapshot and saw that the problem was not really in Builder-processing, but in val-processing.
I hope you can, it would be really cool, if you could make new snapshot with this new build to help me figure out another bottleneck of processing.

**Comment by orange-buffalo** [comment]
Yes, for sure, the performance gain is really nice!
I've made new snapshots with this build (the links are sent in the email).

**Comment by mplushnikov** [comment]
Thanks! I see a lot of surprising things in your snapshots. Something that i didn't seen in my own tests before. I will try to work on some points, that should give good performance boost.

**Comment by mplushnikov** [comment]
Hello Bogdan,

I was working last several days on the issue again. Now, I have added much more optimization for the slowest paths of annotation processing. As I can see in the profiler, it should be much better. 
I would be very grateful if you could test the [new preview version](https://github.com/mplushnikov/lombok-intellij-plugin/releases/download/test_2_preview_issue_180/lombok-plugin-0.10.15.16.zip)  again in your environment and maybe make new snapshot in your profiler.

Thank you very much!

**Comment by orange-buffalo** [comment]
Hello Michail,

Thank you very much for your efforts! 
I have checked this preview, it looks very good. The small file is processed momentary. The analysis time of the large class (with dozens of builder methods) is reduced from 12 to 4-5 sec, which is basically the processing time when plugin is disabled. I also noticed better performance while working with lombok-enriched classes, for instance faster autocomplete and method navigation (or maybe this is a placebo effect :)).

I didn't take new snapshots, because my opinion is that the build is already very good and does not require additional tuning. But if you need them for your analysis, please let me know, it's not a problem to capture some.

Again, thank you for continuous improvements!

**Comment by mplushnikov** [comment]
I'm very happy to hear it! Great, then I can save up the other ideas for performance improvement for the next time:-)
The current changes will be available in the next regular version of plugin. 
Now I can focus on some other defects and improvements for the next version.

**Comment by mplushnikov** [comment]
New version 0.10 of the plugin was released today and contains fixes and improvements for this issue.
