### ISSUE TITLE
Find usages doesn't work (for example Accessors with Setter/Getter)

### ISSUE THREAD

**Issue by holub** [mplushnikov/lombok-intellij-plugin#186]
"Find usage" IDE feature doesn't produce any results for fields annotated with @Getter and @Setter.

lombok plugin: 0.9.8.15

IntelliJ IDEA (Minerva) IU-144.3600.7
Build #IU-144.3600, built on February 2, 2016
JRE: 1.8.0_40-release-b127 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by mplushnikov** [comment]
Please provide an example of code to reproduce this issue. 
I cann't reproduce it with my simple example.
![image](https://cloud.githubusercontent.com/assets/1204509/12866474/b405910a-ccce-11e5-97d9-0701a2c086e5.png)

**Comment by holub** [comment]
Could you try this?

    @Getter
    @Accessors(fluent = true)
    final Password password;

**Comment by mplushnikov** [comment]
Ok, thank you! Now I understand, what do you mean.

**Comment by mplushnikov** [comment]
Similar Issue for Builder/Wither #144

**Comment by tlinkowski** [comment]
+1

Since I use `@Accessors(fluent = true)` quite often, this issue becomes a nuisance.

**Comment by ccronemberger** [comment]
This is not working on version 0.17-2018.1 with or without @Accessors.

**Comment by ccronemberger** [comment]
It works for an attribute of type String, but does not work for an arbitrary class.
