### ISSUE TITLE
val and Java 8 streams.

### ISSUE THREAD

**Issue by artgryn** [mplushnikov/lombok-intellij-plugin#189]
val not recognised when using together with *.stream().*

```
val list = projects.getAllProjects();
List<String> result = list.stream().forEach(item -> {// my code}); <- list can not be recognized 
```

**Comment by AlexejK** [comment]
see #137 and #158 . Due to limitations in IntelliJ API val are non-final from intellij's point of view.

However your code will never work because `forEach()` is a terminal void operation. You can still access ìtem` in lambda without problems.
