### ISSUE TITLE
Support for annotations within `onX` methods

### ISSUE THREAD

**Issue by vicmosin** [mplushnikov/lombok-intellij-plugin#190]
Is it lombok's or intelliJ plugin's restrictions?

`@AllArgsConstructor(access = AccessLevel.PRIVATE, onConstructor = @__(@Builder))` seems to not work..

**Comment by AlexejK** [comment]
Interesting, with this plugin and lombok `1.16.6` I'm using `@RequiredArgsConstructor(onConstructor= @__(@Autowired))` without any issues.

**Comment by vicmosin** [comment]
@AlexejK yes, most of the java/spring annotations work fine. But not the lombok's one I guess.

**Comment by AlexejK** [comment]
Well it's very possible it's still a bit buggy.. I did not test if the same thing works in Eclipse, but it's worth noting that `onX` is an experimental feature.

> This feature is considered 'workaround status' - it exists in order to allow users of lombok that cannot work without this feature to have access to it anyway. If we find a better way to implement this feature, or some future java version introduces an alternative strategy, this feature can disappear without a reasonable deprecation period. Also, this feature may not work in future versions of javac. Use at your own discretion.

https://projectlombok.org/features/experimental/onX.html

**Comment by AlexejK** [comment]
By the way, do you know if it even works in Eclipse?  I'm not sure what the usecase for this type of usage is. 

Less related:
Also worth noting that with spring framework specifically as of upcoming version 4.3 you will no longer need onX for constructors due to support of automatic wiring etc. But this ofc just spring related thing

**Comment by mplushnikov** [comment]
I think this is at first lombok restriction. You can test it simple by writing code and trying to compile it with javac. You will see an error from the compiler, like here:
![image](https://cloud.githubusercontent.com/assets/1204509/14043782/69052cb2-f288-11e5-97ed-15d5f59d090d.png)

And of course intellij-lombok-plugin can nothing support, what is unsupported by lombok itself.
