### ISSUE TITLE
Needing to add lombok.jar to classpath?

### ISSUE THREAD

**Issue by nullren** [mplushnikov/lombok-intellij-plugin#194]
Just wanting clarification with the README.

Following the installation instructions was not enough for me to start using lombok in my project. Ultimately, what I had to do was also do one of the following:
* through Project Structure, Global Libraries, add maven library "org.projectlombok:lombok:1.16.2", then Copy to Project Libraries
* download lombok.jar, then through Project Structure, SDKs, add to my SDK's classpath the jar I downloaded

So I wanted to know, is this just obvious stuff that goes without saying? Is there a preferred method?

**Comment by Janmm14** [comment]
This depends on the IDE used.

**Comment by Janmm14** [comment]
I am using this while having the plugin installed, annotation processing on (using javac compiler) and lombok as a provided maven dependency.

This works for me without issues.

**Comment by nullren** [comment]
I suppose this can be closed because it might just have more to do with the wonky build system I'm using more so than this plugin. Lombok is only a build time dependency and that might confuse things.
