### ISSUE TITLE
@Getter(lazy=true) does not reveal AtomicReference member

### ISSUE THREAD

**Issue by joke** [mplushnikov/lombok-intellij-plugin#195]
Hi,

the member variable of the lazy getter is not revealed. Wherefore type of the underlying AtomicReference is not detected correctly and hence the set operating can not be resolved.

```
@Getter(lazy = true)
private final String cachedValue = generatingFunction();
 
private void reset() {
  this.cachedValue.set(null);
}
```

The code compiles perfectly though.

Regards
Joke

**Comment by mplushnikov** [comment]
Hello Joke,

I think it's a very bad practice.

As you can see by [lombok documentation:](https://projectlombok.org/features/GetterLazy.html)

> You should never refer to the field directly, always use the getter generated by lombok, because the type of the field will be mangled into an AtomicReference. Do not try to directly access this AtomicReference; if it points to itself, the value has been calculated, and it is null. If the reference points to null, then the value has not been calculated. This behaviour may change in future versions. Therefore, always use the generated getter to access your field!

 I am afraid it couldn't be fixed it at the moment.
