### ISSUE TITLE
lombok plugin overrides diamond-inspection severity

### ISSUE THREAD

**Issue by kirviq** [mplushnikov/lombok-intellij-plugin#200]
Since version 0.9.8 the lombok plugin hardcodes the severity of the Convert2Diamond inspection to "warning".

If there is no way to preserve the configured severity, a setting to turn the fix to https://github.com/mplushnikov/lombok-intellij-plugin/issues/153 off would be a workaround.

**Comment by mplushnikov** [comment]
With last changes in original inspection (https://github.com/JetBrains/intellij-community/commit/738850d65f1dfbc6e2e1a9d43857de55d77f9b49)
lombok_plugin will not overwrite diamond inspection any more.
see also #359
