### ISSUE TITLE
com.intellij.util.PathUtil.toSystemIndependentName(Ljava/lang/String;)Ljava/lang/String;

### ISSUE THREAD

**Issue by ESmilic** [mplushnikov/lombok-intellij-plugin#201]
[error.txt](https://github.com/mplushnikov/lombok-intellij-plugin/files/204286/error.txt)
Intellij Idea 13.0.4

**Comment by mplushnikov** [comment]
You should be able to update to IntelliJ 13.1.6 at least I think. [Intellij Download](https://confluence.jetbrains.com/display/IntelliJIDEA/Previous+IntelliJ+IDEA+Releases) This is the version of Intellij I use to check plugin compatibility with.
Why are you using 13.0.4 version?

**Comment by ESmilic** [comment]
switched to 13.1.6, thanks
