### ISSUE TITLE
onConstructor handling

### ISSUE THREAD

**Issue by mkochenough** [mplushnikov/lombok-intellij-plugin#207]
Lombok provides a nice trick to generate constructors with additional annotations added to them. This helps a lot with writing code that uses dependency injection, e.g. with Spring Framework.

A simple testcase looks as following:

@Component
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
public class SomeService {

    private final SomeRepository someRepository;

    private final AnotherRepository anotherRepository;

    public void someLogic() {

    }
}

The problem is that that Lombok Intellij plugin doesn't seem to understand Lombok's specific @__ syntax.

**Comment by AlexejK** [comment]
It works for me with Spring Framework, Latest intelliJ version and latest Lombok Plugin version.
What versions are you using?

**Comment by mkochenough** [comment]
I'm using IntelliJ 2016.1.1, Lombok plugin 0.11.16, and lombok 1.16.8.

The error message I get is:

Error:(18, 43) java: cannot find symbol
  symbol: class __

I uploaded a test project to https://github.com/mkochenough/lombok-test

**Comment by AlexejK** [comment]
it would seem that you do not have annotation processing enabled for your IntelliJ, according to `.idea/compiler.xml`

For lombok to work, please enable it.

**Comment by mkochenough** [comment]
You are right. I setup a new IntelliJ and totally forgot about this. Sorry for the annoyance.

**Comment by AlexejK** [comment]
No problem, glad this works for you now!

**Comment by echoyinke** [comment]
it does not work ,even I enabled it,why?

**Comment by echoyinke** [comment]
I have the same issue with him ,even i enable the annotation prossession

**Comment by rkumarp** [comment]
It doesn't work for me either. Using the following annotation:
`@AllArgsConstructor(onConstructor = @__(@Inject)`

Others annotations seem to be working fine.

**Comment by rsharm7** [comment]
+1

**Comment by xiaohaoo** [comment]
@RequiredArgsConstructor(onConstructor_={@Autowired})  这样写法标红呢

**Comment by diasdev** [comment]
This is still happening for Intellij 2020.3 and latest lombok plugin version.

@AllArgsConstructor(onConstructor = @__(@Inject)
cannot find symbol
symbol: class __

**Comment by musashifraco** [comment]
I had the same problem with intellij in version 2023.3.1.

Solution: install and enable the lombok plugin in intellij idea.
