### ISSUE TITLE
Changing log annotation requires restart of Intellij to work

### ISSUE THREAD

**Issue by ByteFlinger** [mplushnikov/lombok-intellij-plugin#210]
Hi

When I have a class with some log annotation, for example @Slf4j, and 
then I change it to another log annotation like @Log4j2, it seems that 
the change is not taken effect and Intellij shows an error in all log 
variables as if there was no such variable.

The only way to fix it from what I can see it to restart Intellij.

**Comment by mplushnikov** [comment]
The root cause of this problems seems to be a result of the aggressive optimization for some of performance problem. I'll investigate it...

**Comment by Janmm14** [comment]
@mplushnikov maybe add a simple clear lombok cache somewhere in the menu?

**Comment by maksymbaziuk** [comment]
Any update on this? Not very comfortable to reload IDEA after any change)

**Comment by mplushnikov** [comment]
The next version of plugin 0.16 should fix this problem.
