### ISSUE TITLE
IDEA inspection "Field may be 'final'" triggers in spite of @Setter

### ISSUE THREAD

**Issue by eekboom** [mplushnikov/lombok-intellij-plugin#212]
IDEA's inspection "Field may be final" triggers incorrectly on this field:

```
@Setter
@Getter
public class Foo {

    private String bar;

    protected Foo() {
        this.bar = "beep";
    }
}
```

Lombok plugin: 0.11.16
IDEA: IU-145.844.1 (2016.1.1 bug fix EAP from https://confluence.jetbrains.com/display/IDEADEV/IDEA+2016.1+EAP )

**Comment by AlexejK** [comment]
This is interesting. Could you provide a sample project that reproduces this? Also please make sure that you have annotation processing enabled.

You can double-check it by looking at `.idea/compiler.xml` and see if it's enabled there for default annotation processing.

**Comment by eekboom** [comment]
Here's the project. Annotation processing is enabled and IDEA is fine with code that calls the lombok-generated setter.
[final.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/213098/final.zip)

**Comment by AlexejK** [comment]
Thank you, it can now be reproduced after inspecting your setup.

**Comment by eekboom** [comment]
Is there any workaround? I would really like to enable the inspection again in IDEA.

**Comment by mplushnikov** [comment]
Hello @eekboom, unfortunately there is no workaround at the moment. But I can add some logic to help Intellij to skip this Inspection, if the field/class is annotated by @Setter/@Data/@Value. Is it something what could help you?

**Comment by eekboom** [comment]
Yes. That would be great. It also is the correct fix, isn't it?

**Comment by mplushnikov** [comment]
Hmh, yes:), it was correct fix. I thought first, i have to look for all usages of generated setter to determine if it is used or not. But existence of a getter would be enough.

**Comment by hutzli** [comment]
Same problem for the @Builder annotation in IntelliJ 2020.2

**Comment by fedorl** [comment]
Probably the same for @Expose
