### ISSUE TITLE
Lombok doesn't work with Intellij Idea 2016.1.1

### ISSUE THREAD

**Issue by FiMka** [mplushnikov/lombok-intellij-plugin#213]
Hello,

Could you please help me to understand what I'm doing wrong.
I installed lombok v. 0.11.16 in Idea 2016.1.1, restarted IDE, then enabled annotation processors from project and IDE preferences. But if I import lombok.* or use any lombok annotation, the IDE is not able to recognise the library: cannot resolve lombok.
Any help would be highly appreciated. Thanks.

Maxim

**Comment by AlexejK** [comment]
you need to add lombok itself to your project as a dependency. The plugin only lets IDE recognize lombok transformations, but doesn't add "org.projectlombok:lombok:1.16.8" to your dependency list

**Comment by FiMka** [comment]
Hi Alexey! Great thanks for the detailed answer, you're absoultely right, I've just added the library and all is fine for now. :+1:
