### ISSUE TITLE
@Singular clearXXX not recognized

### ISSUE THREAD

**Issue by brunelloriserva** [mplushnikov/lombok-intellij-plugin#225]
When using the clearXXX methods for @Builder fields annotated with @Singular, you get a 'Cannot resolve method' error in the editor.  I am running version 0.11.16 of the plugin and IntelliJ Ultimate 2016.1.1.

**Comment by AlexejK** [comment]
Lombok features of v1.16.8 are not currently supported.  See #192

**Comment by mplushnikov** [comment]
Support for clearXXX methods for @Builder and @Singular annotated classes will be available in the next release of plugin (>= 0.12)
