### ISSUE TITLE
Check onMethod annotations

### ISSUE THREAD

**Issue by Janmm14** [mplushnikov/lombok-intellij-plugin#229]
### `onMethod` annotations are not checked

`onMethod` can basically contain any annotation as often as you want without an error being displayed (whether the annotation is marked as Repeatable is not relevant) while compilation failes as expected.

Here is a special case issue you might want to consider handling:
### No error displayed on duplicated `@NonNull` although being on the field and defined in `onMethod`

Error on compilation: `lombok.NonNull is not a repeatable annotation type`
Example code:

```
import lombok.Getter;
import lombok.NonNull;

public class Test {

    @NonNull
    @Getter(onMethod = @__({@NonNull}))
    private Object list;
}
```

This issue is bound to `NonNull` named annotations which are no subclasses, other annotations are not copied to the getter by lombok.

Similar issue happens with `onParam` and `@Setter`.

**Comment by gradha** [comment]
Another problem of `onMethod` being ignored is that integers marked with [@IntDef](https://developer.android.com/intl/es/tools/debugging/annotations.html#enum-annotations) will be flagged as incorrect use by the IDE. Consider the following getter:

```
    @Getter(onMethod = @__({@Contact.ContactKind})) @Contact.ContactKind
    final int mContactKind;
```
When this getter is used later for comparisons it will be flagged as in the following screenshot:

<img width="392" alt="captura de pantalla 2016-05-26 a las 10 45 21" src="https://cloud.githubusercontent.com/assets/101927/15568992/1b869b06-232f-11e6-986e-0d7f40c13813.png">

The solution is to write the getter manually, which is not ideal but doable on code bases with few of these `@IntDef` tricks.

**Comment by Janmm14** [comment]
Also related: ```@NotNull``` and ```@Nullable``` on an interface getter method report that overridden getter methods are not annotated if its an ```@Getter``` method. No matter whether only the field is annotated or the getter has the onMethod filled.

**Comment by evandertino** [comment]
Its 2019, and we still have no fix.

While using JDK 13 on IntelliJ 2019.3. The IDE does not recognise deprecated Getter and Setter methods.

Lombok annotates the methods correctly, but the IDE does not recognise the `@Deprecated` annotations, set using Lombok. This happens despite the annotations being generated in the class files. Decompiling the generated classes proves this.

See the code below

<img width="627" alt="Screenshot 2019-12-04 at 18 34 17" src="https://user-images.githubusercontent.com/2353639/70156823-95740b00-16c5-11ea-88c0-c6340889936c.png">

IntelliJ generates the structure as follows

<img width="505" alt="Screenshot 2019-12-04 at 18 34 42" src="https://user-images.githubusercontent.com/2353639/70156540-25fe1b80-16c5-11ea-8828-f26ac9bc6146.png">

Note that the `setAge()` and `getAge()` methods do not get marked as deprecated in the structure window.
