### ISSUE TITLE
@Value / @EqualsAndHashCode callSuper false warning: lombok.config ignored

### ISSUE THREAD

**Issue by igorakkerman** [mplushnikov/lombok-intellij-plugin#230]
Hi, the @Value annotation is marked as warning although lombok.config is present with 'lombok.equalsAndHashCode.callSuper = skip', same with @EqualsAndHashCode.

I attached a minimal demo project.

<img width="286" alt="2016-05-04 00_04_55-lomtest - c__lokal_lab_lomtest - lomtest - _src_main_java_lomtest_lomval" src="https://cloud.githubusercontent.com/assets/10802670/14999836/158274a0-118c-11e6-9454-c42a2aba980c.png">
<img width="1269" alt="2016-05-04 00_07_39-lomtest - c__lokal_lab_lomtest - lomtest - _src_main_java_lomtest_lomval" src="https://cloud.githubusercontent.com/assets/10802670/14999892/62df5ec0-118c-11e6-9cdc-683ec6e18208.png">

Thanks,
Igor

[Lomtest.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/247846/Lomtest.zip)

**Comment by mplushnikov** [comment]
It should be fixed in the next release 0.12

**Comment by igorakkerman** [comment]
Thanks a lot for taking care!
