### ISSUE TITLE
Must use wildcard static imports with the Lombok plugin

### ISSUE THREAD

**Issue by billmasek** [mplushnikov/lombok-intellij-plugin#234]
If I enable the lombok plugin if I try to use

import static my.one;
import static my.two;
import static my.thee;

the code automatically changes to
import static my.*;

If I disable the lombok plug-in that stops happening.
It works correctly with standard imports.

**Comment by AlexejK** [comment]
I do not see how this is even possible. 

Please provide versions of your IDEA, lombok plugin and a sample project.

**Comment by AlexejK** [comment]
Due to lack of feeback as well as no proper information provided i will resolve this issue as invalid.
Please feel free to reopen and provide the requested information if you feel this is still an issue.
