### ISSUE TITLE
Lombok Plugin cannnot add "annotation processors profile" automatically for gradle project in idea

### ISSUE THREAD

**Issue by jearton** [mplushnikov/lombok-intellij-plugin#235]
Env: Lombok Plugin 0.11.15, Gradle 2.13, IDEA 15.0.5, Java8
Desc: When I create a maven project, there is a "maven default annotation processors profile" added  automatically, but gradle project can not. I have to add "gradle default annotation processors profile" manually. Apparently, the plugin is short of sth with gradle project...

**Comment by AlexejK** [comment]
For Gradle project you can simply enable default annotation processor. 

Please be aware that IDEA 2016.1 brings correct integration with Gradle via Tooling API. It also fixes a few issues affecting this plugin,  which cannot simply be solved without internal changes to the IDEA. 

I personally use Gradle projects on daily basis so this part gets automatically a lot of testing and as long as either Default Annotation processing enabled or added per module,  you should be fine. 

When it comes to maven projects,  the processor is added by IDEA and not the plugin. So if anything,  it's differences in handling on IDEA side.

**Comment by jearton** [comment]
I get it. Thanks for detailed explanation.
