### ISSUE TITLE
val doesn't work inside lambda

### ISSUE THREAD

**Issue by Dibro89** [mplushnikov/lombok-intellij-plugin#236]
`Runnable run = () -> { val str = ""; };`
Compilation error: incompatible types: java.lang.String cannot be converted to lombok.val

**Comment by AlexejK** [comment]
This is a lombok limitation, not the IDEA lombok plugin. please report to the correct project: https://github.com/rzwitserloot/lombok

They have this issue reported already though: https://github.com/rzwitserloot/lombok/issues/911
