### ISSUE TITLE
Overriding val variable is not highlighted as an error unless the code is compiled

### ISSUE THREAD

**Issue by vtsukur** [mplushnikov/lombok-intellij-plugin#238]
Consider the following code inside a method:

```
val name = "Jack";
name = "Bill";
```

This code won't compile because `val name = "Jack"` turns into `final String name = "Jack"` and overriding `final` variable is not allowed.

The issue is that there are no signs of the compilation problem while editing code: text is not underlined with a red line. Is it something that can be fixed? Otherwise, developer has a false assumption that the code does compile.

**Comment by AlexejK** [comment]
This is a limitation in versions below 2016.2 of IDEA where modifier visibility is not possible to set.
We have an upcoming version of the plugin that supports this on 2016.2 and actually provides a backport of the functionality for earlier versions of the plugin. This feature is available in the next release version of the plugin.

Basically what you are reporting is related to https://github.com/mplushnikov/lombok-intellij-plugin/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Modifier+Visibility%22 list of issues.

I will close this as its already covered by 0.12

**Comment by vtsukur** [comment]
Cool, thank you for the explanation!
