### ISSUE TITLE
Support for @UtilityClass

### ISSUE THREAD

**Issue by IceMan81** [mplushnikov/lombok-intellij-plugin#240]
The plugin does not correctly support the UtilityClass annotation. 
See attached screenshot.

The annotation makes the inner class AquaTestRuntimeFactory static and so the static method create() is valid but Intellij complains about this. 

![image](https://cloud.githubusercontent.com/assets/1093778/15755751/139750e6-28b3-11e6-94a7-b02feff5e3b7.png)

**Comment by AlexejK** [comment]
Dupe of https://github.com/mplushnikov/lombok-intellij-plugin/issues/143

**Comment by IceMan81** [comment]
@AlexejK Sorry about that, should have searched properly before opening the issue. Thanks.
