### ISSUE TITLE
 ModifierVisibility: 2016.2 EAP Changes

### ISSUE THREAD

**Issue by AlexejK** [mplushnikov/lombok-intellij-plugin#243]
It would seem that the PsiAugmentProvider API changed and the ModifierVisibility API has changed as per: https://github.com/JetBrains/intellij-community/commit/e3fe4c48711659f8fbfc2a4f651e04e2d03395de#diff-4f011625b17f07aeb872bd08014fac21

This may be partly affecting #241 and #242 (However 0.11 of the plugin does not rely on that functionality)

**Comment by mplushnikov** [comment]
Looks like Jetbrains guys broke something :( I file an [issue IDEA-157105](https://youtrack.jetbrains.com/issue/IDEA-157105)

**Comment by mplushnikov** [comment]
Peter Gromov added a fix today (https://github.com/JetBrains/intellij-community/commit/eac22bca216623d68aaeee8d52e81550714a1012)
We should check it next days, after new build will be available.

**Comment by AlexejK** [comment]
That's great! I will check this on my branch where I am updating the modifier API. 

Thanks for doing the bug report,  never got around to it.
