### ISSUE TITLE
IntelliJ does not know about clear...() methods for collections.

### ISSUE THREAD

**Issue by stefanbirkner** [mplushnikov/lombok-intellij-plugin#252]
If I add the annotation `@Singular` to a field like

    @Singular
    private final List<String> things;

then Lombok creates the methods `thing(String)`, `things(List<String>)` and `clearThings()`. IntelliJ knows the first one but it does not know about `clearThings()`. If I write code like

    builder.clearThings();

then it compiles and it is executed but the IDE marks it red and tells me that the code has an error.

Lombok version: 1.16.8

**Comment by AlexejK** [comment]
Clear method is added in 1.16.8 and current version of the plugin,  0.11 does not fully support it yet.

**Comment by stefanbirkner** [comment]
Close this a duplicate of #192 and #225.
