### ISSUE TITLE
Refactor "Default @Getter" removes annotation on JPA entity classes

### ISSUE THREAD

**Issue by golonzovsky** [mplushnikov/lombok-intellij-plugin#253]
It would be nice to keep Entity and JSR-303 annotations for lombok refactor actions to keep existing logic.  

We dont know which annotations could be easily moved from getter to field, but at least JPA and JSR-303 will help much, as lombok really shines and removes loads of boilerplate on Entities.

**Initial class:**

``` java
@Entity
@Table(name = "payment")
public class Payment {
    private String paymentId;
    @Id
    @Column(name = "payment_Id", unique = true, nullable = false, length = 64)
    public String getAdjustmentId() {
        return adjustmentId;
    }
}
```

**Current behavior:**

``` java
@Getter
@Entity
@Table(name = "payment")
public class Payment {
    private String paymentId;
}
```

**Expected behavior:**

``` java
@Getter
@Entity
@Table(name = "payment")
public class Payment {
    @Id
    @Column(name = "payment_Id", unique = true, nullable = false, length = 64)
    private String paymentId;
}
```

**Comment by mplushnikov** [comment]
Thank you for nice idea, i'll check how to accomplish it!

**Comment by mplushnikov** [comment]
In the next version of plugin (>=0.14) refactoring action for @Getter/@Setter/@Data will move all of method annotations to the field.
