### ISSUE TITLE
Properties from lombok.config does not involve on suggestion list

### ISSUE THREAD

**Issue by ValeryDubrava** [mplushnikov/lombok-intellij-plugin#254]
I've changed property lombok.log.fieldName to value "logger" and put it to lombok.config file in the root of the maven multi module project

How looks my lombok.config file
`lombok.nonNull.exceptionType = IllegalArgumentException
lombok.log.fieldName = logger
lombok.accessors.chain = true
config.stopBubbling = true`

It works good for all features - compile, syntax checking, delombok and so on, but suggestion list does not work for properties "logger". It shows "No suggestion" popup.
I've tried rebuild project, invalidate cache and put lombok config to all reasonable places: resources, modules roots and so on. It did not help me.

System details:
OS X System, 10.11.5

IntelliJ IDEA 2016.1.3
Build #IU-145.1617, built on June 3, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Lombok: 0.11.16

**Comment by AlexejK** [comment]
as a quick workaround - have you tried restarting IDEA? I know this isn't ideal but this might work.

**Comment by ValeryDubrava** [comment]
Yes, I've tried several times.

**Comment by ValeryDubrava** [comment]
I tried with new java maven application - the same result with custom logger name. Everything works good, but suggestion list is empty for logger variable.

**Comment by AlexejK** [comment]
What is your lombok dependency version? (not version of the plugin)

**Comment by mplushnikov** [comment]
I can now reproduce it and will try to fix it:)
