### ISSUE TITLE
@Getter and @Setter above the class dont work 

### ISSUE THREAD

**Issue by zakedyStyle** [mplushnikov/lombok-intellij-plugin#255]
In this code snippet compiler works OK, but marks red all getters or setters calls.

```java
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@EqualsAndHashCode
@ToString
public class UserRole {

    private int id;
    private String role;
}
```

**Comment by Janmm14** [comment]
Did you tried a restart? If its not fixed by that, try invalidate caches and restart. Report back what helped.

**Comment by AlexejK** [comment]
Please provide a version of IDEA, Lombok plugin and Lombok dependency

**Comment by zakedyStyle** [comment]
After the restart everything seems just fine, but the same trouble was with
@Bean annotation for a while. But it was also fixed after restart.
Intellij Idea 15.0.2
Latest Lombok and plugin.

2016-07-11 17:07 GMT+03:00 Alexej Kubarev <notifications@github.com>:

**Comment by AlexejK** [comment]
If the Bean annotation was failing for you - this is most likely internal IDEA issue, or it was indexing the project. I will resolve this for now, unless you have more information such as stacktraces etc.

**Comment by zakedyStyle** [comment]
No stacktraces, cos it compiles well.
Anyway, thanks.

2016-07-12 15:30 GMT+03:00 Alexej Kubarev <notifications@github.com>:
