### ISSUE TITLE
Intellij cannot see getters/setters generated by @Data on inner class

### ISSUE THREAD

**Issue by maciekdragan** [mplushnikov/lombok-intellij-plugin#256]
Hi! Issue title describes problem already :)
Steps to reproduce:

```
public class SomeClass {
...
   @Data
   public class InnerClass {
      private String field;
   }
}

SomeClass.InnerClass innerClassInstance = someClassInstance.getInnerClassInstance();
innerClassInstance.getField();     // ERROR - Intellij cannot see getter
```

**Comment by AlexejK** [comment]
Which version of IDEA, lombok and lombok plugin are you running?

**Comment by maciekdragan** [comment]
IntelliJ IDEA 2016.1.2
Build #IU-145.972, built on May 14, 2016
JRE: 1.8.0_66-b18 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Lombok version: 1.16.8

Lombok plugin version:  0.11.16

**Comment by thekalinga** [comment]
After updating to the latest version of lombok plugin, the application cannot be run, as intelliJ complains that the setters and getters are missing (tho it does not show any compilation errors)

**Comment by thekalinga** [comment]
I tried using both intellij 15 & 16, I have the same issue. This is blocker, if others too are facing this issue

**Comment by AlexejK** [comment]
Is your annotation processing enabled?

**Comment by AlexejK** [comment]
Ive just tested this with a sample project and proper project configuration -and it all works fine, as long as annotation processing is enabled.

**Comment by AlexejK** [comment]
My guess is that your project setup is wrong - please refer to readme file
