### ISSUE TITLE
val not highlighted as final by Android Studio

### ISSUE THREAD

**Issue by gradha** [mplushnikov/lombok-intellij-plugin#257]
val is `final` but this is not reflected on the source code editor:

<img width="331" alt="captura de pantalla 2016-07-11 a las 11 10 17" src="https://cloud.githubusercontent.com/assets/101927/16725584/363ffa30-4758-11e6-969b-4abd24bfcf8a.png">

Until the compilation step:

    Error:(192, 9) error: cannot assign a value to final variable something

Non-val final variables are flagged correctly by the IDE:

<img width="182" alt="captura de pantalla 2016-07-11 a las 11 10 45" src="https://cloud.githubusercontent.com/assets/101927/16725588/3e14428e-4758-11e6-9257-38ccd34ec2ca.png">

Initially this confused me and made me write `final val` everywhere.

**Comment by AlexejK** [comment]
This is because Modifier visibility support requires 2016.2 EAP and Lombok Plugin 0.12 which is not yet released.

Also, we will most likely have a backport as part of 0.12 that will support 15.x version of IDEA.
I am not 100% sure which version of IDEA that Android Studio is built on top of.

**Comment by AntekM** [comment]
This doesn't seem to be solved in Android Studio 2.2 beta6 (with plugin 0.13.16), but as I know AS is based on bit dated IDEA usually. As I understand we need to wait until they upgrade to at least 2016.2, yes?

**Comment by AlexejK** [comment]
You could attempt to enable runtime patching in Lombok plugin settings. This is a feature for IntelliJ 15.1-2016.1 to support one of the APIs of 2016.12.

However it would seem AS deviates quite a bit from source, for example with Annotation processing (even APIs don't return same values). This means I cannot guarantee if this will work for you as we are primarily targeting main intellij line. Please do report back if you choose to try this :)
