### ISSUE TITLE
Bug: When lombok.accessors.chain=true setters show void return value

### ISSUE THREAD

**Issue by mih-kopylov** [mplushnikov/lombok-intellij-plugin#262]
in lombok.config
`lombok.accessors.chain=true`

in code
`new AuthEvent().setIp( "dd" ).setIp( "some" );`
compiles well, but without IDE help after Ctrl+Space

![2016-07-24_22-35-53](https://cloud.githubusercontent.com/assets/6898003/17085992/1811ba70-51ef-11e6-991b-783137bc026e.png)

**Comment by mplushnikov** [comment]
I think it could be already fixed by changes for #254
I will double check it!

**Comment by mih-kopylov** [comment]
wow, great. Didn't find #254 first.

Thank you. Will be waiting for v0.13

**Comment by mplushnikov** [comment]
I verified it. It should be really fixed in the next build!

**Comment by mih-kopylov** [comment]
great, thank you!
