### ISSUE TITLE
Lombok dependency is missing 

### ISSUE THREAD

**Issue by samodadela** [mplushnikov/lombok-intellij-plugin#265]
After updating IntelliJ Lombok plugin to 0.12.16 I get:

10:21 AM Lombok Dependency is missing
Project "parent" does not seem to have lombok dependency added.
This plugin does not provide it and will not function correctly without.
Please make sure to add it manually and refresh your project.
Click here to see how to add it to your project.

This is a maven project with the parent pom.xml containing only maven properties and a modules section. The (child) modules do need Lombok, but the parent pom doesn't.

I added the dependency to lombok in parent pom.xml and the error went away.

Previous plugin versions did not complain about this. Do I really need to have the dependency to lombok in parent pom even if every child has it's own?

FYI: I erroneously reported this under the lombok project itself. Alexej gave some comments:
https://github.com/rzwitserloot/lombok/issues/1161

**Comment by AlexejK** [comment]
For the sake of removing need to check multiple issues for comments:

> As for the immediate issue at hand - this is not needed to be in parent in your setup, but AFAIK we have no reliable way of finding out if its just a parent container project or if it has actual source code.
>
>This feature has been added to the plugin as a lot of issues to the IntelliJ plugin kept being reported where users thought adding only plugin to IntelliJ is enough (even though our documentation clearly states Lombok itself is still needed). As it stands today, in the plugin config (Other Settings -> Lombok plugin) its possible to turn off some of the features in intellij, including version checks and run-time patching of older versions of IDEA. AFAIK missing dependency warning is a different check (prior to version) and could possibly be extracted.

As per my quoted comment above - we might want to consider extracting missing dependency check into configuration system OR making it smarter by detecting if the "parent" is actually containing any sources.

**Comment by relgames** [comment]
It also complained about missing dependency in a project which does not use lombok at all.

**Comment by AlexejK** [comment]
Also, please note that #263 tracks similar issue.

**Comment by AlexejK** [comment]
#266 Should allow you to disable the warning for the properly configured project

**Comment by AlexejK** [comment]
As #266 is merged and it fixes default settings (for some reasons "default is disabled" did not work) I will mark this as resolved.
