### ISSUE TITLE
Compile errors after moving an @Setter annotation by using IntelliJ move keyboard shortcut ⌥⇧↑

### ISSUE THREAD

**Issue by nvdh** [mplushnikov/lombok-intellij-plugin#270]
When moving an @Getter annotation before an @ToString annotation by using the move shortcut ⌥⇧↑ I get compile errors in IntelliJ (it doesn't see the getter methods any more). The error doesn't go away with rebuilding the project or recompiling. When moving the @Getter by cutting and pasting with cmd + X and cmd + V instead, there is no problem.

**Example**

> @ToString(exclude = {"a", "b", "c", "d", "e"})
> @Getter

⌥⇧↑ + save

> @Getter
> @ToString(exclude = {"a", "b", "c", "d", "e"})

_-> compile errors_

**Versions**

IntelliJ Lombok plugin 0.13.16
IntelliJ IDEA 2016.1.3
Build #IU-145.1617, built on June 3, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by stijnluyten** [comment]
I have the same issue.
IntelliJ Lombok plugin 0.11.14
IntelliJ IDEA 14.1.7

**Comment by AlexejK** [comment]
@stijnluyten Your intellij and Lombok plugin are heavily out of date. There have numerous fixes and improvements both in plugin and ide.

@nvdh what happens if you refresh the project? I have a feeling intellij is not triggering augmentation when using line moving and therefor you get this error.  Can you please try?

**Comment by nvdh** [comment]
@AlexejK I don't know what you mean exactly with refresh, but if I synchronize the project, the problem remains

**Comment by AlexejK** [comment]
Is this a Gradle or maven project?  In that case there is a refresh button for these projects in respective view

**Comment by nvdh** [comment]
It is a maven project. I tried re-importing the project too. I don't really see another option to refresh. I also tried re-building on the commandline and re-synchronizing and re-importing, but the errors remain. I also tried using make and also by rebuilding the project in IntelliJ. Is there any way I can manually trigger the augmentation?

**Comment by AlexejK** [comment]
It's triggered by intellij itself. If reimport of the project doesn't help -  something else is wrong. 

Does command line build go through?

**Comment by nvdh** [comment]
Command line build goes through without any problem.

It is re-import of the maven project, not removing the project and importing everything from scratch (right click on the project -> maven -> reimport). Just to be sure we're talking about the same here.

I'd put a breakpoint to check if the plugin action is triggered (BaseRefactorHandler?), but I didn't figure out how to start IntelliJ with the plugin code yet.

**Comment by mplushnikov** [comment]
Interesting thing, but I can reproduce it.

**Comment by mplushnikov** [comment]
It can have the same root cause as #210

**Comment by mplushnikov** [comment]
The next version of plugin 0.16 should fix this problem.
