### ISSUE TITLE
"Enable lombok version warning" doesn't work.

### ISSUE THREAD

**Issue by OrangeDog** [mplushnikov/lombok-intellij-plugin#272]
IDEA 2016.2, Plugin 0.12.16

I have this checkbox unchecked in Settings -> Other Settings -> Lombok plugin.
However, I still get a warning for every module on startup.

> Lombok Dependency is possible outdated
> Project "X" and Module "y" seem to have outdated lombok dependency added.
> Configured version "1.16.8", but there is at least version "1.16.10" already released
> Maybe you want to update?

**Comment by AlexejK** [comment]
Plugin 0.12 had an issue with this setting, please try 0.13.
