### ISSUE TITLE
Access of public inner enum class

### ISSUE THREAD

**Issue by lxxllxxl** [mplushnikov/lombok-intellij-plugin#279]
When an enum class is defined as public inner enum and try to access its types in another file, editor will report that type can't be accessed. However, that enum is accessible, and build will pass.
This happens after I install lombok plugin. And it will disappear after disable it.

**Comment by AlexejK** [comment]
Can you provide the following :

1.  Test project
2. IntelliJ version 
3. Lombok plugin version 
4. Lombok dependency version
