### ISSUE TITLE
Renaming a field with a @Getter annotation prompts to rename the getter.

### ISSUE THREAD

**Issue by ChrisKitching** [mplushnikov/lombok-intellij-plugin#28]
Consider a field such as:

@Getter private final JCTree decoratedTree;

Place the cursor on the field and push SHIFT+F6 to use IDEA's renaming function for this field.
IDEA will prompt: "A getter exists for decoratedTree - rename it as well?"

Presumably IDEA is detecting the lombok-generated getter that your plugin tells it to pretend exists. 
The ideal behaviour in this case would be that your plugin would automatically tell IDEA "Yes" to this prompt - this would automagically update all calls to the Lombok-generated getter, which would be decidedly cool. Still, manually clicking a button isn't too hard as a workaround.

**Comment by mplushnikov** [comment]
Closed as too old
