### ISSUE TITLE
Dependency outdated warning

### ISSUE THREAD

**Issue by kusid** [mplushnikov/lombok-intellij-plugin#282]
IntelliJ 15.0.1 Ultimate.

'Lombok dependency is possible outdated'- this pops up even when 'Enable lombok version warning' is unchecked. Frankly, I would want the plugin to be completely silent for all projects and not notify me for anything. A global 'turn off notifications' setting would be really helpful.

**Comment by mplushnikov** [comment]
Is not reproducible anymore...
