### ISSUE TITLE
intellij crashes on start because of plugin

### ISSUE THREAD

**Issue by kilonet** [mplushnikov/lombok-intellij-plugin#285]
plugin version 0.13.14
Intellij version 14.0.5
Error message on startup: 

`Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: de.plushnikov.intellij.plugin.LombokPluginUpdateProjectComponentde.plushnikov.intellij.plugin.LombokPluginProjectValidatorComponent PluginClassLoader[Lombook Plugin, 0.13.14] [Plugin: Lombook Plugin]`

full log: [idea.log.txt](https://github.com/mplushnikov/lombok-intellij-plugin/files/442011/idea.log.txt)

I've had no problems running with older plugin version. Is it possible to get fixed? Thanks

**Comment by AlexejK** [comment]
I believe you need to upgrade to at least 14.1.x IDEA. 
Preferably newer versions,  like 15.x or even 2016.2

**Comment by AlexejK** [comment]
If that is not an option you can manually get older version of the plugin and install it from disk.

**Comment by kilonet** [comment]
@AlexejK thanks, will try to install older version of plugin for now

**Comment by kcrosswind** [comment]
i have try 0.11/0.12/0.13 is not ok, my Intellij version 14.0.2, which lombok version can i use? thanks

**Comment by kilonet** [comment]
@kcrosswind plugin version 0.11.14 works for me with intellij 14.0.5
