### ISSUE TITLE
@data does not work

### ISSUE THREAD

**Issue by zzzzfelix** [mplushnikov/lombok-intellij-plugin#289]
I used the lombok plugin 0.13.16 with Intellij 2016.2.4 paid version.  I enabled per instruction.  It works for @Getter @Setter, but it does not work with @Data.  It flag with red color when i tried to access the object.

Please help!

**Comment by jorgheymans** [comment]
what i have seen happening is that sometimes annotations do not take effect the first time, and you need to remove / readd them to get everything working. this is annoying when refactoring.

it seems to happen more when pasting several annotations on a class in one go.

**Comment by mplushnikov** [comment]
Fixed an issue that could cause this behavior #210
Please verify after next plugin version 0.16 will be available
