### ISSUE TITLE
Getter and FieldDefaults with parameter AccessLevel in Enum shows "cannot access"

### ISSUE THREAD

**Issue by Polostor** [mplushnikov/lombok-intellij-plugin#290]
Enum class with annotations Getter and FieldDefaults other then PUBLIC shows Enum values are not accessible from other class although Idea knows about them.

Example: 

```
@Getter
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public enum EnumClass { ENUM1, ENUM2 }
```

In another file 

```
public class OtherClass { 
    public void method() { 
        EnumClass.ENUM1.name; 
    }
 }
```

**Comment by Janmm14** [comment]
Does it work compiled?

**Comment by Polostor** [comment]
Yes, it works after compilation. Even without compilation Idea is able to work with it, it just shows error "Cannot access '<enum>' in '<class>'." which is false and in version 0.11.16 it was working properly..

**Comment by ducquoc** [comment]
I met the same issue, but I used @PackagePrivate  before each enum declaration, and it works as a work-around for the false alarm.

Hope this helps,
