### ISSUE TITLE
Refactor Rename misses @Builder methods

### ISSUE THREAD

**Issue by swilliger** [mplushnikov/lombok-intellij-plugin#295]
Hi,

when i use Refactor->Rename on a member in a lombok class which is annotated with @Value and @Builder, Idea refactores all getters, but misses all builder methods.

It should refactor all builder methods as well.

best regards
Sven

**Comment by eekboom** [comment]
Any progress here?

I created an issue for that problem in IDEA's bug tracker, too. It got resolved with some technical remarks about how this could be implemented in the lombok plugin: https://youtrack.jetbrains.com/issue/IDEA-179790

**Comment by mplushnikov** [comment]
Thank you for your attention, I will look through it.

**Comment by mplushnikov** [comment]
Similar or duplicate issue: #119
