### ISSUE TITLE
Lombok plugin dont work on Android Studio 2.2.2

### ISSUE THREAD

**Issue by Nissaum** [mplushnikov/lombok-intellij-plugin#301]
Hello, i updated the Android Studio for version 2.2.2 and the lombok plugin not working, there is something to solve it?

Thanks for any feedback.

**Comment by Nissaum** [comment]
Problem resolved:
I change the version:
compile "org.projectlombok:lombok:1.16.10"
to:
compile "org.projectlombok:lombok:1.12.6"

**Comment by mplushnikov** [comment]
I think you should change your gradle configuration, add this two lines:
```
provided "org.projectlombok:lombok:1.16.10"
annotationProcessor "org.projectlombok:lombok:1.16.10"
```

From https://github.com/rzwitserloot/lombok/issues/1242

**Comment by Nissaum** [comment]
thanks!!
