### ISSUE TITLE
Change linked text in Lombok Requires Annotation Processing

### ISSUE THREAD

**Issue by rillig-nm** [mplushnikov/lombok-intellij-plugin#302]
The "Lombok Requires Annotation Processing" notification says:

> Annotation processing seems to be disabled for the project "bo-client". For plugin to function correctly, please enable it under "Settings > Build > Compiler > Annotation Processors"
>
> Click on this notification to go to Settings now.

The second paragraph is a link to the settings. To save space, the text "Settings > Build > Compiler > Annotation Processors" should be the link. This makes the second paragraph superfluous.

While here, you could fix "For plugin" to "For the plugin".

**Comment by mplushnikov** [comment]
Thank you for the suggestion! It should be available in the next release (>=0.14).
