### ISSUE TITLE
Extended Builder class requires explicit default constructor definition

### ISSUE THREAD

**Issue by fredo994** [mplushnikov/lombok-intellij-plugin#303]
I have a class `KeywordDefinition` that is annotated with `@Builder` annotation, and class extending 
`KeywordDefinitionBuilder`. Intellij reports an error if extended class does not have an explicit constructor 
with explicit super call even if constructor and super constructor are default constructors. And when I explicitly add those constructors Intellij gives hint that `super()` call is not needed. 

Eg:
![screenshot from 2016-11-08 11-16-00](https://cloud.githubusercontent.com/assets/7530821/20095300/45bf9b22-a5a5-11e6-8e44-ad64fe5e66a8.png)

![screenshot from 2016-11-08 11-16-24](https://cloud.githubusercontent.com/assets/7530821/20095302/478840bc-a5a5-11e6-9a17-b9f80bf2557f.png)

![screenshot from 2016-11-08 11-16-47](https://cloud.githubusercontent.com/assets/7530821/20095375/8be518ca-a5a5-11e6-8c55-2b2a1764d58c.png)

This type of error does not appear in netbeans. I know that this is bad design but this is legacy code written by an intern and I do not have time to change implementation (except adding constructors).

**Comment by mplushnikov** [comment]
It looks like a same cause as in issue #145 and should be fixed by PR #407
