### ISSUE TITLE
@Getter and @Setter support broken

### ISSUE THREAD

**Issue by beedaan** [mplushnikov/lombok-intellij-plugin#315]
I'm using the latest snapshot build (0.14.16)

The Lombok plugin does not recognize getters and setters generated by Lombok.  I can compile the code fine.  It's just my editor that complains about the issue.  I also feel like I could be completely overlooking a setting.

![screen shot 2016-12-01 at 8 15 53 am](https://cloud.githubusercontent.com/assets/884240/20801930/403d1a2e-b79f-11e6-876e-caaf59fd001c.png)

**Comment by mplushnikov** [comment]
Thank you very much for trying it out! Getter/Setter should work, can you verify it, by restarting Intellij?

**Comment by beedaan** [comment]
That seemed to have done the trick.  Just for more information for anyone else that may find themselves in this position, I installed a snapshot version of the plugin after using the plugin from the IntelliJ plugin repository.  This time, I made sure to uninstall the old plugin, restart, install the snapshot version, restart, and now everything is working as expected.
