### ISSUE TITLE
Error signalled with IntelliJ 2016.3

### ISSUE THREAD

**Issue by bgoldowsky** [mplushnikov/lombok-intellij-plugin#321]
Using Lombok plugin 0.13.16 and IntelliJ IDEA 2016.3  (Build #IU-163.7743.44, built on November 17, 2016), the IDE is reporting this error when opening a new project that includes Lombok:

`Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
`

**Comment by AlexejK** [comment]
Duplicates #308
Please try a manual install of the 0.14 pre-release from the releases page.
