### ISSUE TITLE
IntelliJ IDEA 2017.1 EAP: Plugin cannot be installed

### ISSUE THREAD

**Issue by juergenzimmermann** [mplushnikov/lombok-intellij-plugin#328]
When I try to install the Lombok plugin I get the error message "Plugin 'Lombok Plugin' is incompatible with this installation".

**Comment by AlexejK** [comment]
As 20171 is still EAP, compatibility is not yet guaranteed.

**Comment by mplushnikov** [comment]
Just tested current lombok plugin 0.14.16 with IntelliJ IDEA 2017.1 EAP (build 171.2455.10), released on Jan 19, 2017 without any problems.
