### ISSUE TITLE
@Builder annotation with partial implementation shows errors

### ISSUE THREAD

**Issue by toadzky** [mplushnikov/lombok-intellij-plugin#33]
If a class has @Builder and you actually create a static inner class with same name, Lombok will still generate everything else. you can use this to provide default collections or values in your builder, or hide a particular field's setter. 

Intellij highlights the @Builder annotation as problematic and won't recognize the other parts that the annotation does (static method). The error message is 

    "Not generated 'Builder' class. A class with the same name already  exists. This feature is not implemented and is not planned."

Well, it is implemented, so it would be nice if it stopped showing errors.

**Comment by asaf-romano** [comment]
Hi Michail,

Is there some workaround for hiding such stub classes from the plugin? We're using this feature from lombok for integrating with Jackson.

**Comment by twillouer** [comment]
@asaf-romano I don't know if it can help you, but I discover the projet https://github.com/xebia/jackson-lombok and perhaps he can help you

**Comment by mplushnikov** [comment]
Hello @asaf-romano,
I'm working on better support for @Builder and will add some enhancement for partially defined Builder-classes in the next version of plugin.

**Comment by asaf-romano** [comment]
Thanks! :)

BTW, a working-most-of-the-time workaround I found for 0.9 is to extend builder class rather than providing a partial implementation, and point JsonDeserialize to that class.
