### ISSUE TITLE
val/var color

### ISSUE THREAD

**Issue by amirabiri-odoro** [mplushnikov/lombok-intellij-plugin#340]
Is it possible to change the syntax highlighting of `val` & `var` to treat them as keywords?

This is what they effectively are, and this is how they would be colored in other languages (C#, Scala, Kotlin).

**Comment by AlexejK** [comment]
I think this is actually boiling down to how Lombok itself is declaring it as.
you might want to raise this with https://github.com/rzwitserloot/lombok as this plugin is only handling IntelliJ integration.

**Comment by fvsnippets** [comment]
https://plugins.jetbrains.com/plugin/24327-val-highlight

Disclaimer: I am the author. There is no solution so far, so I got to work.
