### ISSUE TITLE
Accessors: Error highlighting on classes with no errors

### ISSUE THREAD

**Issue by delverdev** [mplushnikov/lombok-intellij-plugin#341]
With fluent and chain accessors, some of my classes have error highlights (in the project sidebar). However, they dissapear where I open the classes one by one. They appear and dissapear randomly with no reason (even while AFK). It's too annoying and makes a developing impossible at all. I have error highlights only in project sidebar and tabs (there is no highlights in scrollbar when I open a class).
_2016.3.2_

**Comment by mplushnikov** [comment]
Looks working well with current plugin version. Will close it for now, feel free to reopen it with new example!
