### ISSUE TITLE
@EqualsAndHashCode should treat explicit "of = {}" differently

### ISSUE THREAD

**Issue by seanf** [mplushnikov/lombok-intellij-plugin#342]
Lombok ordinarily treats an explicit value for "of = {}" as meaning "don't include any fields in the equals/hashCode comparison", but the plugin apparently treats it as "include all fields in the comparison" when performing Delombok. Apart from the problem that Delombok via plugin may give inaccurate results, this can lead to StackOverflowError for classes which have two-way references when equals or hashCode is called.

Ref: https://github.com/rzwitserloot/lombok/blob/v1.16.12/src/core/lombok/javac/handlers/HandleEqualsAndHashCode.java#L83

**Comment by seanf** [comment]
Lombok has a few other annotations which may be similar to this one: https://github.com/rzwitserloot/lombok/search?utf8=%E2%9C%93&q=%22annotation.isExplicit%22&type=Code

See also https://youtrack.jetbrains.com/issue/IDEA-166856 for a problem with the IntelliJ inspection "redundant default parameter value assignment" as it affects annotations with implicit/explicit values. Solving the problem with the inspection may require changes in the plugin (since JetBrains probably won't want to put Lombok-specific exceptions into their code).

**Comment by mplushnikov** [comment]
Thank you @seanf!
Amazing issue, i didn't thought somebody will use empty explicit "of" to exclude all fields from EqualsAndHashCode or ToString instead of just removing the annotation itself.

**Comment by seanf** [comment]
Thanks!
