### ISSUE TITLE
Problem Picking up Lombok Changes

### ISSUE THREAD

**Issue by gaoagong** [mplushnikov/lombok-intellij-plugin#343]
Sometimes when I am using Lombok annotations, Intellij doesn't pick them up and they show things in red. A quick fix for this is to comment out the annotations and then uncomment them out. It would be nice if this was not required.

**Comment by AlexejK** [comment]
Can you please provide versions of IDEA, lombok plugin and lombok dependency you are using.

Is there a reproducible use-case or an exact scenario you can provide?

**Comment by mplushnikov** [comment]
Fixed an issue that could cause this behavior #210
Please verify after next plugin version 0.16 will be available
