### ISSUE TITLE
fieldDefaults in lombok.config and @Data Intellij compiler support

### ISSUE THREAD

**Issue by dessens** [mplushnikov/lombok-intellij-plugin#353]
Currently my lombok.config looks like this:
```
lombok.fieldDefaults.defaultPrivate=true
lombok.fieldDefaults.defaultFinal=true
```

I have this class:
```
@Data
public class Foo {
    int one;
    int two;
}
```

Trying to instantiate this causes an error in intellij, but not when compiling with gradle. It complains about the constructor for required arguments not existing.

```
val foo = new Foo(1, 2);
```

If I change the class to this, intellij no longer complains:

```
@Data
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
public class Foo {
    int one;
    int two;
}
```

I am using IntelliJ idea version 2016.3.4 and lombok plugin version 0.14.16

**Comment by mld-ger** [comment]
We do have the issue in our projects as well. I'm using IntelliJ 2017.1.4 and plugin version 0.14.16.

**Comment by mplushnikov** [comment]
> lombok.fieldDefaults.defaultPrivate=true
> lombok.fieldDefaults.defaultFinal=true
Unfortunately  plugin doesn't support these two config options at the moment...

**Comment by Vyacheslav-Lapin** [comment]
+1
