### ISSUE TITLE
Add manual code generation for getter/setter

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [mplushnikov/lombok-intellij-plugin#355]
Sometimes it is needed to generate getter/setter in lombock styling. At first glance lombock is invented for hiding generated code. But from other side, what if I need to create lombock getter/setter with some logic? For example setter receives Double but set Integer value. It can be usefull to generate code by Idea and then modify it.

**Comment by AlexejK** [comment]
Hi and thank you for raising this question.

To clear this question and clarify the way it works I need to point out a few things:
1. This plugin only provides support for Lombok in IDEA - it doesn't correspond to Lombok itself.
2. You might want to check out [lombok docs](https://projectlombok.org/features/index.html) as well as their Github repo: https://github.com/rzwitserloot/lombok
3. Lombok project is targeted to remove boilerplate code, such as "dumb getters/setters" - what you are describing is "smarter" variants. For this case, it's always recommended to write the logic yourself for methods that require it.
4. The way Lombok works is that it acts as an annotation processor, something that is triggered as part of compilation step - what you are referring to is more of a domain of "code generators".
5. It's possible to have IDEA to auto-generate getter/setter code for you as part of the standard functionality of IDEA - and you don't need to do anything with Lombok for those parts.
