### ISSUE TITLE
Explicit type can be diamond inspection is overloaded with the same id

### ISSUE THREAD

**Issue by akozlova** [mplushnikov/lombok-intellij-plugin#359]
I moved the inspection to another group and spend half an hour to find out why the group path was not changed, 

LombokExplicitTypeCanBeDiamondInspection should be removed and the common inspection should support cases with var/val, etc.

**Comment by mplushnikov** [comment]
Hello @akozlova,
removing LombokExplicitTypeCanBeDiamondInspection would be great, but how can we change the common inspection to add support for lombok's var/val types?

**Comment by akozlova** [comment]
I've disabled the inspection in case of augmented types, this lead to no warning in the following case:
```
val l = new ArrayList<Object>();
```
but to me it looks ok as Object will be inferred here more or less by incident, as left side is inferred from right side and right side should be inferred from left one. I guess you may just remove the inspection. Thanks

**Comment by mplushnikov** [comment]
Thank you @akozlova ! Can you tell me a build number of IntelliJ containing your fix?

**Comment by akozlova** [comment]
173.2099
