### ISSUE TITLE
No usages found for fields if using Builder annotation

### ISSUE THREAD

**Issue by klimmik** [mplushnikov/lombok-intellij-plugin#362]
![20170228-lombok-builder-no-usages](https://cloud.githubusercontent.com/assets/13970931/23414697/f0ca0fa2-fded-11e6-8763-ee9f2d4702e8.png)

**Comment by LuiVampa** [comment]
I'm too!

**Comment by CoolHacker999** [comment]
I'd like this to be fixed as soon as possible!

**Comment by mplushnikov** [comment]
duplicate of #144
