### ISSUE TITLE
[Feature request]IDEA .var suffix feature replacement

### ISSUE THREAD

**Issue by caoli5288** [mplushnikov/lombok-intellij-plugin#365]
IDEA supported this feature. type `foo.getBar().var` and got `Bar bar = foo.getBar()`. Replace it with`var bar = foo.getBar()` is much better.
Lombok also supported `val`. `foo.getBar().val` and got `val bar = foo.getBar()` is also good.

**Comment by mplushnikov** [comment]
Just added new postfix templates for:
'.val' ->producing `lombok.val foo = ...` 
and 
'.varl' -> producing `lombok.experimental.var foo = ...`

Should be available in next plagin release (0.16)
