### ISSUE TITLE
Write a contributing guide

### ISSUE THREAD

**Issue by linjer** [mplushnikov/lombok-intellij-plugin#374]
I was interested in trying to contribute to the project. I've cloned master and tried `./gradlew assemble` which fails. I also tried directly importing into IntelliJ 2017.1 and building there, but that also fails.

It would be helpful for people interested in contributing to have a guide for how to setup their environment and import the code for development.

**Comment by mplushnikov** [comment]
Sorry for delay, the project was in broken state last months, but is fixed and buildable now. (master branch)
It's based on gradle-intellij-plugin, so you can find some informations how to build/start in the description here: https://github.com/JetBrains/gradle-intellij-plugin
After checkout from master you only need to import it in Intellij from gradle file.
