### ISSUE TITLE
Multiple "concurrent" accessor-method invocations when debugging

### ISSUE THREAD

**Issue by benjamin84** [mplushnikov/lombok-intellij-plugin#376]
Consider a class like this. The accessor Method for tstamp is explicitly implemented because it generates a value upon first read access:

```
@Data
public class Lomboked
{
   private long tstamp = -1L;

   public long getTstamp ()
   {
      if (tstamp == -1L)
      {
         System.out.println ("Current tstamp value: " + tstamp);
         tstamp = System.currentTimeMillis ();
      }
      return tstamp;
   }

   public static void main (String[] args)
   {
      Lomboked x = new Lomboked ();
      System.out.println (x.getTstamp ());
   }
}
```

When I debug the method "getTstamp()" it seems that it is actually invoked twice, because the debugger seems to invoke that method just in time the breakpoint hits. In this screenshot you can see the value of `tstamp` which is already filled before the assignment happens. Also look at the log messages in the console.

![image](https://cloud.githubusercontent.com/assets/574942/24744832/a30aba72-1ab3-11e7-982e-f452a541b6c4.png)

Without the `@Data` annotation the debugger works as expected. I assume that the lombok plugin for IntelliJ tells the IntelliJ debugger to use the get-accessor methods for reading the values for the "variables" tab which shows the contents of the objects in the current scope.

I tried to add `synchronized` to the method signature, but that didn't help either because the debugger invokes the method in the same thread.

**Comment by mplushnikov** [comment]
Hello benjamin84,
I think you see correct behaviour.
`@Data` generates not only setter/getter, but also `toString()` operation.
By default lombok will generate `toString()` using getter-method access. And IntelliJ-Debugger will show your varaibles and call `toString()` on each object. So the first invocation comes from `toString()` method and not from your call to the getter method.

If you add `@ToString(doNotUseGetters = true)` to your example, and starts debugger again, you will see only one invocation.
