### ISSUE TITLE
Intellij IDEA 2017.1.1 cannot resolve log field of @Slf4j annotation

### ISSUE THREAD

**Issue by matveym** [mplushnikov/lombok-intellij-plugin#377]
All log field usages are marked in red. Compilation works - seems the issue is editor-only.
Lombok plugin version: 0.14.16.
Worked for IDEA 2016.3 and 2017.1.
Reinstalling Lombok plugin and invalidating caches did not help.

**Comment by matveym** [comment]
Log file:
[idea.log.txt](https://github.com/mplushnikov/lombok-intellij-plugin/files/921811/idea.log.txt)

**Comment by linjer** [comment]
Running IntelliJ IDEA 2017.1.1 on my end and `log.` statements work fine for me. Do you have any other annotation processors or any other related env/project elements that might be relevant?

**Comment by matveym** [comment]
@linjer which platform do you use? I have the issue on Windows, but strangely not on Linux. Linux IDEA version is 2017.1.2 (unavailable on Windows yet)

**Comment by linjer** [comment]
@matveym I use macOS and RHEL. Works on both using 2017.1.1. I haven't tested 2017.1.2 RC or newer.

**Comment by matveym** [comment]
Updated to IDEA 2017.1.2 on Windows - did not help.

**Comment by AlexejK** [comment]
Do you have a sample projects you can provide where this happens? Preferably including the `.idea` folder.
I'm using latest versions of IDEA all the time and this function works as expected.

**Comment by matveym** [comment]
While trying to make a sample project I found the cause of the issue. Somehow IntelliJ IDEA 2017 added root pom.xml to "Settings -> Maven -> Ignored Files" (not just for me, but for other team mates as well). After fixing that everything works fine. Sorry for blaming lombok and thanks for your work!

**Comment by AlexejK** [comment]
Glad to hear it was solved 👍

**Comment by AntonyGlim** [comment]
In my case, the problem was the absence of a specific logger. It worked when I added the dependency:
```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.30</version>
        </dependency>
```
for example.
