### ISSUE TITLE
Not supported @XXX(onMethod_, onParam_, onConstructor_) for JDK8

### ISSUE THREAD

**Issue by Wo0nder** [mplushnikov/lombok-intellij-plugin#382]
Subj. 
![9690772ae5c34c07824369d835cdb7ef 1](https://cloud.githubusercontent.com/assets/2150895/25256345/c5abc0b8-2638-11e7-9f93-c45d7328b61b.png)
It compiles and works. But IDEA shows an error.

**Comment by zanydruid** [comment]
+1

**Comment by z0mb1ek** [comment]
any news?

**Comment by amoghtolay** [comment]
+1
This is frustrating as IDEA complains about each and every file in the project, making it difficult to find actual issues.

**Comment by marcelothebuilder** [comment]
+1

**Comment by nehaagarwald** [comment]
+1

**Comment by Janmm14** [comment]
Why not use @...(onMethod = @__({...}))

**Comment by srouquette** [comment]
because your syntax is for jdk7. The syntax for jdk8 is the one described in the bug. You can check that in the code of the @Getter interface.

**Comment by devcken** [comment]
+1

**Comment by piclemx** [comment]
any news on that one?

**Comment by soberich** [comment]
@mplushnikov
Could you maybe guide somehow how to implement this so that I could do and then make a pr?

**Comment by corradom** [comment]
+1

**Comment by danieltaub96** [comment]
+1

**Comment by agrounds** [comment]
+1

**Comment by Abhiseshan** [comment]
+1

**Comment by mix74rus** [comment]
+1

**Comment by nileblue** [comment]
Any update on this? Got the same issue with..
- Intellij v.2018.1
- Lombok plugin v.0.17-2018.1

**Comment by mplushnikov** [comment]
This should be fixed in the next release 0.19

**Comment by devcken** [comment]
Good news, guys!
