### ISSUE TITLE
The @Setter makes IDEA constant conditions & Exceptions wrong

### ISSUE THREAD

**Issue by alswl** [mplushnikov/lombok-intellij-plugin#385]
### Short description

IDEA use "constant conditions & Exceptions` give user warning message.
If a POJO use `@Setter` to a field, IDEA will treat this field as set already.
Then it will warning that `if (this.field == null)` is always true.

### Expected behavior

IDEA should not warning `if (this.field == null)` is always true.

### Version information

 * **IDEA Version:** 2017.1.2
 * **JDK Version:** jdk1.8.0_131
 * **OS Type & Version:** macOS 10.12.4 (16E195)
 * **Lombok Plugin Version:** Version: 0.14.16
 * **Lombok Dependency Version:** _What version of lombok.jar are you using?_

### Steps to reproduce

Example code:

 1. open the sample project
 2. a warning will display at `this.field == null`

### Sample project

[alswl/sample-for-lombok-issue](https://github.com/alswl/sample-for-lombok-issue)

 - [x] Sample project provided
 - [x] I am able to reproduce this error on the sample project by following the steps described above

### Additional information

![lombok](https://cloud.githubusercontent.com/assets/227562/25839112/e888d8d4-34c8-11e7-9242-a1e239d268cc.png)

### Stacktrace

none

**Comment by mplushnikov** [comment]
Looks like be fixed already in Intellij 2020
