### ISSUE TITLE
lombok plugin submodule

### ISSUE THREAD

**Issue by iody** [mplushnikov/lombok-intellij-plugin#387]
hi,

Anyone experiencing this in intellij. lombok is not working when inside submodule when running unit test in main project.

java cannot find symbol on setter getter etc...

intellij can detect the annotation and references but when building the submodule it can't find it.

**Comment by iody** [comment]
i remove the dependon submodule in project structure in main it works

**Comment by Lemmmy** [comment]
@iody Can you explain specifically what you did to fix this? I am unable to get Lombok working in submodules, but it works fine for the root project. This is also using the `gradle-lombok` plugin. The projects compile fine, but getters etc appear in red in IntelliJ.
