### ISSUE TITLE
The plug-in requires configuration of the project even if the project does not use Lombok

### ISSUE THREAD

**Issue by BorzdeG** [mplushnikov/lombok-intellij-plugin#390]
### Short description
![](https://habrastorage.org/web/dbd/252/a3d/dbd252a3d19c40bb9dda3ef7318b4dc7.png)

### Version information

IntelliJ IDEA 2017.2 EAP
Build #IU-172.2656.10, built on May 30, 2017
JRE: 1.8.0_152-release-867-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

Lombok Plugin Version:0.14.16

**Comment by AleksanderGrzybowski** [comment]
I have the same issue, every time I open a project that does not use Lombok, this error is displayed - maybe the plugin could check if Lombok is actually used in project before this? This is kinda annoying, would really appreciate a fix or at least some workaround.

![image](https://user-images.githubusercontent.com/9342028/30197745-05eb4668-946a-11e7-8004-75e4aa6abbb2.png)

**Comment by ettavolt** [comment]
One can manually disable the plugin per project (that's the first option on its settings screen).
Still a problem if annotation processing is enabled for a module, but plugin wants it to be enabled for entire project.

**Comment by asarkar** [comment]
I'm working on a Haskell project, and the plugin keeps popping up asking me to enable annotation processing. It should only warn the user if the project is detected to use Lombok. The current behavior is simply stupid.

**Comment by mplushnikov** [comment]
Closed as already fixed in bb56e2dfb6538307ed58af3fedf94144927aaab3
