### ISSUE TITLE
@RequiredArgsConstructor with JDK8

### ISSUE THREAD

**Issue by z0mb1ek** [mplushnikov/lombok-intellij-plugin#392]
Hi. why I can write `@RequiredArgsConstructor(onConstructor_={@Autowired})` like requare in docs for jdk8? Its work but IDEA cannot resolve it. thx

**Comment by echoyinke** [comment]
so do i

**Comment by mplushnikov** [comment]
It's a same issue as #382, so I'll close it here as duplicate.
