### ISSUE TITLE
Feature request: SneakyThrows Quick Fix

### ISSUE THREAD

**Issue by depsypher** [mplushnikov/lombok-intellij-plugin#394]
### Short description
Would love there to be a quick fix that adds an `@SneakyThrows` annotation to a method when code in there throws a checked Exception.

### Expected behavior
Alt-Enter on problem code that throws an exception should have an `Add @SneakyThrows` menu item that adds the annotation to fix the problem.

**Comment by mplushnikov** [comment]
Should be available in the next version of plugin (0.28)
