### ISSUE TITLE
Reopening #188

### ISSUE THREAD

**Issue by prashantverma999** [mplushnikov/lombok-intellij-plugin#395]
### Short description
_Provide a short description of the issue here. Do not include stacktraces in this sectrion_

Reopening #188 since the issue got resolved without the bug being fixed. When I use Lombok's UtilityClass annotation, all members are automatically static. However, although the compilation works perfectly, IntelliJ complains every time I invoke any method of that class:

`non-static method X cannot be referenced from a static context`

When I redundantly add the static modifier myself, the errors disappear. Note that this does not affect functionality. The code still executes as expected. The developer experience is affected.

### Expected behavior
_Is there a specific expected behavior?_

Yes. Intellij should not complain since UtilityClass annotation makes the method static.

### Version information

 * **IDEA Version:** _Please provide full IntelliJ IDEA Version - available from About view_
Idea 15.0.3 Build #IU-143.1821 built on January 19, 2016
 * **JDK Version:** _What is your JDK version, including update level?_
1.8.0_102
 * **OS Type & Version:** _Are you on Mac/Windows/Linux? Provide as much information as possible about versions_
Linux
 * **Lombok Plugin Version:** _What is the version of the plugin installed?`_
0.13.15
 * **Lombok Dependency Version:** _What version of lombok.jar are you using?_
1.16

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Use @UtilityClass annotation on a class with at least one method. Don't declare the method explicitly static
2. Access the method in a static manner from somewhere else.

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

STACKTRACE HERE (inside code markup)

```

**Comment by mplushnikov** [comment]
Hello prashantverma999,
are you still using IntelliJ 15? Please verify you have activated "Enable IntelliJ runtime patching" in lombok plugin configuration panel.
![image](https://user-images.githubusercontent.com/1204509/30487829-e20f6e1a-9a34-11e7-9d1e-859522599067.png)

But the best option is to update to new version of IntelliJ (at least 2016.2), bacause it contains full support for @UtilityClass/@Value and similar "visibility"-changing features.

**Comment by prashantverma999** [comment]
Thanks for the response @mplushnikov. I have upgraded my Intellij to a newer version as per your comment and I don't have this issue with the newer version.
