### ISSUE TITLE
Getter/Setters randomly failing in 2017.1.4

### ISSUE THREAD

**Issue by springframeworkguru** [mplushnikov/lombok-intellij-plugin#397]
### Short description
Getters and setters are randomly failing - on some Project Lombock classes. Works fine for awhile, then IntelliJ starts to think getters / setters are missing. Project rebuilds fine, but IntelliJ requires a re-start to clear up.

### Expected behavior
_Is there a specific expected behavior? 

Should not need to keep re-starting. 

### Version information

 * **IDEA Version: 2017.1.4
 * **JDK Version: 1.8.0_121
 * **OS Type & Version: OSX 10.12.5
 * **Lombok Plugin Version: 0.14.16
 * **Lombok Dependency Version: 1.16.16

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

Random - works fine, then stops working. No errors. Seems to be happening about every 2 hrs of coding.

**Comment by bn3t** [comment]
I have the same behavior.

**Comment by AlexejK** [comment]
Any sample project including *.iml file would be helpful to inspect the project setup.
We have not yet experienced this in the setups we run at work but given many differnt knobs - we need a project sample that does this (also preferably a list of other plugins installed & enabled)

**Comment by springframeworkguru** [comment]
I've upgraded to the latest IntelliJ release and have not seen this for a bit. Maybe accidentally fixed???

**Comment by AlexejK** [comment]
Not sure. It might have to do with some re-indexing and similar. Please get back to me if you see it and please try to isolate it to a smallest possible project so we can reproduce it.

**Comment by mplushnikov** [comment]
I'll close it for now...
