### ISSUE TITLE
lombok无法再jrebel下正常工作

### ISSUE THREAD

**Issue by jaune162** [mplushnikov/lombok-intellij-plugin#401]
### Short description
lombok无法再jrebel下正常工作。当我编译代码时，无法将带有lombok注解的类热部署到jrebel中。在调用新增属性时会出现setter或getter找不到的问题。

### Expected behavior
可以在jrebel下正常使用。

### Version information

 * **IDEA Version:** 2017.2
 * **JDK Version:** 1.8
 * **OS Type & Version:** Windows10
 * **Lombok Plugin Version:** 0.14.16
 * **Lombok Dependency Version:** 1.16.16

### Steps to reproduce
 1. 创建一个springboot项目，并引入lombok
 2. 创建一个Bean并添加`@Data`注解。添加若干属性。
 3. 创建一个Controller，并使用setter向Bean中添加属性值
 4. 在jrebel模式下启动springboot项目
 5. 向Bean中添加属性，并修改Controller。
 6. `Build Project`
 7. 调用Controller

**Comment by AlexejK** [comment]
Please translate it all in english and re-open the issue.
