### ISSUE TITLE
Failed to download: 403 Forbidden

### ISSUE THREAD

**Issue by wikier** [mplushnikov/lombok-intellij-plugin#405]
### Short description
Browsing the plugin repository, I got to the plugin. But the install button raises an error: 

```
Plugin Lombok Plugin was not installed: 
Cannot download 'http://download.plugins.jetbrains.com/6317/31784/lombok-plugin-0.14.15.zip?updateId=31784&pluginId=6317&uuid=1bf3c431-a088-4820-b9d6-f57e9a6b6bd9&code=IC&build=143.2370': Server returned HTTP response code: 403 for URL: http://download.plugins.jetbrains.com/6317/31784/lombok-plugin-0.14.15.zip?updateId=31784&pluginId=6317&uuid=1bf3c431-a088-4820-b9d6-f57e9a6b6bd9&code=IC&build=143.2370
, response: 403 Forbidden
```

### Expected behavior
The expected behavior would be to actually get the plugin installed.

### Version information

 * **IDEA Version:** `15.0.6` 
 * **JDK Version:** `1.8.0_144-b01`
 * **OS Type & Version:** Linux

**Comment by Janmm14** [comment]
On the first glance it looks like jetbrains has an issue.

**Comment by AlexejK** [comment]
You can always install it manually from the Code releases page.
But it's correct, its an issue on the jetbrains side and has nothing to do with the plugin itself.

There should be a new version coming out soon which might trigger some updates on a Jetbrains side, but I'm not aware if it will solve the issue or not.

**Comment by wikier** [comment]
I'm going to close this issue. It looks it was a weird issue on my IntelliJ. After an upgrade, I got it installed as usual.
