### ISSUE TITLE
Delombok "All Lombok annotations" does not delombok the @UtilityClass annotation 

### ISSUE THREAD

**Issue by vnedyavila** [mplushnikov/lombok-intellij-plugin#406]
### Short description
Refactor --> Delombok --> All Lombok annotations does not delombok the @UtilityClass annotation.

### Expected behavior
Refactor --> Delombok --> All Lombok annotations delomboks the @UtilityClass annotation.

### Version information
 * **IDEA Version:** _Please provide full IntelliJ IDEA Version - available from About view_
IntelliJ IDEA 2017.1.2
Build #IC-171.4249.39, built on April 25, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

 * **JDK Version:** _What is your JDK version, including update level?_
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

 * **OS Type & Version:** _Are you on Mac/Windows/Linux? Provide as much information as possible about versions_
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

 * **Lombok Plugin Version:** _What is the version of the plugin installed?`_
0.14.16

 * **Lombok Dependency Version:** _What version of find are you using?_

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

1. Given the above specifications, write a test class that has one method with the following signature:
`
public void test() { return; }
`
2. Add the @UtilityClass annotation above the class.
3. Go to Refactor --> Delombok --> All Lombok annotations.
4. Observe that nothing happens.

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

STACKTRACE HERE (inside code markup)

```

**Comment by mplushnikov** [comment]
Yeap, you are right, there are no delombok support for @Utilityclass at the moment.

**Comment by swadhawan** [comment]
When is this expected.

https://plugins.jetbrains.com/plugin/6317-lombok-plugin
from Intellij 2016.2 @UtilityClass

Above plugin page says that this is already supported, but this doesn't work for me.
