### ISSUE TITLE
Inspection short name 'Convert2Diamond' is not unique

### ISSUE THREAD

**Issue by amaembo** [mplushnikov/lombok-intellij-plugin#409]
IntelliJ IDEA developer is here.

Having several inspections sharing the same short name may lead to subtle bugs, so in 2017.3 we [added](https://github.com/JetBrains/intellij-community/commit/9292c6698b6fe286bfac5edd6e5f0fce2a1c3461) a check for that during inspection registration. It appears that the check fails on the latest Lombok plugin (0.14.16) with the following message:

```
Short name 'Convert2Diamond' is not unique
class 'de.plushnikov.intellij.plugin.inspection.LombokExplicitTypeCanBeDiamondInspection' in 
PluginDescriptor[name='Lombok Plugin', classpath='C:\Lan\ultimate\config\plugins\lombok-plugin']
and
class'com.intellij.codeInspection.ExplicitTypeCanBeDiamondInspection' in 
PluginDescriptor[name='IDEA CORE', 
classpath='C:\Lan\ultimate\out\classes\production\ultimate-resources']
conflict
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.checkForDuplicateShortName(InspectionToolRegistrar.java:80)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.ensureInitialized(InspectionToolRegistrar.java:58)
```

I'm not sure whether this check will remain in release, but it's a good idea to change a duplicating short name now to prevent possible error messages and user frustration. Thank you for collaboration!

**Comment by akozlova** [comment]
Duplicates #359. I'll comment how to fix the initial issue there when the solution will be ready, thanks
