### ISSUE TITLE
val does not infer enum set

### ISSUE THREAD

**Issue by thomasmantay** [mplushnikov/lombok-intellij-plugin#410]
### Description

val does not infer enum set. Check out the following example:

public class Test {

    private enum TestEnum {
        A, B;
    }

    public boolean test() {
        final Set<TestEnum> someEnums = Sets.newHashSet();
        val setOfEnums = (1 == 1) ? EnumSet.allOf(TestEnum.class) : someEnums;
        return setOfEnums.contains(TestEnum.A);
    }
}

setOfEnums is inferred as Object rather than Set<TestEnum> and, hence, "contains" is marked as a compiler error in IDEA.

### Version information

IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

Lombok plugin version: 0.14.16.

**Comment by mplushnikov** [comment]
Hello thomasmantay,
please verify with last version of plugin (0.15.17.2)
It contains already some changes as part of #260, which should help for your example.
I cann't reproduce your error at the moment.

**Comment by thomasmantay** [comment]
Works now. No error marker anymore on the "contains" method. Tested in version 0.15.17.2.

**Comment by mplushnikov** [comment]
Thank you for your response!
