### ISSUE TITLE
No Annotation Processors option shown

### ISSUE THREAD

**Issue by DanteAndroid** [mplushnikov/lombok-intellij-plugin#411]
Please take a look at [this](https://github.com/nvenky/excel-parser/issues/14)

**Comment by mplushnikov** [comment]
Please provide more information. Example: https://github.com/mplushnikov/lombok-intellij-plugin/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by DanteAndroid** [comment]
Found it in Default setting, thx.
