### ISSUE TITLE
IntelliJ Idea don't detect src/main/lombok as source folder automatically.

### ISSUE THREAD

**Issue by broadliyn** [mplushnikov/lombok-intellij-plugin#413]
I am using Idea 2017.2 and latest lombok lib. 

Every time i imported project into idea, `src/main/lombok` will alway be recognized as a normal directory.

I have to manually mark all the `src/main/lombok` directories as source folder.

Is there anyway to make IntelliJ idea detect them as source folders?

Thank you.

**Comment by mplushnikov** [comment]
Hello @broadliyn, 
Which project are you talking about? Please describe your steps and what you try to accomplish.
