### ISSUE TITLE
Delombok does not consider @Builder.Default

### ISSUE THREAD

**Issue by hosswald** [mplushnikov/lombok-intellij-plugin#430]
Please refer to the description of the following ticket: https://github.com/rzwitserloot/lombok/issues/1527

**Comment by hosswald** [comment]
I'm not sure if this is a Lombok- or a IDEA-Plugin-Problem, should I create a ticket in the Lombok issue system @rzwitserloot ?

**Comment by mplushnikov** [comment]
Support for Builder.Default is still to be implemented, see #375
