### ISSUE TITLE
IntelliJ Idea doesn't recognize Lombok's annotations

### ISSUE THREAD

**Issue by sleyzerzon** [mplushnikov/lombok-intellij-plugin#433]
I'm having trouble integrating Lombok with the latest IntelliJ IDEA CE, the issue is fully documented here:

https://stackoverflow.com/questions/48015246/intellij-idea-doesnt-recognize-lomboks-annotations-not-a-duplicate

The forced manual solution has been documented here:

https://stackoverflow.com/questions/48016609/intellij-idea-doesnt-recognize-lomboks-annotations

My assumption was that the plugin should take care of downloading and referencing necessary jars.  Am I mistaken in that assumption?

**Comment by DarekDan** [comment]
Same issue,, here. 

IntelliJ IDEA 2017.3.2 (Ultimate Edition)
Build #IU-173.4127.27, built on December 25, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by sebek64** [comment]
I see the same problem in the latest idea on linux, in a project using gradle and having lombok in compileOnly and apt dependencies. Annotation processing is enabled in idea.

**Comment by Carighan** [comment]
Same issue here, but more specific: As of IntelliJ 2017.3.3, @Data is no longer recognized.

Running on Java 9.0.1 on a 64bit Windows 10.

**Comment by CodingOX** [comment]
Same issue !

**Comment by xp-vit** [comment]
I have the same issue (annotations not recognised):
 - Lombok is added as grade plugin https://github.com/franzbecker/gradle-lombok
 - Idea version 2017.2.5

Had to keep Lombok like this:
`compile group: 'org.projectlombok', name: 'lombok', version: '1.16.20'`

But this is adding Lombok to final Jar.

**Comment by sleyzerzon** [comment]
I posted my workaround here: https://stackoverflow.com/questions/48015246/intellij-idea-doesnt-recognize-lomboks-annotations/48016647#48016647
Perhaps it will help someone before the issue is addressed.

**Comment by xp-vit** [comment]
@sleyzerzon  Thanks, this is good workaround, but when you have a team 100+ members it becomes hard to rely on such workarounds. Fix should work with "git pull" :-)

**Comment by ripatte** [comment]
I am seeing this too on my IntelliJ 2017.3.4 UE. Intellij just compaints it's not able to find a symbol, which is a getter in this case.

We use Java 8.

This is how our ivy.xml look like:
`<dependency org="org.projectlombok" name="lombok" rev="1.16+" conf="build,runtime->default"/>`

And here is the .classpath entry:
`<classpathentry kind="lib" path="lib/build/lombok.jar"/>`

**Comment by sumitaccess007** [comment]
Hi,

I have also faced this Issue, Not able to recognize getters and setters while accessing them.
https://github.com/sumitaccess007/SpringBoot_DataModule_Sorting_Implementation.git
I do not understand the exact problem and with those Error messages the project is also building successfully.
