### ISSUE TITLE
@Bulder.Default field not recognized when the field is final

### ISSUE THREAD

**Issue by george-harness** [mplushnikov/lombok-intellij-plugin#434]
### Short description
For the following class:

    @Builder
     public class Test {
      @Builder.Default private final int code = 5;
    
      public static void foo() {
        Test.builder().code(5).build();
      }
    }

The method code is reported as missing.

### Expected behavior
The `code` method is valid, I would expect it to not be reported as error. 

### Version information

 * **IDEA Version:** 

IntelliJ IDEA 2017.3.2 (Community Edition)
Build #IC-173.4127.27, built on December 25, 2017
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

 * **JDK Version:**
1.8.0_152

 * **OS Type & Version:**
Mac 10.13.2 (17C88)
 * **Lombok Plugin Version:**
Version: 0.15.17.2

 * **Lombok Dependency Version:**
1.16.18

### Steps to reproduce
1. Write the class as is
2. The intelliJ will show the method code as an error

**Comment by george-harness** [comment]
I think the problem is in this line: https://github.com/mplushnikov/lombok-intellij-plugin/blob/6b0a48d181168c4abe6d951a2239775edd072159/src/main/java/de/plushnikov/intellij/plugin/processor/handler/BuilderHandler.java#L557

It should include an extra check if the field is annotated with `@Builder.Default`.

**Comment by mplushnikov** [comment]
Support for Builder.Default is still to be implemented, see #375
