### ISSUE TITLE
Occasional "compile errors"

### ISSUE THREAD

**Issue by nikowitt** [mplushnikov/lombok-intellij-plugin#436]
Given the class that is lomboked
```
public class RemoteMailConnection {
(...)
@ToString(exclude = "password") // cannot use constant here, see https://github.com/rzwitserloot/lombok/issues/1540
@Accessors(fluent = true)
@Getter
@Setter
public static class Configuration extends SettingsBasedConfiguration<Configuration> {

	@NotBlank
	private String user;

	@NotBlank
	private String host;

	@Range(min = 1, max = 65535)
	private int port = JAFConstants.REMOTE_MAIL_DEFAULT_PORT_IMAP;

	@Pattern(regexp = JAFRegExp.IMAP_OR_IMAPS)
	private String protocol = JAFConstants.REMOTE_MAIL_IMAP;

	@NotBlank
	@CustomValidationException(NoOrWrongPasswordSuppliedException.class)
	private String password;

	@Min(-1)
	private int timeout = 60000;

	@Min(-1)
	private int connectionTimeout = 60000;

	private boolean partialFetch = false;

	Configuration() {
		super(REMOTE_MAIL_IMAP + ".");
	}

	private String getPropertyPrefix() {
		Objects.requireNonNull(protocol(), "Protocol must be set in order to call this method!");
		return MAIL_PREFIX + protocol() + ".";
	}

}

(...)
}
```
IntelliJ occasionally complains about an issue:

![image](https://user-images.githubusercontent.com/1472328/34706619-1a086aa4-f509-11e7-911b-228b9e1bd113.png)

Opening/saving the file in a different work space does not display this issue. Recompiling or rebuilding the project does not solve this one.

IntelliJ IDEA 2017.3.2 (Community Edition)
Build #IC-173.4127.27, built on December 25, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.11.2-041102-generic

Lombok: 1.16.18
Lombok Plugin: 0.15.17.2

Any idea?
Regards,
Niko

**Comment by nikowitt** [comment]
Invalidating caches seems to help.

**Comment by mplushnikov** [comment]
It could be some of sideissues of one performance optimization done long time ago, like #210 too.
Didn't get time to investigate it deeper...

**Comment by mplushnikov** [comment]
Do you still have any issue with it? 

I' ll close this for now, feel free to reopen the issue, if it still occurs!
