### ISSUE TITLE
Wrong compile error when using AllArgsConstructor.staticName

### ISSUE THREAD

**Issue by nikowitt** [mplushnikov/lombok-intellij-plugin#437]
Hi there,

I've reported a wrong compile error which appears be caused by the Lombok plugin.

See https://youtrack.jetbrains.com/issue/IDEA-184745

IntelliJ IDEA 2017.3.2 (Community Edition)
Build #IC-173.4127.27, built on December 25, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.11.2-041102-generic
Lombok plugin: 0.15.17.2
Lombok jar: 1.16.18

Regards,
Niko

**Comment by akozlova** [comment]
I suggest patch to bind static factory param types to it's type parameters. Didn't build the plugin though

Index: src/main/java/de/plushnikov/intellij/plugin/processor/clazz/constructor/AbstractConstructorClassProcessor.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/de/plushnikov/intellij/plugin/processor/clazz/constructor/AbstractConstructorClassProcessor.java	(revision cf5fb9de71a873a9172360579bf34db53dad8ab6)
+++ src/main/java/de/plushnikov/intellij/plugin/processor/clazz/constructor/AbstractConstructorClassProcessor.java	(date 1515606739214)
@@ -2,19 +2,7 @@
 
 import com.intellij.ide.util.PropertiesComponent;
 import com.intellij.openapi.util.text.StringUtil;
-import com.intellij.psi.PsiAnnotation;
-import com.intellij.psi.PsiAnonymousClass;
-import com.intellij.psi.PsiClass;
-import com.intellij.psi.PsiCodeBlock;
-import com.intellij.psi.PsiElement;
-import com.intellij.psi.PsiField;
-import com.intellij.psi.PsiMethod;
-import com.intellij.psi.PsiModifier;
-import com.intellij.psi.PsiModifierList;
-import com.intellij.psi.PsiParameter;
-import com.intellij.psi.PsiParameterList;
-import com.intellij.psi.PsiType;
-import com.intellij.psi.PsiTypeParameter;
+import com.intellij.psi.*;
 import com.intellij.psi.util.PsiTypesUtil;
 import com.intellij.util.StringBuilderSpinAllocator;
 import de.plushnikov.intellij.plugin.lombokconfig.ConfigKey;
@@ -298,6 +286,15 @@
       method.withTypeParameter(typeParameter);
     }
 
+    PsiSubstitutor subst = PsiSubstitutor.EMPTY;
+    PsiTypeParameter[] methodTypeParameters = method.getTypeParameters();
+    final PsiTypeParameter[] classTypeParameters = psiClass.getTypeParameters();
+    for (int i = 0; i < classTypeParameters.length; i++) {
+      final PsiTypeParameter psiTypeParameter = classTypeParameters[i];
+      subst = subst.put(psiTypeParameter, PsiSubstitutor.EMPTY.substitute(methodTypeParameters[i]));
+    }
+
+
 //    final PsiElementFactory factory = JavaPsiFacade.getElementFactory(psiClass.getProject());
 //    final PsiTypeParameter typeParameter = psiClass.getTypeParameters()[0];
 //    final PsiClassType methodParameterType = factory.createType(typeParameter, PsiSubstitutor.EMPTY);
@@ -306,7 +303,7 @@
     if (!useJavaDefaults) {
       for (PsiField param : params) {
         final PsiType methodParameterType = param.getType();
-        method.withParameter(param.getName(), methodParameterType);
+        method.withParameter(param.getName(), subst.substitute(methodParameterType));
       }
     }

**Comment by mplushnikov** [comment]
Hello @nikowitt,
it's difficult to undestand your partial example. Please provide full minimal example to verify your issue.

As I can see, the error you are getting is right, becase the last parameter of the `of` - constructor should be a `BiConsumer` (something like `void accept(T t, U u)`) and you are passing getter to it. 
 ```
        public void setLastTransmittal(TransmittalActionDocument lastAction) {
		this.lastTransmittal = lastAction;
	}

	public void setLastComment(CommentActionDocument lastComment) {
		this.lastComment = lastComment;
	}
```
If I replace lombok annotation with manually created of-method, I get the same error like you.

@akozlova  Thank you for your diff, it was based on very old version of the code base. Please update your local installation next time:)

**Comment by nikowitt** [comment]
Hi there,
sure:

```
package com.sobis.jaf.playground;

import java.util.Set;
import java.util.function.BiConsumer;
import java.util.function.Function;

public class Test {

	private static final Action<TransmittalActionDocument> TRANSMITTALACTION = Action.of(TransmittalActionDocument.class, MetaDocument.TRANSMITTALS,
			MetaDocument.LAST_TRANSMITTAL, MetaDocument::getTransmittals, MetaDocument::setLastTransmittal);
	private static final Action<CommentActionDocument> COMMENTACTION = Action.of(CommentActionDocument.class, MetaDocument.COMMENTS,
			MetaDocument.LAST_COMMENT,
			MetaDocument::getComments, MetaDocument::setLastComment);

	private static class Action<T extends ActionDocument> {

		private final Class<T> clazz;
		private final String collectionProperty;
		private final String lastActionProperty;
		private final Function<MetaDocument, Set<T>> collection;
		private final BiConsumer<MetaDocument, T> lastAction;

		private Action(Class<T> clazz, String collectionProperty, String lastActionProperty, Function<MetaDocument, Set<T>> collection,
				BiConsumer<MetaDocument, T> lastAction) {
			this.clazz = clazz;
			this.collectionProperty = collectionProperty;
			this.lastActionProperty = lastActionProperty;
			this.collection = collection;
			this.lastAction = lastAction;
		}

		static <T extends ActionDocument> Action<T> of(Class<T> clazz, String collectionProperty, String lastActionProperty,
				Function<MetaDocument, Set<T>> collection, BiConsumer<MetaDocument, T> lastAction) {
			return new Action<>(clazz, collectionProperty, lastActionProperty, collection, lastAction);
		}
	}

	private static class MetaDocument {

		static final String TRANSMITTALS = "transmittals";
		static final String COMMENTS = "comments";
		static final String LAST_TRANSMITTAL = "lastTransmittal";
		static final String LAST_COMMENT = "lastComment";

		private Set<TransmittalActionDocument> transmittals;
		private Set<CommentActionDocument> comments;
		private TransmittalActionDocument lastTransmittal;
		private CommentActionDocument lastComment;

		public Set<TransmittalActionDocument> getTransmittals() {
			return transmittals;
		}

		public void setLastTransmittal(TransmittalActionDocument lastAction) {
			lastTransmittal = lastAction;
		}

		public void setLastComment(CommentActionDocument lastComment) {
			this.lastComment = lastComment;
		}

		public Set<CommentActionDocument> getComments() {
			return comments;
		}
	}

	private static abstract class ActionDocument {

	}

	private static class TransmittalActionDocument extends ActionDocument {

	}

	private static class CommentActionDocument extends ActionDocument {

	}
}
```

works fine without compilation error.
Modifying the Action class to
```
@AllArgsConstructor(staticName = "of")
	private static class Action<T extends ActionDocument> {

		private final Class<T> clazz;
		private final String collectionProperty;
		private final String lastActionProperty;
		private final Function<MetaDocument, Set<T>> collection;
		private final BiConsumer<MetaDocument, T> lastAction;
	}
```
displays the mentioned compile error.

Regards,
Niko

**Comment by souvik-locus** [comment]
Hello, will this be fixed anytime soon?

**Comment by mplushnikov** [comment]
Hello @souvik-locus, thank you for remembering, will fix this in next release!
