### ISSUE TITLE
Refactoring classes marked @Builder doesn't cascade changes

### ISSUE THREAD

**Issue by Bekreth** [mplushnikov/lombok-intellij-plugin#442]
When you have a pho marked with an @Builder annotation, refactoring the fields in the object doesn't translate to refactoring the builder methods throughout the code.

Ideally, this should work the same way it does for getters/setters where refactoring the name of the field causes Intellij to also refactor the names of the associated methods.

**Comment by rijnb** [comment]
I can confirm this bug - having the same problem here.

**Comment by mplushnikov** [comment]
Closed as duplicate of #119
