### ISSUE TITLE
@Data,@Builder,@Getter,@Setter can't supported interface or @interface

### ISSUE THREAD

**Issue by Jovi007** [mplushnikov/lombok-intellij-plugin#443]
### Short description
when I add @Data annotation to modify my custom anntotation , it'll tip me that "@Data is only supported on a class"
![4444](https://user-images.githubusercontent.com/17540320/35381513-85073574-01f7-11e8-83b6-ec946f7e4ac7.png)

### Expected behavior
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface Data {
	String staticConstructor() default "";
}

@Target(ElementType.TYPE)，The TYPE is including annotation type，so @Data can
supported annotation as I think

### Version information

 * **IDEA Version:** IntelliJ IDEA 2017.2.4 Build #IC-172.4343.14, built on September 12, 2017
 * **JDK Version:** JRE: 1.8.0_152-release-915-b12 amd64
 * **OS Type & Version:** Mac OS High Sierra 10.13.2
 * **Lombok Plugin Version:** 0.15.17.2
 * **Lombok Dependency Version:** 1.16.20

### Steps to reproduce
1.Create an annotation
2.Add @Data to modify this custom annotation

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [x] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
I just want to packaging @Data,@Builder,@NoArgsConstructor and @AllArgsConstructor into one custom annotation, and use the annotation to modify other classes; 
if these annotation couldn't supported annotation type ,how should I to do?
### Stacktrace
nope

**Comment by mplushnikov** [comment]
Unfortunately, this is not possible with lombok

**Comment by clembou590** [comment]
what a pity!

**Comment by danielchungara1** [comment]
2021, Any solution for wrapping lombok annotation?

**Comment by PawelSzymanski89** [comment]
@danielchungara1 maby create annotated class than extend it

**Comment by danielchungara1** [comment]
> 

@PawelSzymanski89 that sounds pretty good. You said that the subclasses will inherit lombok annotations (from the superclass). I will tray thanks!
