### ISSUE TITLE
Methods are not generated when a Lombok annotation is replaced by another one

### ISSUE THREAD

**Issue by ewirch** [mplushnikov/lombok-intellij-plugin#444]
Lombok Version: 1.16.20
Plugin Version: 0.15.17.2

Have a class with a private field. Annotate the class with `@Data`. Observe that setter and getter are generated. Now replace `@Data` by `@Getter` (by pasting the string from clipboard). Observe that getter and setter are removed, but not re-generated.

Expected: getter is generated.

**Comment by mplushnikov** [comment]
> Plugin Version: 0.15.17.2

Please update to 0.16.xxxx version of plugin, this issue should be already fixed 
Duplicate #210, #270
