### ISSUE TITLE
abstract class @Builder not support hierarchie

### ISSUE THREAD

**Issue by asmburning** [mplushnikov/lombok-intellij-plugin#445]
### Short description
abstract class @Builder not support hierarchie

### Expected behavior
Effective Java(3rd Edtion) Item 2
The Builder pattern is well suited to class hierarchies.

### Version information

 * **IDEA Version:** 2017.3.1
 * **JDK Version:** 9
 * **OS Type & Version:** win10
 * **Lombok Plugin Version:**0.15.17.2
 * **Lombok Dependency Version:** 1.16.18

### Expected Sample Code

// Builder pattern for class hierarchies
public abstract class Pizza {
public enum Topping { HAM, MUSHROOM, ONION, PEPPER, SAUSAGE }
final Set<Topping> toppings;
abstract static class Builder<T extends Builder<T>> {
EnumSet<Topping> toppings = EnumSet.noneOf(Topping.class);
public T addTopping(Topping topping) {
toppings.add(Objects.requireNonNull(topping));
return self();
} a
bstract Pizza build();
// Subclasses must override this method to return "this"
protected abstract T self();
}P
izza(Builder<?> builder) {
toppings = builder.toppings.clone(); // See Item 50
}}

public class NyPizza extends Pizza {
public enum Size { SMALL, MEDIUM, LARGE }
private final Size size;
public static class Builder extends Pizza.Builder<Builder> {
private final Size size;
public Builder(Size size) {
this.size = Objects.requireNonNull(size);
} @
Override public NyPizza build() {
return new NyPizza(this);
} @
Override protected Builder self() { return this; }} p
rivate NyPizza(Builder builder) {
super(builder);
size = builder.size;
}} p
ublic class Calzone extends Pizza {
private final boolean sauceInside;
public static class Builder extends Pizza.Builder<Builder> {
private boolean sauceInside = false; // Default
public Builder sauceInside() {
sauceInside = true;
return this;
} @
Override public Calzone build() {
return new Calzone(this);
} @
Override protected Builder self() { return this; }
} p
rivate Calzone(Builder builder) {
super(builder);
sauceInside = builder.sauceInside;
}}

**Comment by mplushnikov** [comment]
It has nothing to do with plugin, please ask lombok team for it's features.
