### ISSUE TITLE
plugin compatibility issue in IntelliJ IDEA 181.3494.3(IDEA 2018.1 EAP)

### ISSUE THREAD

**Issue by Sudio** [mplushnikov/lombok-intellij-plugin#449]
### Short description
plugin compatibility issue in IntelliJ IDEA 181.3494.3(IDEA 2018.1 EAP)

### Expected behavior
While the class call set/get method ,it should hint the method.

### Version information

 * **IDEA Version:** IntelliJ IDEA 181.3494.3(IDEA 2018.1 EAP)
 * **JDK Version:**JDK8
 * **OS Type & Version:** Windows 7
 * **Lombok Plugin Version:** 0.16-2017.3.3
 * **Lombok Dependency Version:** latest

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_
 When using IDEA 2018.1 EAP , any project integration with lombok hint get/set method doesn't exist.When we call set/get method ,the method will turn red.it seems the lombok plugin have problems in upward compatibility

**Comment by schauder** [comment]
Also for other things like required Arguments annotation. Basically it doesn't seem to work. It actually shows up as disabled when I do CMD-SHIFT-A lombok. Turning it on triggers a restart of the IDE but after that it is still OFF

**Comment by krzyk** [comment]
Created #463, it now compiles and tests pass for the EAP.

**Comment by Waize** [comment]
When will the new version be available?
