### ISSUE TITLE
@Data: inspection complains about missing @EqualsAndHashCode(callSuper=true), even though set in config

### ISSUE THREAD

**Issue by hosswald** [mplushnikov/lombok-intellij-plugin#454]
### Short description
My lombok.config has the following two lines:
```
clear lombok.equalsAndHashCode.callSuper
lombok.equalsAndHashCode.callSuper = CALL
```
Not when I have the Lombok inspection (there is only one, unfortunately) on in IDEA, I get the following warning in subclasses:
`Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '(callSuper=false)' to your type.`
This is annoying and requires me to add an unnecessary line that I wanted to avoid with the config above.

### Expected behavior
Please either provide fine-grained inspections, so I can turn the inspection off (best case: only for the above case) or don't show the warning when the config specifies the case.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2017.3.4 (Ultimate Edition)
 * **JDK Version:** jdk1.8.0_121
 * **OS Type & Version:** Windows 10
 * **Lombok Plugin Version:** 0.16-2017.3.3
 * **Lombok Dependency Version:** 1.16.20

### Steps to reproduce
 * Set up lombok.config as described and make sure it is loaded.
 * Turn on the Lombok inspection in IDEA
 * Create a class (it does not matter whether or not it is annotated with `@Data` or `@EqualsAndHashCode`)
 * Create a subclass
 * Annotate subclass with `@Data` or `@EqualsAndHashCode`
 * Notice the warning that suggests adding `(callSuper=false)`

### Sample project
```
class Parent {
    @Data // Here be dragons
    static class Child extends Parent { }
}
```

**Comment by srosenthal** [comment]
Same issue here on MacOS. I've disabled the inspection for now but I'd like to turn it back on if & when this is fixed.

**Comment by adamarmistead** [comment]
Added a PR to resolve this issue: https://github.com/mplushnikov/lombok-intellij-plugin/pull/459
