### ISSUE TITLE
Fix plugin in IntelliJ 2018.1

### ISSUE THREAD

**Issue by pety3bi** [mplushnikov/lombok-intellij-plugin#465]
Lombok annotations in IntelliJ 2018.1 are broken

**Comment by ruurd** [comment]
The newest IntelliJ announces that the plugin is incompatible.

**Comment by AleksanderGrzybowski** [comment]
At least now there is a red message on the release notes window. Fix would be awesome :)  
![image](https://user-images.githubusercontent.com/9342028/37982271-6b2fc926-31f0-11e8-9dcc-7c59c92c1303.png)

**Comment by bopfermann** [comment]
If anyone is stuck like I was, this seems to work until a real release comes out.

1. Clone the repo
1. In `gradle.properties` set `ideaVersion=2018.1`
1. Run `./gradlew buildPlugin`
1. Open IntelliJ
1. Uninstall existing Lombok plugin
1. Install built plugin `build/distributions/lombok-plugin-0.17.zip` with "Install Plugin from disk" button
1. Restart IntelliJ

This is NOT thoroughly tested, but did load up without issues and support compiling my reasonably complex codebase without issue.

Looking at the plugin details it shows `Version: 0.17-2018.1`

**Comment by ruurd** [comment]
PR is underway, running gradle check as we speak...

**Comment by padusumilli** [comment]
Here's the link to the plugin built on my local setup until it's offically supported

[lombok-plugin-0.17.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/1853861/lombok-plugin-0.17.zip)

**Comment by matheustardivo** [comment]
It's already released... just click on "Check for Updates..." to update it 😉

**Comment by tecnom1k3** [comment]
thanks, works like a charm

**Comment by iDenzil** [comment]
I'm still seeing the 0.16 version in IntelliJ and he's warning me it doesn't work with the latest update. So I haven't installed that update yet. 
When I click "check for updates" my IntelliJ only finds the IntelliJ update again, and not the Lombok plugin.
Am I doing it wrong or what am I missing?

**Comment by svenhaag** [comment]
It's still not available: https://github.com/mplushnikov/lombok-intellij-plugin/releases

**Comment by marcschumacher** [comment]
Try to use the update functionality in IntelliJ (on Mac: "IntelliJ IDEA/Check for updates").

**Comment by durimkryeziu** [comment]
This is how I did:

http://prntscr.com/ixf1ds

**Comment by kippert** [comment]
So for anyone struggling here. I updated my intellij to the latest version first (using toolbox) and then did the check for updates, at which point it says that the new lombok plugin is 0.15.17.2 at first glance it looks to all be there but time will tell. It's not immediately obvious, and the version numbering is probably throwing a few folks off, it did me.

**Comment by iDenzil** [comment]
So the new version is 0.15.17.2, and the previous version was 0.16-2017.3 ?
Thanks for the input everyone. I'm in no rush here, just wondering where is the difference coming from :)

**Comment by krzyk** [comment]
Fixed in #449, but it hasn't been released yet.

**Comment by wangchunyang** [comment]
@iDenzil I think the new version should be 0.17-2018.1. Perhaps @durimkryeziu was upgrading from old version to 0.16. So he could see the "update" button.

**Comment by sananiki** [comment]
just waiting...

**Comment by mplushnikov** [comment]
Hello guys, be cool, I'll make a new release next days!

**Comment by bn3t** [comment]
Waiting as well to be able to use 2018.1 with lombok.

**Comment by gajatko** [comment]
It works now (at least for me). After updating to 2018.1 it's possible to download an update ("help->check for updates").

**Comment by mplushnikov** [comment]
I just pushed current build of plugin as 0.17-2018.1 version. It can be downloaded from Intellij-Plugin-Repository.

**Comment by pedegie** [comment]
I have installed 0.17-2018.1 plugin version but it doesn't works for me. Everything works fine but lombok.config doesn't affects any .java files. Intellij version:  2018.1.2 EAP
