### ISSUE TITLE
[FEATURE REQUEST] Support hints for var / val

### ISSUE THREAD

**Issue by dodalovic** [mplushnikov/lombok-intellij-plugin#467]
Hi, 
I'm wondering what are the chances to show parameter hints next to `var` / `val` instances, like: 
![image](https://user-images.githubusercontent.com/6358061/38051830-b74b09c6-32cf-11e8-8d55-ec29cdd6d198.png)

Some people in my team still like to have hints about type, so might be interesting to support that. 

Thanks for great work!

**Comment by mplushnikov** [comment]
Such hints were already implemented by IntelliJ in the current version:
![image](https://user-images.githubusercontent.com/1204509/92311621-e00a1700-efb8-11ea-869a-2bef36f31666.png)
