### ISSUE TITLE
Feature request: support onX annotations via @_

### ISSUE THREAD

**Issue by danlangford** [mplushnikov/lombok-intellij-plugin#47]
we have used the onX annotations in the past and would love to keep using them in intellij

http://projectlombok.org/features/experimental/onX.html

we like to use it like this:
`@RequiredArgsConstructor(onConstructor = @_(@Inject))`

this allows us to do constructor level dependency injection without writing a constructor ourself. and with more and more java libraries pushing annotations the need to annotate lombok generated methods will continue to grow. (jersey, ,spring, servlet 3.0, jdo, jpa are all moving to annotation driven config)

currently when i try that the intellij inspection says `cannot find symbol '_'` which is a true statement. in fact if the `@_` type does exist then this feature will not work. see the small print on the link above. it is a hack but should work through jdk 6, 7, and 8 at least.

**Comment by mogren** [comment]
:+1:

**Comment by laurimak** [comment]
+1

**Comment by AlexejK** [comment]
+1

**Comment by jogura** [comment]
+1

**Comment by writzx** [comment]
+1

**Comment by jordanjennings** [comment]
+1 this would be an awesome feature to have

**Comment by aquator** [comment]
Hi, can we have an estimate on this? The issue is more then a year old, and I can see only +1-s. I am not familiar with IDEA plugin system, can it be done at all?

**Comment by haisi** [comment]
+1

**Comment by vicmosin** [comment]
Is there are some news regarding this topic? 0.9.4 still has this issues, not compile errors, just warnings, but still annoying.. With `@Getter(onMethod=@__({@Id, @Column(name="unique-id")}))` the same problems. Give us some response please regarding the state of this issue. Thanks!

**Comment by cdutra** [comment]
+1

**Comment by danlangford** [comment]
for all those that are watching this issue please note that @Siriah has submitted a pull request that will close this. so keep your eye on this https://github.com/mplushnikov/lombok-intellij-plugin/pull/120 it could make it into an upcoming patch.  thanks

**Comment by mogren** [comment]
The PR seems to work for me for @RequiredArgsConstructor(onConstructor = @__(@Autowired)) on 14.1.4 Ultimate

**Comment by mplushnikov** [comment]
Provided PR added to new release 0.9.6 of the plugin.
