### ISSUE TITLE
Warning about Wither requiring AllArgsConstructor, although Builder provides one

### ISSUE THREAD

**Issue by rillig-eon** [mplushnikov/lombok-intellij-plugin#473]
### Short description
```java
@Getter
@Builder
class Point {
    @Wither final int x;
    @Wither final int y;
}
```

Both instances of `@Wither` produce a warning: "Wither needs constructor for all fields". This warning is wrong since the `@Builder` already provides this constructor.

### Expected behavior
No warning appears.

### Version information

* IntelliJ IDEA 2018.1.1 (Community Edition)
* Build #IC-181.4445.78, built on April 9, 2018
* JRE: 1.8.0_161-b12 amd64
* JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
* Windows 7 6.1
 * **Lombok Plugin Version:** 0.17-2018.1

**Comment by mplushnikov** [comment]
This should be fixed in the next release 0.19
