### ISSUE TITLE
Importing @Builder generated builder classes does not work

### ISSUE THREAD

**Issue by bpedman** [mplushnikov/lombok-intellij-plugin#48]
For example, if I have:

```java
@Builder
public class Test
{
  private int foo;
}
```

This will generate an internal class named `TestBuilder`. If I then try to import it in another class like `import Test.TestBuilder` it thinks the class doesn't exist. 

However, I can still import the class `Test` and assign the builder to a new variable like `Test.TestBuilder builder = Test.builder();` but I would like to just reference the builder class itself if possible

**Comment by richadams8** [comment]
:+1:

**Comment by RodrigoQuesadaDev** [comment]
+1

**Comment by vicmosin** [comment]
+1, really drives crazy...

**Comment by mrcritical** [comment]
+1

**Comment by evantaurusta** [comment]
if you are usinng intelliJ, you can install the lombok plugins to let IntelliJ knows that the references are preCompiled

**Comment by cocoa93** [comment]
> if you are usinng intelliJ, you can install the lombok plugins to let IntelliJ knows that the references are preCompiled

brilliant! thank you so much
