### ISSUE TITLE
IntelliJ stuck on "Build" when running programs after plugin download

### ISSUE THREAD

**Issue by brett11** [mplushnikov/lombok-intellij-plugin#482]
### Short description
After downloading the plugin, IntelliJ gets stuck on "build" when running any program, even a "HelloWorld" program. The bottom of the screen shows "1 process running...", and "Build" shows in the "Background Tasks" popup, with a full blue progress bar, but never exits. 

### Version information

 * **IDEA Version:**  2018.1.3
 * **JDK Version:**  Java™ SE Development Kit 8, Update 171 (JDK 8u171)
 * **OS Type & Version:** _Are you on Mac/Windows/Linux? macOS High Sierra Version 10.13.3
 * **Lombok Plugin Version:**  0.17-2018.1

Note, I have also tried with IntelliJ version 2017.3.5 and Lombok version v0.16-2017.3.3 with the same results.

### Steps to reproduce
1. Download IntelliJ
2. Run HelloWorld program; it works
3. Download lombok-intellij-plugin
4. Run HelloWorld program; it gets stuck on build
5. Uninstall lombok-intellij-plugin
6. Run HelloWorld program; it still gets stuck on build

```

**Comment by mplushnikov** [comment]
I think it something wrong with your environment. If your issue still present after your uninstall the plugin, it has nothing to do with it.

**Comment by bharathkalyans** [comment]
Even I am facing similar issues!🥲
