### ISSUE TITLE
At Version 2018.2 of Intellij ,The lombok-plugin is invalidation

### ISSUE THREAD

**Issue by AndroidIosWebEmbeddedFirmwareDver** [mplushnikov/lombok-intellij-plugin#483]
![image](https://user-images.githubusercontent.com/8732312/40343264-a0d143dc-5dc1-11e8-9ca6-5ef7d6f0c13b.png)
The Issues is that :at Version 2018.2 of Intellij the lombok-plugin is invalidation。
![image](https://user-images.githubusercontent.com/8732312/40343277-afc96478-5dc1-11e8-84e9-a38e03e7442e.png)

<img width="424" alt="wx20180522-130903 2x" src="https://user-images.githubusercontent.com/8732312/40343349-fb1fc750-5dc1-11e8-9182-9c73f6734397.png">
<img width="669" alt="wx20180522-130944 2x" src="https://user-images.githubusercontent.com/8732312/40343350-fb694272-5dc1-11e8-8158-b42af8d88610.png">

**Comment by 9526xu** [comment]
+1

**Comment by cy4n** [comment]
duplicates https://github.com/mplushnikov/lombok-intellij-plugin/issues/481
