### ISSUE TITLE
Please add support for @Flogger annotation (lombok 1.18.0)

### ISSUE THREAD

**Issue by wkuranowski** [mplushnikov/lombok-intellij-plugin#488]
### Short description
Looks like `@Flogger` annotation is currently not supported. I get "Cannot resolve symbol 'log'" in IDE, but project builds fine.

### Version information

 * **IDEA Version:** 2018.1.4 Ultimate
 * **JDK Version:** jdk1.8.0_172
 * **OS Type & Version:** Windows 10
 * **Lombok Plugin Version:** 0.17-2018.1
 * **Lombok Dependency Version:** 1.18.0

**Comment by mplushnikov** [comment]
This should be fixed in the next release 0.19
