### ISSUE TITLE
Add support for lombok.noArgsConstructor.extraPrivate

### ISSUE THREAD

**Issue by noe-caratini** [mplushnikov/lombok-intellij-plugin#490]
### Short description
Lombok 1.16.22 introduced the config lombok.noArgsConstructor.extraPrivate to generate private no-args constructors for @Value and @Data, this is currently not supported by the plugin.

### Version information

 * **IDEA Version:** 2018.1.4
 * **JDK Version:** 1.8.0_152
 * **OS Type & Version:** MacOS High Sierra 10.13.2
 * **Lombok Plugin Version:** 0.17-2018.1
 * **Lombok Dependency Version:** 1.18.0

**Comment by mplushnikov** [comment]
This should be fixed in the next release 0.19
