### ISSUE TITLE
Lombok plugin breaks creating Intellij IDEA postfix expressions

### ISSUE THREAD

**Issue by teranik1994** [mplushnikov/lombok-intellij-plugin#497]
### Short description
When Lombok plugin is enabled and I am trying to create new postfix expression IDEA shows two Javas instead of one.
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000092579-IntelliJ-IDEA-Creating-postfix-expression-doesn-t-work?page=1#community_comment_360000037419

### Expected behavior
IDEA should show only one Java.
### Version information

 * **IDEA Version:** IntelliJ IDEA (build #IU-181.5281.24, 12 Jun 2018 15:10) 2018.1.5
 * **JDK Version:** java version "1.8.0_171" local, and IDEA under 1.8.0_152-release-1136-b39
 * **OS Type & Version:**  Linux (4.4.0-128-generic, amd64), Windows 7/10 too.
 * **Lombok Plugin Version:** Version: 0.18-2018.1

### Steps to reproduce
 1. Go to IDEA settings
 2. Go to the postfix expressions
 3. Click on the "+" button
 4. You should see 2 Java available

![image](https://user-images.githubusercontent.com/8035255/42039668-9c0f8cee-7af6-11e8-93d4-63c9de49a440.png)

**Comment by mplushnikov** [comment]
funny issue :smile:, should be fixed in the next release (0.20)

**Comment by baoxin** [comment]
![image](https://user-images.githubusercontent.com/9128509/50125520-3a72b980-02a4-11e9-8099-50ab87b3ceb0.png)
![image](https://user-images.githubusercontent.com/9128509/50125635-b53bd480-02a4-11e9-8ddd-bf6ef63f0f62.png)

Unable to create properly postfix completion

Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
