### ISSUE TITLE
The upgrade to IntelliJ 2018.2 warns Lombok plugin is incompatible

### ISSUE THREAD

**Issue by glawrence** [mplushnikov/lombok-intellij-plugin#508]
### Short description
The plug-in is incompatible with the latest IntelliJ (2018.2 build 182.3684.101) and hence I cannot upgrade and keep Lombok functionality, I assume, please correct me if my assumption is wrong. The exact message is "Plugin incompatible with the new build found: Lombok plugin"

### Expected behaviour
Seamless upgrade, without warning like other plugins

### Version information

 * **IDEA Version:** 2018.1.6 (build 181.5540.7)
 * **JDK Version:** 1.8.0_172
 * **OS Type & Version:** macOS High Sierra 10.13.6
 * **Lombok Plugin Version:** 0.19-2018.1
 * **Lombok Dependency Version:** sorry, not sure where to find this, should be latest

### Steps to reproduce
 1. "Check for updates.." in IntelliJ
 2. observe warning in red about Lombok plugin

**Comment by chamsco-aws** [comment]
It appears a 0.19-LATEST-EAP-SNAPSHOT has been released to the JetBrains plugin repo. It got 2018.2 working for me.

**Comment by leftler** [comment]
There appears to be a update released, version 0.19-LATEST-EAP-SNAPSHOT of the plugin got it working for me.

**Comment by Anksmahajan** [comment]
It does give a warning before updating but if you ignore and continue with the update there is a compatible Lombok plugin update that will happen after IDE update.

**Comment by liaoxu** [comment]
0.19-LATEST-EAP-SNAPSHOT works, just check for update again

**Comment by glawrence** [comment]
Thanks for the advice and input folks, much appreciated.

I did ignore the warning and continue with the upgrade, which worked fine.
Then I got the prompt to update the Lombok plugin, which updated to 0.19-LATEST-EAP-SNAPSHOT
Now everything is working fine.

**Comment by kirillgroshkov** [comment]
Ok, I gonna try that now with fingers crossed...

**Comment by kirillgroshkov** [comment]
Worked for me!

**Comment by BassplayerPatrick** [comment]
works like a charm!

**Comment by stlhrt** [comment]
The same case for 2018.2.1

**Comment by RodolfoAmandioDias** [comment]
The same case for 2018.2.1

**Comment by el-dom** [comment]
I wonder what you mean by saying "the same case...". Is `0.19-LATEST-EAP-SNAPSHOT` working for you on 2018.2.1 or is it broken again? Because it's not working for me. On 2018.2.2 as well, but that shouldn't be surprising.

**Comment by BassplayerPatrick** [comment]
People, sometimes changes are not backwards compatible. Like glawrence said: Just ignore the error, upgrade, and after restart the pluginmanager will suggest the lombok plugin update

**Comment by stlhrt** [comment]
Correct, update information in 2018.1 says the plugin is not compatible with new version,  but after upgrade 2018.2 actually updates Lombok plugin to new version

**Comment by flyrev** [comment]
Reinstalled the plugin, everything is red:

IntelliJ IDEA 2018.2 (Ultimate Edition)
Build #IU-182.3684.101, built on July 24, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-862.11.6.el7.x86_64

**Comment by maheeka** [comment]
Installed latest Lombok version : https://github.com/mplushnikov/lombok-intellij-plugin/releases/download/releasebuild_0.20/lombok-plugin-0.20-2018.2.zip and resolved.

**Comment by mplushnikov** [comment]
You can ignore this warning. Just update IntelliJ and update plugin afterwards to the last version. (Click Plugins->Browse Repositories -> and search for "lombok plugin") 
There is a version of plugin for each of last builds of Intellij: https://plugins.jetbrains.com/plugin/6317-lombok-plugin

**Comment by mariowise** [comment]
I've the plugin installed, the annotations activated and the dependency in my pom.xml. And lombok doesn't work (OSX: 10.13.6, Intellij: 2018.2.6 CE, lombo: 0.22.2018.2) any ideas?
