### ISSUE TITLE
@Slf4j support reports an error

### ISSUE THREAD

**Issue by yairzaslavsky** [mplushnikov/lombok-intellij-plugin#510]
### Short description
i had to upgrade to intellij 2018.2,  and i am using plugin version 0.19-LATEST-EAP-SNAPSHOT

I have a class annotated with @Slf4j annotation, and the following code:
`            log.warn("Extra page of books of library {} genre {} author: {}", library, genre,
                    author);`

The IDE marks this line as error -
Wrong 1st argument type - Found 'java.lang.string, required: 'org.slf4j.marker...'

### Expected behavior
Error should not appear.

### Version information
No error
 * **IDEA Version:** _Please provide full IntelliJ IDEA Version - available from About view_
 intellij 2018.2
 * **JDK Version:** _What is your JDK version, including update level?_

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

 * **OS Type & Version:** _Are you on Mac/Windows/Linux? 
mac
 * **Lombok Plugin Version:** _What is the version of the plugin installed?`_

 0.19-LATEST-EAP-SNAPSHOT

 * **Lombok Dependency Version:** _What version of lombok.jar are you using?_

Lombok-1.16

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. ???
 2. ???
 3. ???

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

STACKTRACE HERE (inside code markup)

```

**Comment by theshamuel** [comment]
After upgrading IDEA to 2018.2 I had the same problem, but I had gone out after reinstall Lombok plugin (Version: 0.19-LATEST-EAP-SNAPSHOT) from repository.

**Comment by mplushnikov** [comment]
@yairzaslavsky Looks like: https://stackoverflow.com/questions/33468151/slf4j-varargs-interprets-first-string-as-marker
Please provide some code example and versions of your log dependencies to look deeper...

**Comment by mplushnikov** [comment]
Closed, as no feedback provided. Not reproducible.

**Comment by sumitdang** [comment]
@Override
    public Optional<List<SamplePojo>> getSamplePojoByParam123(final String param1, final String param2, final String param3) {
        log.info("Called - getSamplePojoByParam123({0}, {1}, {2})", param1, param2, param3);

        log.info("Called - getSamplePojoByParam123({}, {}, {})", param1, param2, param3);

Here is the error -
![image](https://user-images.githubusercontent.com/8988907/49036202-eaed1200-f16b-11e8-904d-ee4cf6c501b2.png)

**Comment by Ghilteras** [comment]
is it still `invalid` after sumitdang comment?

**Comment by Ghilteras** [comment]
I'm still experiencing this issue by the way, can we reopen it?
