### ISSUE TITLE
Not compatible with intellij 2018.2

### ISSUE THREAD

**Issue by Nymerea** [mplushnikov/lombok-intellij-plugin#511]
The plugin is mark as not compatible with last intellij update

**Comment by jasper-vandemalle** [comment]
Have you read https://github.com/mplushnikov/lombok-intellij-plugin/issues/508? After updating to 2018.2 you'll receive a notification to update the Lombok plugin.

**Comment by Nymerea** [comment]
I didn't, thanks for your quick reply.
I've tried to update IDE first, ignoring lombok plugin. Then updated lombok plugin and it works like a charm.

thanks a million
