### ISSUE TITLE
Add support for @SuperBuilder

### ISSUE THREAD

**Issue by Cepr0** [mplushnikov/lombok-intellij-plugin#513]
### Short description

Please add support for [@SuperBuilder](https://projectlombok.org/features/experimental/SuperBuilder) annotation. It's a long-awaited feature and now, with Lombok 1.18.2, it has been released.

### Expected behavior
Support for @SuperBuilder annotation

### Version information

 * **IDEA Version:** 2018.1
 * **JDK Version:** JDK8
 * **OS Type & Version:** Windows 10 Pro
 * **Lombok Plugin Version:** 0.19
 * **Lombok Dependency Version:** 1.18.2

### Steps to reproduce
Add Lombok 1.18.2 to the project

**Comment by jackmahoney** [comment]
Would love to see this

**Comment by aaavang** [comment]
I was ecstatic when @SuperBuilder was released, but it's largely unusable without IDE integration.

**Comment by dabrowt1** [comment]
This would be very helpful for us.

**Comment by isaacaggrey** [comment]
I'd be glad to help contribute this, but I'd probably need some direction as I've never made an IntelliJ plugin. @mplushnikov are you or anyone else aware of anyone else working on this?

**Comment by smogstate** [comment]
i can help on that, but need a piece of explanation where to start.

**Comment by sluongng** [comment]
Is this being worked on by anyone? Or do we have to wait for the annotation to make it out of experimental?

**Comment by isaacaggrey** [comment]
@sluongng I don't believe so. If you're familiar with the IntelliJ plugin ecosystem, I say go for it.

I had started to very briefly during my company's hackathon but switched gears early on as I realized I have a lot more to grok looking at the existing `Builder` code in the plugin as an example.

**Comment by alishtory** [comment]
My team also need  @SuperBuilder Support

**Comment by ympadilha** [comment]
Yes please support for `@SuperBuilder` please! My team also uses it!

**Comment by mmfrb** [comment]
+1 !

**Comment by gordon043** [comment]
+1

**Comment by AUsachov** [comment]
+1

**Comment by griffico** [comment]
+2 (from paired programmers at major enterprise)

**Comment by Littlearphone** [comment]
+10086

**Comment by Arunagithub1** [comment]
We are eagerly waiting for support of superbuilder

**Comment by alexejk** [comment]
You are more than welcome to contribute with a PR for this

**Comment by dmincf** [comment]
+1

**Comment by binarywang** [comment]
hope it will be implemented soon

**Comment by smogstate** [comment]
i will check on weekend

**Comment by timothyBrake** [comment]
Yes that would be awesome as now in a professional environment creating test data for the models is a pain using just the @Builder because most probably these models extend from a superclass.

**Comment by wollowizard** [comment]
+1

**Comment by timothy-mugayi** [comment]
+1

**Comment by msio** [comment]
+1

**Comment by dongzhongwei** [comment]
My team also need @SuperBuilder Support

**Comment by mazemax** [comment]
+1

**Comment by mplushnikov** [comment]
Looked on this feature now. It's quite complex and will need some deeper rework of current Builder implementation. Solution will take some time.

**Comment by furkanozbay** [comment]
+1

**Comment by litttlefisher** [comment]
+1

**Comment by sasoori** [comment]
+1

**Comment by premik91** [comment]
This would be great! Without the lombok plugin, lombok is quite useless for us :)

**Comment by eacdy** [comment]
+1

**Comment by hiencnpm** [comment]
+1

**Comment by PWAlessi** [comment]
+1

**Comment by brucewinger** [comment]
+1

**Comment by msegmx** [comment]
+1

**Comment by no0ker** [comment]
+1

**Comment by woaixky** [comment]
+1

**Comment by nickbuller** [comment]
I think its fair to say that along with many other people this is my biggest issue, so would be wonderful to have super builders working in the plugin. Pretty please!

**Comment by kyivrush** [comment]
+1

**Comment by jamataran** [comment]
👍🏻

**Comment by mplushnikov** [comment]
This feature is already on my todo-list, more +1 comments doesn't make it faster :-)

**Comment by mplushnikov** [comment]
Hello guys,
implementation of SuperBuilder makes a big step forward. :wink:

If you want, you can try current alpha build (only for IntelliJ 2019.2+) here: https://github.com/mplushnikov/lombok-intellij-plugin/releases/tag/0.27_superbuilder_alpha

Feel free to share you experience and comment any problems with it. :fire:

**Comment by ifzm** [comment]
nice, long-awaited Zhimin Fang 邮箱：devfzm@gmail.com 签名由 网易邮箱大师 定制 On 09/01/2019 00:12, Michail Plushnikov wrote: Hello guys, implementation of SuperBuilder makes a big step forward. 😉 If you want, you can try current alpha build (only for IntelliJ 2019.2+) here: https://github.com/mplushnikov/lombok-intellij-plugin/releases/tag/0.27_superbuilder_alpha Feel free to share you experience and comment any problems with it. 🔥 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ifzm** [comment]
nice, long-awaited 👍

**Comment by litttlefisher** [comment]
perfect

**Comment by jruhe-adesso** [comment]
yeah :thumbsup:

**Comment by ponziani** [comment]
Works for me, great job !

**Comment by svenhaag** [comment]
Wow finally, super useful feature. However, I don't understand why we need an extra annotation for this? EqualsAndHashcode and ToString have “super=true“ for this. It would be more consistent I think.

**Comment by typekpb** [comment]
can't waut to see it in stable version

**Comment by octopus-prime** [comment]
Works like a charm! Thanks a lot!!

But (I think the same belongs to @Builder too)

```
@Data
@SuperBuilder
public class Foo {
    private int x;
    private int y;
}
```

produces this outline/structure

![image](https://user-images.githubusercontent.com/7620013/64127886-f41ea580-cdb3-11e9-9140-63e003b2e8dd.png)

As you can see: There is the default-constructor shown.
Also you can type `Foo foo = new Foo();` in IDE without error, because IDE thinks there is the default-constructor.
But starting the compiler you see the truth

```
error: constructor Foo in class Foo cannot be applied to given types;
        final Foo foo = new Foo();
                        ^
  required: FooBuilder<?,?>
  found: no arguments
  reason: actual and formal argument lists differ in length

```

**Comment by mplushnikov** [comment]
@octopus-prime Good catch, will look on it!

**Comment by fanlei1988** [comment]
Thanks，it's prefect.

**Comment by foresx** [comment]
Hey guys, when will the new release come?

**Comment by lehug** [comment]
> Hey guys, when will the new release come?

https://github.com/mplushnikov/lombok-intellij-plugin/releases/tag/0.27_superbuilder_alpha

**Comment by behzadian** [comment]
> Hi, I tried to install but I got error: Plugin 'Lombok' is incompatible with this installation
my idea version is: 2019.1.1 Build #IU-191.6707.61
> 
> > Hey guys, when will the new release come?
> 
> https://github.com/mplushnikov/lombok-intellij-plugin/releases/tag/0.27_superbuilder_alpha

**Comment by behzadian** [comment]
> 
> 
> > Hey guys, when will the new release come?
> 
> https://github.com/mplushnikov/lombok-intellij-plugin/releases/tag/0.27_superbuilder_alpha

Hi, I tried to install plug in but I got error: "Plugin 'Lombok' is incompatible with this installation"
My Idead version is: 2019.1.1 (Build #IU-191.6707.61)

**Comment by eric-gymondo** [comment]
> > > Hey guys, when will the new release come?
> > 
> > 
> > https://github.com/mplushnikov/lombok-intellij-plugin/releases/tag/0.27_superbuilder_alpha
> 
> Hi, I tried to install plug in but I got error: "Plugin 'Lombok' is incompatible with this installation"
> My Idead version is: 2019.1.1 (Build #IU-191.6707.61)

it's only supported by only for IntelliJ 2019.2+

**Comment by cosmin-rezmerita** [comment]
hi,
i used the lombok-plugin-0.27.0-2019.2 for @SuperBuilder annotation and i have the following structure:
```
@SuperBuilder
public class A {
public field1;
}

@SuperBuilder
public class B extends A {
public field2;
}
```
now, i'm trying to use the builder of class A in a scenario like this:
```
return someOptional
    .map(item -> A.builder().field1(value).build())
    .orElseGet(() -> A.builder().field1(otherClass.method(something)).build());
```

the error i get is:
Error:(102, 201) java: incompatible types: bad return type in lambda expression
    capture#1 of ? cannot be converted to capture#2 of ?

can you please help me with this?

Version information:
IntellijIdea: IntelliJ IDEA 2019.2.3 (Ultimate Edition) Build #IU-192.6817.14, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mplushnikov** [comment]
@cosmin-rezmerita Interesting usecase! I think you can't use a lambda expression for a functional interface, if the method in the functional interface has type parameters. See section §15.27.3 in JLS8: https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.27.3

But your code should compile if your add explicit cast to the map method: (.map(item -> (A) A.builder().field1(value).build())).

**Comment by cosmin-rezmerita** [comment]
@mplushnikov thank you! explicit cast works fine. 
is it something like using builder in .map does not return a "clear" object type, so .orElseGet does not know what to expect? Because using classic constructors also work:
```
return someOptional
    .map(item -> new A())
    .orElseGet(() -> A.builder().field1(otherClass.method(something)).build()
```

**Comment by mplushnikov** [comment]
@cosmin-rezmerita Yes, you are right. Using Builders-methods in the map-method returns generic wildcard type like ABuilder<?> and the right type cann't be automatically calculated. If you cast it/or use just constructor, its clear for the comiler, which type shlould be used.

**Comment by daniel-shuy** [comment]
Thank you so much @mplushnikov

**Comment by LalithaKuruba** [comment]
Hi  
Will @SuperBuilder is having support in xjc- lombok plugin ?
