### ISSUE TITLE
After idea 2018.2 installs lombok, it still shows me lombok dependency is missing.

### ISSUE THREAD

**Issue by zzzzjinxiang** [mplushnikov/lombok-intellij-plugin#515]
### Short description
After idea 2018.2 installs lombok, it still shows me lombok dependency is missing.	
                Lombok Dependency is missing
		Project "sell" does not seem to have lombok dependency added.
		This plugin does not provide it and will not function correctly without.
		Please make sure to add it manually and refresh your project.
But i already added dependency to pom.xml.
Dependency 'org.projectlombok:lombok:1.18.0' not found.
### Expected behavior
@Slf4j can work.

### Version information

 * **IDEA Version:** IDEA 2018.2
 * **JDK Version:** java 9.0.4
 * **OS Type & Version:** windows 10
 * **Lombok Plugin Version:**  Lombok 0.19-LATEST-EAP-SNAPSHOT
 * **Lombok Dependency Version:**  Lombok 1.18.2

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Dependency 'org.projectlombok:lombok:1.18.2' not found
 2. ???
 3. ???

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

Don't create a new "dependencies" frame, keeping one can work fine.

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

STACKTRACE HERE (inside code markup)

```

**Comment by jkobtr** [comment]
help me

**Comment by vistier** [comment]
me too

**Comment by CodingOX** [comment]
same issues

**Comment by merikan** [comment]
@zzzzjinxiang use plugin version 0.19-LATEST-EAP-SNAPSHOT instead. See issue #508

**Comment by zzzzjinxiang** [comment]
I added two dependencies to the pom.xml, you need delete one <dependencies></dependencies>, this problem would disapper. That's so studied. Shame XD.
