### ISSUE TITLE
get-getter of Boolean field is not shown in usages if is-getter is implemented

### ISSUE THREAD

**Issue by anibyl** [mplushnikov/lombok-intellij-plugin#517]
### Short description
I have this class
```
@Getter
class Foo {
    Boolean bar;
}
```
Usages (Alt+F7) of `bar` field include `bar` itself and `getBar()`. 
Then I implement primitive getter.
```
@Getter
class Foo {
    Boolean bar;

    public boolean isBar() {
        return bar != null && bar;
    }
}
```
Now usages include only `bar` and `isBar()` but no `getBar()` (which obviously exists).

### Expected behavior
Boolean getter `getBar()` is included in usages.

### Version information

 * **IDEA Version:** 2018.2
 * **JDK Version:** OpenJDK 1.8.0_152
 * **OS Type & Version:** Ubuntu 16.04
 * **Lombok Plugin Version:** 0.19-LATEST-EAP-SNAPSHOT
 * **Lombok Dependency Version:** 1.16.20

### Steps to reproduce
 1. Write this class
```
@Getter
class Foo {
    Boolean bar;

    public boolean isBar() {
        return bar != null && bar;
    }
}
```
 2. Show usages of bar field (Alt+F7)

**Comment by mplushnikov** [comment]
@anibyl Can you verify with current new version of plugin? It contains some improvements for "Find Usages" already

**Comment by anibyl** [comment]
@mplushnikov it works now.
Doesn't include `isBar()` usages but it's okay. In fact this is the same behavior as IDE has.
