### ISSUE TITLE
Private @NoArgsConstructor is not recognized by other plugins

### ISSUE THREAD

**Issue by davidhendrix** [mplushnikov/lombok-intellij-plugin#521]
### Short description
The private constructor created by adding `@NoArgsConstructor(access = AccessLevel.PRIVATE)` to a class is not recognized by other plugins such as SonarLint or Checkstyle-IDEA. 
These highlight the existence of a public default constructor in classes with only static methods. Manually adding a pricate constructor resolver the issue but adding the annotation does not.
I don't know whether it's an issue with these plugins or the lombok plugin but since it's the common part, I decided to start here.
### Expected behavior
The generated constructor should satisfy these plugins.

### Version information
IntelliJ IDEA 2018.2.1 (Ultimate Edition)
Build #IU-182.3911.36, built on August 6, 2018
Licensed to David Hendrix
Subscription is active until October 16, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
 * **IDEA Version:** IDEA 2018.2.1 (Ultimate Edition)
Build #IU-182.3911.36, built on August 6, 2018
 * **JDK Version:** JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 * **OS Type & Version:** Windows 10
 * **Lombok Plugin Version:** 0.19-LATEST-EAP-SNAPSHOT
 * **Lombok Dependency Version:** 1.16.18

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Create a class with a single public static method
 2. Add `@NoArgsConstructor(access = AccessLevel.PRIVATE)`
 3. run Checkstyle-IDEA with the HideUtilityClassConstructorCheck activated or SonarLint

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

STACKTRACE HERE (inside code markup)

```

**Comment by mplushnikov** [comment]
@davidhendrix This is something that should be done by other plugins. This plugin (lombok-intellij-plugin) adds support for IntelliJ only. It can not handle something, waht is normally done by other plugins.
Vote or make a PR for example for this issue for Checkstyle: https://github.com/checkstyle/checkstyle/issues/2579
