### ISSUE TITLE
Lombok is broken in IDEA 2018.2.2

### ISSUE THREAD

**Issue by mikeDubrovin** [mplushnikov/lombok-intellij-plugin#525]
### Short description
Lombok is broken in IDEA 2018.2.2

### Expected behaviour
IDEA can build a project.

### Version information
IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

 * **Lombok Plugin Version:**  0.19-LATEST-EAP-SNAPSHOT
 * **Lombok Dependency Version:** 1.12.2

**Comment by deepankarmalhan** [comment]
Same issue, even though Issue #508 says that Lombok plugin version 0.19-LATEST-EAP-SNAPSHOT works for some people.

**Comment by dev-indb** [comment]
same version, same issue

**Comment by sanmibuh** [comment]
The new version 2018.2.3 is incompatible 
![image](https://user-images.githubusercontent.com/15193703/45152110-61fbb580-b1d0-11e8-90ce-67455019624f.png)

**Comment by abarik1981** [comment]
Fails with `lombok plugin: 0.19-LATEST-EAP-SNAPSHOT `

```
IntelliJ IDEA 2018.2.4 (Community Edition)
Build #IC-182.4505.22, built on September 18, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.9.119-0.1.ac.277.71.329.metal1.x86_64
```

**Comment by mplushnikov** [comment]
You can ignore this warning. Just update IntelliJ and update plugin afterwards to the last version. (Click Plugins->Browse Repositories -> and search for "lombok plugin")
