### ISSUE TITLE
MacOS repeatedly crash after installing Lombok plugin

### ISSUE THREAD

**Issue by tommyJin** [mplushnikov/lombok-intellij-plugin#529]
I erase the disk and reinstall the macos with the help from Apple genius bar staffs to make sure the problem is not from the laptop itself. Then I install the IDEA, everything works fine. I open the preferences and click the Plugins. Search 'Lombok' in the repositories text input, and choose the 4th 'Lombok Plugin' and click the install button. After I press the restart IDEA button, the macos just freezed and nothing I can do. I have to shutdown the macpro and restart again, and when I open the project, the crash happened again and again. I can hardly work right now.
 
Could you guys give some advice?

System: MacBook Pro (Retina, 13-inch, Early 2015)
MacOS version: MacOS Mojave
IDEA: the latest 2018.2.4 Ultimate edition
lombok: from IDEA repositories

**Comment by mplushnikov** [comment]
Can you please verify your issue with current version of plugin 0.20?
If it still present there, please also test current snapshot build:
[lombok-plugin-0.21-2018.2.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2435390/lombok-plugin-0.21-2018.2.zip)

**Comment by mplushnikov** [comment]
Closed, as no feedback provided. Not reproducible.
