### ISSUE TITLE
Configuration keys

### ISSUE THREAD

**Issue by Lekanich** [mplushnikov/lombok-intellij-plugin#53]
Plugin doesn't support configuration keys like this http://projectlombok.org/features/configuration.html?

**Comment by mattcreaser** [comment]
Accessor prefix would be a nice-to-have.

**Comment by dmiescgm** [comment]
I need support for lombok.getter.noIsPrefix

Could you add support for this parameters, too?

**Comment by nkavian** [comment]
Here is the lombok.config I am dieing to use!! Please add the missing support.

````
clear lombok.accessors.prefix
lombok.accessors.chain = true
lombok.accessors.prefix += m
lombok.anyConstructor.suppressConstructorProperties = true
config.stopBubbling = true
````

**Comment by assylias** [comment]
Thanks for the food work. Here is my wishlist :-)

    lombok.accessors.chain = true
    lombok.accessors.fluent = true

**Comment by mplushnikov** [comment]
At the moment following lombok-configuration-keys were already added to plugin:
```
config.stopBubbling
lombok.log.fieldName
lombok.log.fieldIsStatic
lombok.equalsAndHashCode.doNotUseGetters
lombok.anyConstructor.suppressConstructorProperties
lombok.toString.doNotUseGetters
lombok.toString.includeFieldNames
lombok.accessors.chain
lombok.accessors.fluent
lombok.getter.noIsPrefix
```

**Comment by mmoayyed** [comment]
@mplushnikov great work. much appreciated. do u have a sense when the next release might be cut?

**Comment by mplushnikov** [comment]
Version 0.9.0 of plugin is available now. It contains some work for this issue, feel free to test and comment it.

**Comment by mmoayyed** [comment]
Does not seem to work for me.

I have IDEA 14.0.3 enterprise and lombok plugin 0.9.0 installed. My project is a multi-module maven project that consists of close to 20 sub-modules. In the parent directory where the root pom is, I have added:

```xml
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.16.2</version>
      <scope>provided</scope>
    </dependency>
```

The plugin is enabled for the parent and all other modules. Annotation processing is also enabled for all modules. My compiler is set to use javac and I am running JDK 1.7.

Also, in the very root directory where the parent pom is, I have a lombk.config file with the following:

```
config.stopBubbling = true
lombok.log.fieldIsStatic = false
lombok.log.fieldName = 'logger'
```

Pretty simple. **I restarted IDEA once just to be sure everything is activated.** and rebuilt the project again, to be extra sure.

I then annotated a class with @Slf4j and started getting compiler errors, because no "logger" field was generated for me. I do see "log" but there is no logger per my configuration. 

What's missing?

**Comment by mmoayyed** [comment]
I am also not clear on when the changes are activated. If change something in lombok.config, do I have to restart IDEA? Do I have to rebuild the project?

**Comment by mmoayyed** [comment]
It would also be good to be able to review which settings are recognized by the plugin. I see that I can modify fonts and colors for the config file but I have no idea which of the settings are loaded.

**Comment by Janmm14** [comment]
enabled annotation processing?

**Comment by mmoayyed** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1205228/6249959/f966683e-b747-11e4-966b-ad58749ef151.png)

Yes. See the screenshot please.

**Comment by mmoayyed** [comment]
Do I have to specify the lombok jar as an explicit processor? IDE is set to pick up processors from the classpath.

**Comment by mplushnikov** [comment]
You have to put your "lombok.config" files into project src directory at the moment. For example  in maven project it could be under "src/main/java".

**Comment by mmoayyed** [comment]
thanks for the tip. That didn't seem to work either. Moved the config file to src/main/java for a given module, made sure javac was the compiler, closed and reopened idea and rebuilt the project. same result.

**Comment by mmoayyed** [comment]
any other suggestions or thoughts as to why this isn't working? do you have a sample project by any chance I could try?

**Comment by zshamrock** [comment]
It doesn't work for me as well.
IntelliJ IDEA: 14.0.3 Enterprise
Lombok plugin: 0.9.1

I'm using `lombok.accessors.fluent`
I've tried to put lombok.config into src/main/java and src/main/lombok, no effect.

Thank you.

**Comment by addedsparkle** [comment]
It would be great if the plugin could pick the config file up from the project directory. I have a multi-project gradle build and if the lombok.config file is in src/main/java then it doesn't build. We have to have two copies of the config file, one in src/main/java for the plugin and one in project root dir for gradle.

**Comment by dmiescgm** [comment]
+1 to @addedsparkle

**Comment by nhekfqn** [comment]
+1 to @addedsparkle and @dmiescgm (running IDEA 14.1.1 and lombok plugin 0.9.2) I have a few modules and have to copy lombok.config to src/main/java folders of each module. This is biggest issue with pluging for me at the moment, hope you'll put it on top of your todo list.

Btw, I checked the pluging about 6 months ago and it was totally unusable for me at that moment. With the latest version of plugin I can at last start using lombok in my projects. Thanks for your work!

**Comment by scruffyfox** [comment]
Is there any ETA on support for this, especially accessor prefixes? Implementation of this for config files would literally make my teams life so much easier

**Comment by RodrigoQuesadaDev** [comment]
Support for accessor prefix configuration would be very helpful.

**Comment by jbatte47** [comment]
+1, I am writing field names with a different convention in files enhanced by lombok versus other files, which makes my eye twitch. Really looking forward to `lombok.accessors.*` support in IDEA.

**Comment by mogren** [comment]
Ah, works for me now that I saw that lombok.config has to be in src/main/java. I too wish that the plugin could pick up the settings from the base project directory like lombok does. (Right now we have to have 44 copies of our lombok.config just to rename the logging package....

**Comment by AlexejK** [comment]
Interesting.. According to Lombok source code it should bubble up the lookup until it gets stop bubbling configuration: 

https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/core/configuration/FileSystemSourceCache.java

That seems to be starting off a file that Lombok is parsing and all the way up. Can it be that the plugin is triggering Lombok slightly differently compared to Eclipse/Gradle ?

Would also love the ability to properly configure Lombok in a multi-module project.

**Comment by baracil** [comment]
According to the method `getStringLombokConfigProperty` in:

https://github.com/mplushnikov/lombok-intellij-plugin/blob/master/lombok-plugin/src/main/java/de/plushnikov/intellij/plugin/lombokconfig/ConfigDiscovery.java

The plugin seems to have its own implementation to read the global configuration. 

It does not do exactly like Lombok: it starts from the folder containing the file that it is parsing but does not go all the way up, instead it stops at the default package. That is why putting the configuration file in src/main/java works but not in the root directory of the project.

**Comment by mplushnikov** [comment]
@baracil Exactly, at the moment you have to place lombok.config file in the src/main/java or src/main/resource directory (or other source root directory).
I will check the possibility of reading of config file from the module/project directory. That would help to simplify multi-project configuration.

**Comment by jemshit** [comment]
With Android Studio 1.5 and Plugin v 0.9.6.14, IDE can't find `lombok.config`. I've put it under `/src/main/java`.

**Comment by darenegade** [comment]
Of course it's the same with IntelliJ 15. Neither ```src/main/java``` nor ```src/main/resource``` works for me.

A nice side effect is, if i put the ```@Accessors``` annotation above my class, the class structure changes to the configured behavior. Unfortunately it has no effect on the generated  Class files.

**Comment by AlexejK** [comment]
This is interesting. Im using 15.0.2 (and was using both EAP and prod versions of 15) and everything works fine for me. Naturally I had to ensure that In Preferences -> Other Settings -> Lombok plugin, I have "Enable Lombok plugin for this project" enabled.

I have Lombok Plugin 0.9.6.14 installed as well.
You do have Lombok as dependency in the project (in pom.xml or build.gradle), right?

**Comment by jemshit** [comment]
Of course, otherwise it won't compile

**Comment by AlexejK** [comment]
I have customised logger variable name that is being found by the plugin. Could it be that this is an issue of some configurations not being applied properly rather than lombok.config not being found?

**Comment by jemshit** [comment]
@AlexejK  i am trying to use
`lombok.anyConstructor.suppressConstructorProperties = true` which does not work

**Comment by darenegade** [comment]
I have set the Maven dependeny for Lombok in my pom.xml and the plugin is enabled for the project.
(Lombok Plugin 0.9.6.14 and IntelliJ 15.0.2 )

I my  ```src/main/resource/lombok.config``` i have set the property ```lombok.getter.noIsPrefix = true```. But i was mistaking with the ```@Accessors``` annotation. I rebuilded my project and lombok created all Class Files with no Is-Prefix. 
But the Class Structure didn't changed and stayed with the Is-Prefix. And IntelliJ can't make the project cause it didn't find the symbol for the getter without IS-Prefix. After that I applied the  ```@Accessors``` annotation to my class and everything worked as intended (Class Structur had Get-Prefix too).

But shouldn't it just work without the extra annotation?

**Comment by AlexejK** [comment]
From what I know, `@Accessors` is the experimental feature in Lombok, and the IntelliJ plugin has to support each and every feature to make sure IDEA understands it.

I would suggest that you create a separate issue for this specific functionality.

**Comment by idelpivnitskiy** [comment]
`lombok.accessors.chain = true` doesn't work if you don't have an `@Accessors` annotation on the bean. But according to the Lombok's doc:
> lombok.accessors.chain = [true | false] (default: false)
If set to true, **any class that either doesn't have an @Accessors annotation, or it does**, but that annotation does not have an explicit value for the chain parameter, will act as if @Accessors(chain = true) is present.


Tested with version 0.10.16 and Intellij IDEA 2016.1.1

**Comment by mplushnikov** [comment]
New version (0.11) of plugin was released today. It contains many improvements for configuration system of lombok. Please verify it and open new issues for new problems:)
