### ISSUE TITLE
Low performance of @Builder

### ISSUE THREAD

**Issue by ricksouzaa** [mplushnikov/lombok-intellij-plugin#535]
### Short description

When I use @Builder the IntelliJ IDE gets very slow and locks.

### Expected behavior

No slowing or blocking.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2018.2.4 (Ultimate Edition) - Build #IU-182.4505.22
 * **JDK Version:** 1.8.0_152-release-1248-b8 x86_64 - OpenJDK 64-Bit Server VM by JetBrains s.r.o
 * **OS Type & Version:** macOS 10.13.6
 * **Lombok Plugin Version:** 0.21.2018.2
 * **Lombok Dependency Version:** I don't know

### Steps to reproduce

I have an api rest with 60 JPA entities and using the following annotations:

@Entity
@Table (name = "person")
@DynamicInsert
@DynamicUpdate
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Loggable
public class Person extends AbstractEntity <Long> {...

When I comment on the @Builder IntelliJ IDE stops crashing.

**Comment by mplushnikov** [comment]
Can you please provide some example project, to reproduce your performance issue?

**Comment by ricksouzaa** [comment]
I already reinstalled the plugin but the problem continues.

It only happens when you have many entities annotated with @Builder.
If I create a test project the error will not happen because there will be only one template.

Lombok Plugin Version: 0.21.2018.2

**Comment by mplushnikov** [comment]
Similar issue #516

**Comment by mplushnikov** [comment]
Will handle it by generall performance improvements in #516

**Comment by mplushnikov** [comment]
Just added something, that could help to get better performance. Can you @ricksouzaa check this version in your environment?
[lombok-plugin-0.22-2018.2.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2451893/lombok-plugin-0.22-2018.2.zip)

**Comment by ricksouzaa** [comment]
Great !!!
The problem was fixed !!!

Thanks a lot masters !!!
