### ISSUE TITLE
Lombok Plugin is incompatible with this installation

### ISSUE THREAD

**Issue by pilif42** [mplushnikov/lombok-intellij-plugin#537]
I am using 
IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018
Licensed to ...
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

I have downloaded locally lombok-plugin-0.21-183.2153.8.zip

When pointing to it, I am getting: Plugin 'Lombok Plugin' is incompatible with this installation

**Comment by mplushnikov** [comment]
Please use compatible build for your version. For IntelliJ 2018.2 it is here: https://github.com/mplushnikov/lombok-intellij-plugin/releases/download/releasebuild_0.21/lombok-plugin-0.21-2016.2.zip
Or just install from Jetbrains plugin center.
http://plugins.jetbrains.com/plugin/download?rel=true&updateId=50582
