### ISSUE TITLE
error warning when using inner classes

### ISSUE THREAD

**Issue by FirstJavaMaster** [mplushnikov/lombok-intellij-plugin#541]
### Short description
When using lombok on an inner class, the access modifier of the inner class will have an exception warning.

### Expected behavior
In fact, this warning should not appear

### Version information

 * **IDEA Version:** The latest version, in fact, every version is like this, this warning has nothing to do with the version of the idea
```
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
Licensed to ***
Subscription is active until May 5, 2019
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

 * **JDK Version:** The latest version, in fact, every version is like this, this warning has nothing to do with the java version
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

 * **OS Type & Version:** Windows 1804. In fact, every version is like this, this warning has nothing to do with the windows version
 * **Lombok Plugin Version:** Version: 0.21.2018.2, in fact, the version I have used is the same
 * **Lombok Dependency Version:** The current version of 1.18.2, in fact, the version I have used is the same

### Steps to reproduce
This warning appears when the code is statically checked, so the way to reproduce this problem is to create a few test classes.

1. Create a class A that has an inner class. Manually declare the get and set methods.
![image](https://user-images.githubusercontent.com/22362110/47283476-26993700-d616-11e8-8ad6-e34618e82dc2.png)

2. Create a class B, which also has an inner class. Here use `@Data` to declare the get and set methods.
![image](https://user-images.githubusercontent.com/22362110/47283559-7972ee80-d616-11e8-921b-7ae53acc18ca.png)

3. Use two inner classes in the same way in another place, but note the warning in the previous image.
![image](https://user-images.githubusercontent.com/22362110/47283644-bb9c3000-d616-11e8-9e7b-f7994426e90e.png)

4. In fact, I can't remove the `public` of `Inner.class` in `B.class`, because then the compiler will report an error. In other words, there is an extra warning here.

### Sample project
my [demo](https://github.com/FirstJavaMaster/demo-show-github/tree/master/lombok-access-modifier-warning)

**Comment by mplushnikov** [comment]
Thank you @FirstJavaMaster for excellent description!
