### ISSUE TITLE
Feature request : Rename getter for boolean/ Boolean field

### ISSUE THREAD

**Issue by mesudip** [mplushnikov/lombok-intellij-plugin#545]
Let's say for a field `boolean active` isn't it better to have a getter named `isActive` rather than `getActive` ? The same applies for all boolean fields.

**Comment by mplushnikov** [comment]
What do you mean? How the methods are generated, is defined by lombok project: https://projectlombok.org/features/GetterSetter

**Comment by mplushnikov** [comment]
No feedback provided, closed as invalid
