### ISSUE TITLE
@FieldNameConstants Incompatability with lombok 1.18.4

### ISSUE THREAD

**Issue by alanachtenberg** [mplushnikov/lombok-intellij-plugin#547]
### Short description
1.18.4 introduced a breaking change for @FieldNameConstants. Generated fields are no longer prefix + fieldName + suffix and instead are generated as just fieldName inside an inner type.

After delombok i am seeing
`public static final String nullFIELDnull = "field";`

### Expected behavior
Generated strings should belong in inner type as

`public final class Fields{
  public static final String FIELD = "field";
}
`

See unit test from lombok repo.
Before:
https://github.com/rzwitserloot/lombok/blob/3d432c38d0cfeb36b8e7402eca56faaafcf7bac7/test/transform/resource/before/FieldNameConstantsBasic.java

After:
https://github.com/rzwitserloot/lombok/blob/3d432c38d0cfeb36b8e7402eca56faaafcf7bac7/test/transform/resource/after-delombok/FieldNameConstantsBasic.java

### Version information

 * **IDEA Version:** Build #IU-182.4892.20, built on October 16, 2018

 * **JDK Version:** JRE: 1.8.0_152-release-1248-b19 amd64
 * **OS Type & Version:** Windows 7 6.1 * 
 * **Lombok Plugin Version:** 0.22.2018.2
 * **Lombok Dependency Version:** 1.18.4

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

Simply use @FieldNameConstants with latest version of lombok.

**Comment by dabrowt1** [comment]
+1

**Comment by Vyacheslav-Lapin** [comment]
+1

**Comment by ziduye** [comment]
up

**Comment by srowatt** [comment]
+1

**Comment by FatCash** [comment]
+1

**Comment by eximius313** [comment]
+1

**Comment by Streamline27** [comment]
+1

**Comment by tfactor2** [comment]
+1

**Comment by luludwa** [comment]
+1

**Comment by lludwa** [comment]
Are you going to fix it?

**Comment by darekurlik** [comment]
+1

**Comment by voliveira89** [comment]
I'm having this problem too, but with OpenJDK 11!

**Comment by QwerTech** [comment]
+1

**Comment by vrosenshtein** [comment]
I am still having the problem. Tried on versions 1.18.4, 1.18.5 and 1.18.6.

<img width="691" alt="screenshot" src="https://user-images.githubusercontent.com/34549691/52807787-2b866880-3095-11e9-81c5-1680446b301e.png">

**Comment by mplushnikov** [comment]
@vrosenshtein: this change will be available in the next release of plugin (version 0.24)

**Comment by TomaszGaweda** [comment]
@mplushnikov do you know when 0.24 will be released? :) Thanks in advance!

**Comment by lukasz-gosiewski** [comment]
@mplushnikov +1 for Tomasz, fix release would be really appreciated.

**Comment by QwerTech** [comment]
+1 also very interested in release date

**Comment by voliveira89** [comment]
I would appreciate know the release date please :)

**Comment by lukasz-gosiewski** [comment]
It's released, if someone is still waiting.

**Comment by schernov-xo** [comment]
Well, just installed 0.25-EAP onto IDEA 2019.1.2. The issue is still here if the lombok dependency is 1.18.4 or 1.18.6. If the lombok is 1.18.2, it's fine of 0.25-EAP (was not working on 0.24 - thanks).
![Screenshot 2019-05-09 at 18 27 55](https://user-images.githubusercontent.com/41187778/57466089-9b695100-7288-11e9-8a6b-53fddd65bdec.png)

**Comment by mplushnikov** [comment]
You are right @schernov-xo . You need compatible lombok library for your code of couse.

**Comment by schernov-xo** [comment]
@mplushnikov just realized that lombok 1.18.6 has another format of Fields class (instead of FIELD_ constants). Did not expect such change in a minor update (since 1.18.2). Seems to be working fine. Thanks!
