### ISSUE TITLE
Regression in 0.22.2018.2: Cannot resolve method 'build()'

### ISSUE THREAD

**Issue by mkeller-ergon** [mplushnikov/lombok-intellij-plugin#548]
### Short description
Since the update to 0.22.2018.2, we get some classes marked as invalid in intelliJ 2018.2.5.
They get 'red' as soon as they are opened in the editor, however the build runs through smoothly and the 'redness' can temporarily be removed by manually rebuilding that module.
The effect is always:
* Some statically imported builder's ".build()" method is marked red with the message "Cannot resolve method 'build()'"
* Quite often also the corresponding static import is marked as 'unused'
* IntelliJ also fails to display the type of the static method:
![image](https://user-images.githubusercontent.com/23031669/48184118-52fcc500-e331-11e8-8b1c-7335bbb871ea.png)

### Expected behavior
No red markers, intellij detects the build() method correctly.

### Version information

 * **IDEA Version:**
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
Licensed to Ergon Informatik AG / Matthias Keller
Subscription is active until July 5, 2019
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
 * **JDK Version:** OpenJDK 11.0.1
 * **OS Type & Version:** Windows 10 Pro
 * **Lombok Plugin Version:** 0.22.2018.2
 * **Lombok Dependency Version:**lombok:1.18.2

**Comment by mplushnikov** [comment]
Hello Matthias,
do you have some reproducible example for your issue? Can you tell some more details? Do you have current issue only with static imports?

**Comment by mplushnikov** [comment]
Well, I'll close it for now. Please retest with last plugin version 0.27 and feel free to open a new issue if it doesn't help...
