### ISSUE TITLE
Doesn't compile with Gradle 5 RC

### ISSUE THREAD

**Issue by asarkar** [mplushnikov/lombok-intellij-plugin#552]
### Short description
Doesn't compile with Gradle 5 RC

### Expected behavior
Duh

### Version information

 * **IDEA Version:**
IntelliJ IDEA 2018.3 EAP (Community Edition)
Build #IC-183.4284.36, built on November 7, 2018
 * **JDK Version:** 11.0.1
 * **OS Type & Version:** macOS 10.14.1
 * **Lombok Plugin Version:** v0.22.IDEA-EAP
 * **Lombok Dependency Version:** 1.18.4
 * **Gradle Wrapper Version:** gradle-5.0-20181112000030+0000

### Steps to reproduce
None of the Lombok annotations work. All of the following are red.
```
import lombok.AccessLevel;
import lombok.Getter;

@Getter(AccessLevel.PROTECTED)
```

STACKTRACE HERE
```
Error:(12, 27) java: package lombok.extern.slf4j does not exist
Error:(17, 2) java: cannot find symbol
  symbol: class Slf4j
```

```
dependencies {
    annotationProcessor("org.projectlombok:lombok:$lombokVersion")
    compileOnly("org.projectlombok:lombok:$lombokVersion")
}
```

**Comment by mplushnikov** [comment]
Please ask in project lombok, or make new issue there: (https://github.com/rzwitserloot/lombok/issues) It has nothing to do with lombok-plugin for IntelliJ.

**Comment by mplushnikov** [comment]
Hello @asarkar 
I found this issue for IntelliJ: https://youtrack.jetbrains.com/issue/IDEA-201974
It can explain your problem, please try to update your IntelliJ. There is a new fixed version now.
