### ISSUE TITLE
IDEA plugin breaks custom getter/setters by refactoring 

### ISSUE THREAD

**Issue by pashazadeh** [mplushnikov/lombok-intellij-plugin#555]
I have classes with dozens of getter/setters, most of them are simple one, but a few are not. When using IDEA plugin **refactor>lombk>Default @ Getter** it removes all the getters even the not default ones and adds the **@ Getter** annotation, same thing happens for **refactor>lombk>Default @ Setter**.

For example if in my class I have:

```
public MyClass {
    // lots of field with default getter and setter
    private SomeType someType;
    public SomeType getSomeType() {
        if (someType == null) { someType = new SomeType(); }
        return someType;
    }
}

```
I expect the plugin just removes the simple getter/setters and let this custom getter remain in class, but it removes this too.

**Comment by mplushnikov** [comment]
I'll close this one. Fix should be provided by #688
