### ISSUE TITLE
IntelliJ reports not implemented method on code genereted by lombok

### ISSUE THREAD

**Issue by KamilHapak2** [mplushnikov/lombok-intellij-plugin#559]
### Short description
If a class is implementing interface that has `getSomething` method, and class has `something` attribute and `@Getter` annotation, it will compile, but Intellij reports error "class have to implement interface method"

### Expected behavior
Plugin should inform Intellij that this method will be generated

### Version information

 * **IDEA Version:** IntelliJ IDEA 2018.3 (Community Edition)
Build #IC-183.4284.148, built on November 21, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 * **JDK Version:** 1.8.0_121
 * **OS Type & Version:** Windows 10 10.0
 * **Lombok Plugin Version:** v0.21.2018.2
 * **Lombok Dependency Version:** 1.18.0
### Steps to reproduce

 1. Paste given code:
 
import lombok.Getter;
import lombok.Setter;

interface Testable{
    String setSomething();
}
@Setter
public class Test implements Testable{
    private String something;
}
The error message:
Class 'Test' must either be declared abstract or implement abstract method 'setSomething()' in 'Testable'
```

**Comment by FrankBian** [comment]
the plugin is incompatible with current version.

**Comment by mplushnikov** [comment]
I think you have an incompatible version of plugin installed in your IntelliJ. 
"v0.21.2018.2" is definitely wrong for "2018.3" So plugin isn't working at the moment
Please update to 0.23-2018.3, or just select "Help>Check for updates" - it will update your plugins automatically.
