### ISSUE TITLE
Missing auto-generated modifiers on fields and class shown in the "Structure" window when using `@Value`

### ISSUE THREAD

**Issue by kuporific** [mplushnikov/lombok-intellij-plugin#56]
When using [`@Value`](http://projectlombok.org/features/Value.html), "all fields are made private and final by default" and "the class itself is also made final by default". For example:

    @Value
    public class MyDataClass {
	Object o1;
	private Object o2;
	private final Object o3; 
    }

In IntelliJ's "Structure" window (below the "Project" window by default), the class and all fields should be marked `final`, and all fields should also be marked `private`, which we can inspect by running the following code

    System.out.println("MyDataClass Final: "
            + Modifier.isFinal(MyDataClass.class.getModifiers()));

    Arrays.stream(MyDataClass.class.getDeclaredFields()).forEach(
            field -> System.out.println(field.toString()));

Which outputs

    MyDataClass Final: true
    private final java.lang.Object com.etrade.token.actions.MyDataClass.o1
    private final java.lang.Object com.etrade.token.actions.MyDataClass.o2
    private final java.lang.Object com.etrade.token.actions.MyDataClass.o3

Currently, the modifiers are not changed:

![screen shot 2014-06-24 at 2 49 26 pm](https://cloud.githubusercontent.com/assets/4064195/3376001/5102f97e-fbd0-11e3-8a66-1894c53280a3.png)

This allows me to extend the class in the IDE with no warnings or errors (but this fails on build).

**Comment by jschaf** [comment]
Is there an issue filed with IntelliJ I can follow for this?

**Comment by jfftonsic** [comment]
Having similar problems. Needless to say, this is a terrible thing for lombok + Intellij users. Is there a probability for this feature to be implemented in Intellij?

**Comment by mplushnikov** [comment]
I just filed a issue [IDEA-153706](https://youtrack.jetbrains.com/issue/IDEA-153706) for Intellij.
