### ISSUE TITLE
UI freezes with plugin enabled

### ISSUE THREAD

**Issue by GMillerVarian** [mplushnikov/lombok-intellij-plugin#568]
### Short description
With Lombok plugin enabled, IntelliJ IDEA UI becomes laggy, with freeze threadDumps in the logs folder. I have contacted JetBrains support, and they indicated that they have received multiple reports of freezing with Lombok plugin and suggested I report the issue here.

### Expected behavior
UI remains response, with blocking operations done in background threads.

### Version information

 * **IDEA Version:** 2018.3.1
 * **JDK Version:** 8u191
 * **OS Type & Version:** Windows 10
 * **Lombok Plugin Version:** 0.22
 * **Lombok Dependency Version:** 1.18.4

### Steps to reproduce

 1. Import Java Gradle project into IntelliJ
 2. Disable all custom plugins, notice IDEA is responsive, and no freeze dumps appear in IDEA logs folder (ex. %USERPROFILE%\\.IntelliJIdea2018.3\\system\\log)
 3. Enable Lombok plugin, UI now becomes laggy. Some freezes are less than 5 seconds, and do not appear in logs folder, while other freezes are longer and do appear as freeze dumps in the logs folder.

### Additional information

According to JetBrains support, freezes appear related to file I/O. Antivirus software may exacerbate the issue, making it easier to reproduce.

**Comment by mplushnikov** [comment]
Hello @GMillerVarian 
Do you have some example project to reproduce your issue? 
Do you have an jetbrains tracking issue number to read your conversation with Jetbrains support?

**Comment by GMillerVarian** [comment]
I tried a couple of sample projects that I downloaded and was not able to see the problem to the extent that we are seeing in our projects. I'm not sure if it's just the size or perhaps a conflict with another dependency? There was no YouTrack issue created, it was a private ticket. I don't think there is too much to pass along other than "All freezes we've seen are at random places on file system read or write". It's mostly just trying to get logs and isolate the cause.

**Comment by murathazer** [comment]
Is there any progress about this issue? 

We've same problem. While writing code in java files which have Lombok annotations IDE  becomes laggy and unresponsive (v0.23-2018.3)

![sr](https://user-images.githubusercontent.com/507048/54524971-4265f680-4984-11e9-80f1-5f2894b33851.gif)

**Comment by mplushnikov** [comment]
@murathazer There was no big changes for this. Did you test it with 0.24 version too?

**Comment by murathazer** [comment]
@mplushnikov yes, i tried with the Intellij 2019.1.1 and Lombok Plugin v0.24-2018.3 but performance problem continues.

may issue be related with this? https://youtrack.jetbrains.com/issue/IDEA-207243

**Comment by peterpz1** [comment]
What are the plans for fix? This issue is really making IntelliJ with lombok work not possible (each click causes 5 sec freeze). I reported it here:
**https://youtrack.jetbrains.com/issue/IDEA-218273**

**Comment by mplushnikov** [comment]
@peterpz1 @murathazer @GMillerVarian Can you verify last version (0.26.2) of plugin for IntelliJ 2019.2? It contains some optimization and fixes for general caching. I'm intresting in any performance changes in your environment. Changed it something, is it better or badder?

**Comment by peterpz1** [comment]
Unfortunately this issue caused that I couldn't work with IJ at all. So I had to change computer. I don't know why but on some PC this issue is occurring, on some not. And now my environment isn't representative any more.

**Comment by mplushnikov** [comment]
Ok, will close it for now. Please retest with last plugin version 0.27 and feel free to open a new issue if it doesn't help...
