### ISSUE TITLE
Incorrect constructors appear in "Structure" when `@Value` and `@Builder`

### ISSUE THREAD

**Issue by kuporific** [mplushnikov/lombok-intellij-plugin#57]
Consider the following class

    @Value
    @Builder
    public class MyDataClass {
        Object o1;
        private Object o2;
        private final Object o3;
    }

If just `@Value` were used, a public, all args constructor is generated. However, since both `@Value` and `@Builder` are present, it generates an all args constructor with default access, and no public constructor is created. We can inspect this by running the following code:

    Arrays.stream(MyDataClass.class.getDeclaredConstructors())
            .forEach(System.out::println);

which outputs in the first case (`@Value` only)

    public MyDataClass(java.lang.String,long)

and in the second case (`@Value` and `@Builder`)

    MyDataClass(java.lang.String,long)

However, the "Structure" window in the IDE incorrectly shows two constructors (it's impossible to tell what their access levels are, but that's a separate issue):

![screen shot 2014-06-24 at 3 05 54 pm](https://cloud.githubusercontent.com/assets/4064195/3376206/a2af9a5a-fbd2-11e3-9dbd-8ea2870d7e9f.png)

This allows me to construct an instance of `MyDataClass` (in another package) in the IDE (but this fails on build).

**Comment by mplushnikov** [comment]
Version 0.9.0 of plugin is available now
