### ISSUE TITLE
`ConstructorProperties` in Delomboked code.

### ISSUE THREAD

**Issue by michielboekhoff** [mplushnikov/lombok-intellij-plugin#580]
### Short description
Say I have a class 

```
@RequiredArgsConstructor
@Getter
public class BookDto {
    private final String name;
}
```

then I expect a constructor to be generated, by default _without_ `@ConstructorProperties` (as the default for `lombok.anyConstructor.addConstructorProperties` is `false`). However, the `@ConstructorProperties` is always being shown.

### Expected behavior
Delombok constructors should add `@ConstructorProperties` if and only if this setting is enabled, as per `lombok.anyConstructor.addConstructorProperties` in lombok.config.

### Version information

 * **IDEA Version:** 
IntelliJ IDEA 2018.3.3 (Community Edition)
Build #IC-183.5153.38, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.15-300.fc29.x86_64
 * **JDK Version:**
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode, sharing)
 * **OS Type & Version:** 
I'm on Fedora 29.
 * **Lombok Plugin Version:** v0.23-2018.3
 * **Lombok Dependency Version:** 1.18.4

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Add `@RequiredArgsConstructor` on a class with final members.

**Comment by mplushnikov** [comment]
@michielboekhoff Yes, any help is welcome! Just submit your PR and I will look on it.

**Comment by bric3** [comment]
It doesn't understand `lombok.addLombokGeneratedAnnotation` either nor annotations like `lombok.copyableAnnotations += com.fasterxml.jackson.annotation.JsonFormat`

**Comment by michielboekhoff** [comment]
@bric3 - maybe we should create separate issues for those then? If it makes sense to you and would benefit your use-case.

**Comment by bric3** [comment]
@michielboekhoff Yes maybe. What do you think @mplushnikov. How would you like us to fill the issue. e.g. `lombok.addLombokGeneratedAnnotation` and `` seems related in term of feature / code. While `lombok.anyConstructor.addConstructorProperties` seems more complex. Or all properties are related as they are mostly about _delomboking_ code and should be in the same issue.

**Comment by mplushnikov** [comment]
@bric3 I would prefer to have separate issues or PRs for this. Smaller PR are easier to check and to integrate as a big one:)

**Comment by michielboekhoff** [comment]
@mplushnikov - I've been hacking away at this, and have got something that I think works (more or less). Problem is that the default has now been changed (as in, Lombok does not, by default, generate `@ConstructorProperties`) which is actually a backwards-incompatible change. I've assumed that the order is something like 

`suppressConstructorProperties` in `lombok.config` < `addConstructorProperties` < `suppressConstructorProperties` on the annotation. 

This change does, as a result, break some tests, but I've changed the expectations and am adding extra tests to cover for this set of configuration changes.

**Comment by mplushnikov** [comment]
@michielboekhoff Just make a PR so I can look on your code and play with it

**Comment by tangqiuyang** [comment]
very good

**Comment by tangqiuyang** [comment]
very good

**Comment by tangqiuyang** [comment]
very good

**Comment by tangqiuyang** [comment]
very good

**Comment by tangqiuyang** [comment]
very good

**Comment by tangqiuyang** [comment]
very good

**Comment by tangqiuyang** [comment]
very good

**Comment by tangqiuyang** [comment]
very good
