### ISSUE TITLE
IntelliJ 2019.1 EAP: Plugin not supported

### ISSUE THREAD

**Issue by kosi2801** [mplushnikov/lombok-intellij-plugin#583]
### Short description
IntelliJ 2019.1 EAP considers the Lombok Plugin not compatible and warns before updating.

### Expected behavior
Lombok Plugin should not show up as incompatible when updating to 2019.1 EAP

### Version information

 * **IDEA Version:** 2019.1 EAP 191.4214.41
 * **Lombok Plugin Version:** v0.23-2018.3

### Steps to reproduce
 1. Have IntelliJ 2018.x installed, have Lombok plugin installed
 2. Start IntelliJ Update dialog

### Additional Info
Screenshot of update dialog:
![auswahl_027](https://user-images.githubusercontent.com/1632470/51895052-905d7580-23a9-11e9-81a3-7e6c7c52ad3d.png)

**Comment by AlexByte** [comment]
In 2018.3.4 also

**Comment by mmoayyed** [comment]
I am not sure I understand the fix here: if the plugin version is declared as not compatible with IDEA, how could reinstalling it fix the issue and remove the warning? Or is there a fix available in 0.24 version of the plugin?

**Comment by AlexByte** [comment]
This error was displayed after importing settings.

**Comment by mplushnikov** [comment]
@mmoayyed 0.24 version will prevent Intellij to show this warning during update from 2018.3 to 2019.1
But you can also use existing plugin version -> ignore this warning-> update Intellij-> update plugins. This will install plugin marked as supported for 2019.1

**Comment by mmoayyed** [comment]
Thank you very much for clarifying this.

**Comment by DianaAlcantara** [comment]
I have a new laptop, downloaded this IntelliJ 2019.1, installed the lombok plugin 0.24, from scratch, and still it's getting disabled by Intellij. I will have to use the previous Intellij version in order to work.

**Comment by AlexByte** [comment]
@DianaAlcantara https://github.com/mplushnikov/lombok-intellij-plugin/issues/583#issuecomment-466990522

**Comment by AlexByte** [comment]
@DianaAlcantara try to reinstall the plugin.

**Comment by DianaAlcantara** [comment]
Thanks Alex, but I already removed and installed it again twice. I know the resinstalling the For now,  I'll try working with 2018.3.6. I plugin thing worked for one of my team mates who had the previous intellij and installed the new one: he had to remove and reinstall the plugin. In this case I'm starting with the 2019.1, no other intellij version was on this machine, and reinstalling it is not working.  For now I'm gonna use the old one, until this is solved. Thanks!

**Comment by AlexByte** [comment]
@DianaAlcantara This is already solved? create other issue.
