### ISSUE TITLE
 AccessLevel specfication not being respected for staticConstructorMethod by @RequiredArgsConstructor & @AllArgsConstructor

### ISSUE THREAD

**Issue by bhchandra** [mplushnikov/lombok-intellij-plugin#584]
### Short description

Here is an example class which should have the factory method `of` with private access.
 
```
@RequiredArgsConstructor(staticName = "of", access = PRIVATE)
public final class Assets {

    private final String pathName;

    public static Assets find(@NonNull String fileName) {
        try {
            return Assets.of(
                    Assets.class.getClassLoader().getResource(fileName).getPath()
            );
        } catch (NullPointerException ex) {
            throw new RuntimeException(new FileNotFoundException("\"" + fileName + "\""));
        }
    }
....
....
}
```

The factory method `of` has public access and can be accessed.

![untitled](https://user-images.githubusercontent.com/16656423/51938236-3b822500-23d2-11e9-94a2-e821a2c3eeae.png)

### Expected behavior
The generated static factory method `of` should have private access.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2018.3.4
 * **JDK Version:** JDK 8 1.8.0_191-b12
 * **OS Type & Version:** _Windows 10 updated.
 * **Lombok Plugin Version:** latest version available from marketplace. 0.23
 * **Lombok Dependency Version:** happens on both 1.18.2 & 1.18.4

### Steps to reproduce

 1. create a class with a field and mark it with @RequiredArgsConstructor(staticName = "of", access = PRIVATE)
 2. You can access the factory method `of` in another class.

### Additional information
Compilating with Maven throws a Comilation failure, at the usage of `Asserts.of()` with error message 
`error: of(String) has private  access in Assets`
This should mean that Lombok is working correctly.

**Comment by mplushnikov** [comment]
Thank you @bhchandra, This is really old bug, existing in code from the beginning:-)
