### ISSUE TITLE
New feature @FieldNameConstants(asEnum = true)

### ISSUE THREAD

**Issue by vyemialyanchyk** [mplushnikov/lombok-intellij-plugin#589]
This is feature request

### Short description
FieldNameConstants with asEnum is not working

### Expected behavior
All details are here:
"New features for @FieldNameConstants"
https://github.com/rzwitserloot/lombok/issues/1774

**Comment by mplushnikov** [comment]
@vyemialyanchyk This feature was already implemented for #547 and will be available in the next plugin release (0.24)

**Comment by FedyaLutkovski** [comment]
Hello. In the 24th version @FieldNameConstants still does not work as it should. Namely, I mean the parameter asEnum - it just does not work.
