### ISSUE TITLE
Constructor body context is not set properly

### ISSUE THREAD

**Issue by amaembo** [mplushnikov/lombok-intellij-plugin#593]
IntelliJ IDEA developer here.

In [AbstractConstructorClassProcessor](https://github.com/mplushnikov/lombok-intellij-plugin/blob/3d3bf77a2d2899ca50cfb28401c06cf5401fac4c/src/main/java/de/plushnikov/intellij/plugin/processor/clazz/constructor/AbstractConstructorClassProcessor.java#L295) you use
```
constructor.withBody(PsiMethodUtil.createCodeBlockFromText(blockText.toString(), psiClass));
```

Please try using `constructor` as the context instead of `psiClass`. This should make resolve within the constructor body working.

Why this matters?

Some IDEA inspections (e.g. Redundant assignment) analyze constructor bodies, including your generated constructor. While you generate it as `this.field = field;`, the context is set to the class, not to the constructor, thus right-hand `field` is not resolved to constructor parameter, but resolved to the field, so this assignment looks bogus to analyzer and it can make wrong conclusions.

Example:

```java
@AllArgsConstructor
public final class Test {
  private int age = 10; // this assignment should be marked as redundant
}
```

The field initialization should be marked as redundant, as the field is always reassigned in synthetic constructor. However inspection doesn't mark it, because it thinks that field is used in the constructor before assignment.

Note that I did not test whether my suggestion works, but in general all generated method bodies should have the corresponding method as the context.

**Comment by mplushnikov** [comment]
@amaembo Thank you Tagir! Didn't know full value of context. The next plugin build will contain your suggested fix.
