### ISSUE TITLE
Lombok imports and annotations displayed in red with intellij version 2018.3.5

### ISSUE THREAD

**Issue by vijayaalla** [mplushnikov/lombok-intellij-plugin#598]
### Short description
Lombok imports and annotations displayed in red with intellij version 2018.3.5. However no issue when running the tests/application

### Expected behavior
Intellij should not show Lombok imports and annotations in red as compilation problem when its not

### Version information

 * **IDEA Version:**  Intellij version 2018.3.5.
 * **JDK Version:** 1.8
 * **OS Type & Version:** Mac
 * **Lombok Plugin Version:** 0.23
 * **Lombok Dependency Version:** NA

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Install intellij version 2018.3.5
 2. Add Lombok plugin version 0.23
 3. Enable Annotation processing in intellij.
 4. Lombok imports and annotation displayed in RED.

**Comment by mplushnikov** [comment]
I think you just forgot to add lombok dependency. Please verify your setup. https://projectlombok.org/setup/overview

**Comment by vijayaalla** [comment]
Thanks for the response.

I have updated the org.projectlombok:lombok to v1.18.6 and issue resolved
