### ISSUE TITLE
val postfix completion  need be configurable

### ISSUE THREAD

**Issue by tldzyx** [mplushnikov/lombok-intellij-plugin#599]
### Short description
In my work team, most people think the **"lombok.val foo"** is more friendly for **write code** and the **"final $type"** is more friendly for **read code**, so we hop the **val** behavior like **var** just add the final key, and maybe **vall** like **varl** just for lombok.

### Expected behavior
the **val postfix completion** can be config, it's need help and support.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2018.3.5 (Community Edition)
 * **JDK Version:** 1.8.0_152-release-1343-b28 amd64
 * **OS Type & Version:** Windows 10 10.0
 * **Lombok Plugin Version:** 0.23-2018.3
 * **Lombok Dependency Version:** 1.18.6

### Sample project
1. if use **val**, then
``` java
public class Foo {
    void m(Object o) {
        String.valueOf(123).val
    }
} 
```
will to be
``` java
public class Foo {
    void m(Object o) {
        final String foo = String.valueOf(123);
    }
}
```
2. if use **vall**, then
``` java
public class Foo {
    void m(Object o) {
        String.valueOf(123).vall
    }
} 
```
will to be
``` java
public class Foo {
    void m(Object o) {
        lombok.val foo = String.valueOf(123);
    }
}
```

**Comment by mplushnikov** [comment]
What is your expections? Waht do you like to configure? At the moment lombok plugin already provides two postfix complition: "varl" for lombok.var and "val" for lombok.val.
There is currently a bug #617, maybe you have same dissiculties?

**Comment by mplushnikov** [comment]
closed as no feedback provided
