### ISSUE TITLE
Plugin incompatible with the new build found: Lombok Plugin --- IDEA 2019.1 UPDATE

### ISSUE THREAD

**Issue by smalints** [mplushnikov/lombok-intellij-plugin#603]
<img width="1346" alt="IDEA 2019.1" src="https://user-images.githubusercontent.com/19852104/55106001-45c95280-50e7-11e9-9142-71485d6a51ef.png">

**Comment by ruurd** [comment]
Update anyway then immediately update plugins which will load the Lombok plugin marked compatible with 2019.1

**Comment by hcl04** [comment]
Sorry, because of my net , i can not check update of this plugin in the market. 
So can you tell me  where i can download it directly ?

**Comment by davichi11** [comment]
> Sorry, because of my net , i can not check update of this plugin in the market.
> So can you tell me where i can download it directly ?

更新还没出来 我退回到2018.3.6了

**Comment by hcl04** [comment]
> > Sorry, because of my net , i can not check update of this plugin in the market.
> > So can you tell me where i can download it directly ?
> 
> 更新还没出来 我退回到2018.3.6了

我在 Realease 中找到了 ：[0.23-EAP](https://github.com/mplushnikov/lombok-intellij-plugin/releases/download/releasebuild_0.23/lombok-plugin-0.23-EAP.zip)

**Comment by davichi11** [comment]
> > > Sorry, because of my net , i can not check update of this plugin in the market.
> > > So can you tell me where i can download it directly ?
> > 
> > 
> > 更新还没出来 我退回到2018.3.6了
> 
> 我在 Release 中找到了 ：[0.23-EAP](https://github.com/mplushnikov/lombok-intellij-plugin/releases/download/releasebuild_0.23/lombok-plugin-0.23-EAP.zip)

看来还是不是正式版,jetbrain的插件市场没有最新的,无奈

**Comment by myifeng** [comment]
It is now possible to update the Lombok plug-in version to 0.23-EAP in IDEA, adapting to IDEA version 2019.1. @davichi11

**Comment by smalints** [comment]
After update IDEA -> update Lombok.
