### ISSUE TITLE
it is not work with  idea 2019.1

### ISSUE THREAD

**Issue by Viking1726** [mplushnikov/lombok-intellij-plugin#604]
![image](https://user-images.githubusercontent.com/30591576/55142093-c6835f80-5176-11e9-90a8-c7ec2cd506ce.png)

**Comment by myifeng** [comment]
It is now possible to update the Lombok plug-in version to 0.23-EAP in IDEA, adapting to IDEA version 2019.1.

**Comment by AndyRubio** [comment]
@myifeng can you provide some detail on how to do this?

**Comment by markoandersson** [comment]
@AndyRubio Just update IDEA and you can then update the plugin. See https://github.com/mplushnikov/lombok-intellij-plugin/issues/603

**Comment by Viking1726** [comment]
![image](https://user-images.githubusercontent.com/30591576/55203330-e746c600-5205-11e9-8699-b7c6525b3589.png)

thank guys
