### ISSUE TITLE
Constants generated with @FieldNameConstants are in lower camel case

### ISSUE THREAD

**Issue by oleksandr-bilous** [mplushnikov/lombok-intellij-plugin#609]
### Short description
@FieldNameConstants generates an inner type with string constants in a lower camel case.  Doesn't depend on asEnum() is true or false.

### Expected behavior
According to [Google's java style guide](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names) :

> Constant names use CONSTANT_CASE: all uppercase letters, with each word separated from the next by a single underscore.

[Oracle's java language specification](https://docs.oracle.com/javase/specs/jls/se8/html/jls-6.html#jls-6.2) says:

>Constant names normally have no lowercase letters ...

### Version information

 * **IDEA Version:** IntelliJ IDEA 2019.1 (Ultimate Edition). Build 191.6183.87
 * **JDK Version:** 1.8.0_202
 * **OS Type & Version:** Windows 8.1
 * **Lombok Plugin Version:** 0.24
 * **Lombok Dependency Version:** 1.18.6

### Sample
![image](https://user-images.githubusercontent.com/30628706/55401221-c4474980-5558-11e9-97f7-5bb345593d26.png)

**Comment by vrosenshtein** [comment]
Hi. I have the same issue in the same environment.
I understand that FieldNameConstants is experimental feature, nevertheless it am widely using it in my project - about 200 classes annotated with FieldNameConstants. Switching from upper case constant names to lower case is big surprise for me.

Proposed solution is to let user decide what code style to use. Also, as @oleksandr-bilous mentioned it is common practice to use upper case names and I believe this behavior should be enabled by default.

**Comment by mplushnikov** [comment]
Look at this issue: https://github.com/rzwitserloot/lombok/issues/1942
Lombok project use same case as used for fieldnames....

**Comment by vrosenshtein** [comment]
Sorry guys, but this is quite ugly solution.
Even if we have different naming conventions, we should **support most widely used one by default** and probably have some options to adapt to less widely used.
I like Lombok, it really makes my life easier and for my colleagues as well, but now I am quite disappointed.

**Comment by mplushnikov** [comment]
Please open new issue in project lombok: https://github.com/rzwitserloot/lombok/issues to handle it. If this will be changed by lombok, I'l be able to change this in plugin.
