### ISSUE TITLE
When using @Builder the builder class is not visible

### ISSUE THREAD

**Issue by robertandrewbain** [mplushnikov/lombok-intellij-plugin#610]
### Short description
Given a class named, E.G. `Foo` annotated with `@Builder` importing `Foo.FooBuilder` in another class fails with "java: cannot find symbol".
### Expected behavior
Importing `Foo.FooBuilder` should "just work".

### Version information

 * **IDEA Version:**
IntelliJ IDEA 2019.1 (Community Edition)
Build #IC-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 * **JDK Version:** 
openjdk 12 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)
 * **OS Type & Version:**
macOS 10.14.3
 * **Lombok Plugin Version:**
v0.24-2018.3
 * **Lombok Dependency Version:** 
1.18.6
### Steps to reproduce

 1. Create a class named, E.G. `Foo`, annotated with `@Builder`
 2. Create another class and import `Foo.FooBuilder`
 3. Build the project

**Comment by mplushnikov** [comment]
Unfortunatly, this error comes from javac. Nothing that plugin can handle. It looks like lombok didn't run properly or you got a case descibed here: https://github.com/rzwitserloot/lombok/issues/2044

**Comment by adispenza** [comment]
In case anyone googles their way here as I did, I solved this by downgrading to IntelliJ 2018.3.6 with the corresponding version of this plugin.

**Comment by robertandrewbain** [comment]
Incidentally, I solved by removing the static imports and importing non static and calling, E.G. `Foo.builder()`

**Comment by manuelwallrapp** [comment]
I have the same issue with Intellij Idea 2022.3, if I downgrade to 2022.2, it works.
