### ISSUE TITLE
Error in @Singular handling

### ISSUE THREAD

**Issue by robertandrewbain** [mplushnikov/lombok-intellij-plugin#612]
### Short description
Given a class named, E.G. `Foo` annotated with `@Builder` and a field annotated with `@Singular` E.G. `@Singular private final List<String> strings`, Intellij reports an error saying Error:java: Lombok annotation handler class lombok.javac.handlers.HandleBuilder failed on Foo.java: java.lang.IllegalStateException: Lombok TreeMaker frontend issue: no match when looking for method: com.sun.tools.javac.tree.JCTree$JCBreak com.sun.tools.javac.tree.TreeMaker.Break(com.sun.tools.javac.util.Name)
### Version information

 * **IDEA Version:**
IntelliJ IDEA 2019.1 (Community Edition)
Build #IC-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 * **JDK Version:** 
openjdk 12 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)
 * **OS Type & Version:**
macOS 10.14.3
 * **Lombok Plugin Version:**
v0.24-2018.3
 * **Lombok Dependency Version:** 
1.18.6
### Steps to reproduce

 1. Create a class named, E.G. `Foo`, annotated with `@Builder`
 2. Create a field annotated with `@Singular` E.G. `@Singular private final List<String> strings`
 3. Build the project

**Comment by mplushnikov** [comment]
This is problem of project lombok. (like here: https://github.com/rzwitserloot/lombok/issues/1888) not of the plugin.

**Comment by robertandrewbain** [comment]
@mplushnikov I did come across this lombok issue, however I thought Lombok Plugin Version v0.24-2018.3 used Lombok 1.18.6, in which the issue is fixed?
