### ISSUE TITLE
plugin issue with  IntelliJ

### ISSUE THREAD

**Issue by ashutoshcp** [mplushnikov/lombok-intellij-plugin#615]
### Short description
Compilation Error of incompatible types: java.lang.String cannot be converted to lombok.val
E.g: val baseUrl = env.getProperty("somevalue");
### Expected behavior
It should compile properly.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2019.1 (Ultimate Edition) Build #IU-191.6183.87, built on March 27, 2019

 * **JDK Version:** : JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 * **OS Type & Version:** macOS 10.14.4
 * **Lombok Plugin Version:** v0.24-2018.3
 * **Lombok Dependency Version:** 1.18.4

**Comment by mplushnikov** [comment]
Do you have some example project to reproduce this? I think you have misconfigured your project, it look like lombok is not on the classpath during compilation.

**Comment by ashutoshcp** [comment]
Thanks @mplushnikov , Resolved this. After enabling annotation Processor it worked. 
 [
<img width="1283" alt="Screenshot 2019-04-10 at 2 52 16 PM" src="https://user-images.githubusercontent.com/10486922/55867544-51fde700-5ba0-11e9-92b7-1f7c77dfe3d9.png">
](url)

**Comment by ashutoshcp** [comment]
Thanks
