### ISSUE TITLE
Can't add new 'Java Postfix Completion shortcut' and upon failure old custom shortcuts are also lost.

### ISSUE THREAD

**Issue by spaceCamel** [mplushnikov/lombok-intellij-plugin#617]
### Short description

When the Lombok plugin is installed I can't add new 'Java Postfix Completion' shortcuts.
 
### Expected behavior

Open IntelliJ preferences. Go to 'Editor -> General -> Postfix Completion'. Click on the `+` sign and select `Java`.

<img width="1320" alt="Screenshot 2019-04-09 at 16 02 51" src="https://user-images.githubusercontent.com/97157/55813760-44375b80-5ae5-11e9-95bc-0c9373434d17.png">

Configure the new shortcut for a 'non primitive type' (language level doesn't seem to matter, anyway I've used Java 6).

<img width="541" alt="Screenshot 2019-04-09 at 16 05 18" src="https://user-images.githubusercontent.com/97157/55813889-7648bd80-5ae5-11e9-8cba-afb25d5f3dd7.png">

Click 'OK' on 'Create new Java Template' window. Click 'Apply' or 'OK' on the 'Preferences' window.

The new setting is applied.

### Version information

* **From 'About IntelliJ IDEA':**

```
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
```

 * **Lombok Plugin Version:** `v0.24-2018.3`
 * **Lombok Dependency Version:** `1.18.6`

### Steps to reproduce

 1. Install / Launch the IntelliJ IDEA version as above (without Lombok plugin activated)
 2. Add a 'Postfix Completion' short cut for Java as described in Expected behaviour (i.e. associate `.foo` with `foo($EXPR$)`)
 3. Confirm all changes by clicking 'OK'/'Apply'
3. create a new Gradle project
4. try the newly added shortcut (i.e. `myVar.foo<TAB>` should result in `foo(myVar)`)
5. Add Lombok plugin to your project
6. Add a new 'Postfix Completion' short cut for Java as described in Expected behaviour (i.e. associate `bar` with `bar($EXPR$)`)
7. Click 'Apply' in the 'Preferences' window. You'll see that the button does not deactivate (the changes are not applied). If you click 'OK' at this point or even instead of clicking 'Apply', the preferences window will close and neither `.foo` nor `.bar` shortcuts will be working anymore.
8. If you open the 'Postfix Completions' settings again you'll see that both 'foo' and 'bar' configuration have disappeared.

### Sample project

Please, let me know if you need a sample project in the comments and I'll add one.

### Additional information

No errors are present in IntelliJ's event log.

This issue seems related with #497, but as you can see in the screenshot above, both 'Java' and 'Lombok' are visible in the 'new postfix completion' menu (`+` sign)

**Comment by NekoCaffeine** [comment]
I have been troubled by this

**Comment by spaceCamel** [comment]
I've also reproduced the issue with the following configuration:

```
IntelliJ IDEA 2018.3.3 (Ultimate Edition)
Build #IU-183.5153.38, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-46-generic
lombok v0.24-2018.3
```

**Comment by spaceCamel** [comment]
A workaround if you want to add a 'Postfix Completion' is:

1. disable Lombok plugin and restart IntelliJ
2. add the shortcut
3. re-enable Lombok plugin
4. restart IntelliJ

Note that the shortcuts will now appear duplicated in the drop-down menu, but they'll work whatever you choose.

<img width="599" alt="Screenshot 2019-04-09 at 16 57 57" src="https://user-images.githubusercontent.com/97157/55815707-ab0a4400-5ae8-11e9-87eb-65cc377910ec.png">

**Comment by zolotov** [comment]
@mplushnikov it's ok to extend `JavaPostfixTemplateProvider`, just override `getId`, so native Java-templates won't use your provider for deserializing.
