### ISSUE TITLE
ToString.Exclude and @EqualsAndHashCode.Exclude are not resolved in IntelliJ

### ISSUE THREAD

**Issue by rama-coder** [mplushnikov/lombok-intellij-plugin#625]
My IntelliJ is able to resolve @ToString and @EqualsAndHashCode but its UNABLE to resolve @ToString.Exclude and @EqualsAndHashCode.Exclude annotations.

I am using IntelliJ community edition latest version and using lombok 0.24-2017.2. Tried getting latest lombok but I could not get more later than 0.24-2017.2. Can someone help to resolve this issue?

**Comment by mplushnikov** [comment]
Please verify version of your lombok dependency in your pom.xml or build.gradle file. You need both: plugin for Intellij and lombok jar in your project.
