### ISSUE TITLE
Add support for lombok.fieldNameConstants.uppercase = true from lombok 1.18.8

### ISSUE THREAD

**Issue by mplushnikov** [mplushnikov/lombok-intellij-plugin#629]
Add support for lombok.fieldNameConstants.uppercase = true from lombok 1.18.8

See: https://projectlombok.org/changelog

**Comment by alanachtenberg** [comment]
Lombok units
[before](https://github.com/rzwitserloot/lombok/blob/bf0499263b05e11fdd43886df3dc5663c8fee5f4/test/transform/resource/before/FieldNameConstantsUppercased.java)
[after delombok](https://github.com/rzwitserloot/lombok/blob/bf0499263b05e11fdd43886df3dc5663c8fee5f4/test/transform/resource/after-delombok/FieldNameConstantsUppercased.java)

Should probably just be able to call same method camelCaseToConstant in
[HandlerUtil](https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/core/handlers/HandlerUtil.java)
