### ISSUE TITLE
lombok.fieldNameConstants.uppercase = true not working

### ISSUE THREAD

**Issue by monkeydp** [mplushnikov/lombok-intellij-plugin#640]
### Short description
I set l`ombok.fieldNameConstants.uppercase = true` not work
But other property like `lombok.accessors.chain` work well

### Expected behavior
```
public class MainTest {
    
    @Test
    public void test() {
        // Expected here refer to `MY_NAME`, but get `myName` in idea
        String name = User.Fields.MY_NAME;
    }

    @FieldNameConstants
    static class User {
        private String myName;
    }
}
```

### Version information

 * **IDEA Version:** 2018.3
 * **JDK Version:** 1.8.0_151
 * **OS Type & Version:** Win10 1809 (OS inner version 17763.503)
 * **Lombok Plugin Version:** v0.25
 * **Lombok Dependency Version:** 1.18.8

**Comment by mplushnikov** [comment]
Yes, this is not implemented in the moment. See: https://github.com/mplushnikov/lombok-intellij-plugin/issues/629
