### ISSUE TITLE
IDEA 2019.2 highlights builder() method invocation as an error

### ISSUE THREAD

**Issue by remal** [mplushnikov/lombok-intellij-plugin#648]
### Short description
`builder()` method usage causes a warning message:
```
Cannot access CustomerDto.CustomerDtoBuilder
```

### Expected behavior
The IDEA warning message should not appear.

### Version information

 * **IDEA Version:** IDEA 2019.2 (Ultimate Edition)
 * **JDK Version:** 1.8
 * **OS Type & Version:** Windows 10
 * **Lombok Plugin Version:** 0.25-2019.1
 * **Lombok Dependency Version:** 1.18.8

### Steps to reproduce
```java
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
@FieldDefaults(level = PRIVATE)
public class CustomerDto {
    String id;
    String firstName;
}
```
![screen](https://user-images.githubusercontent.com/231188/61817979-77191b80-ae58-11e9-818c-130ad10ecd8b.png)

**Comment by bfx** [comment]
I'v just updated intellij and faced this problem

**Comment by zxxz** [comment]
+1 I am also experiencing the same issue... is there a workaround?

**Comment by arthurzwl** [comment]
+1 same issue

**Comment by temofey1989** [comment]
+1

**Comment by temofey1989** [comment]
Nop... After some time it appears again. :D

**Comment by temofey1989** [comment]
Ok, disabling and enabling Lombok Plugin (with IDEA restarts) fixed this problem for me.

**Comment by massfords** [comment]
> Ok, disabling and enabling Lombok Plugin (with IDEA restarts) fixed this problem for me.

Seemed to work for me as well but the errors are back

**Comment by Bluecodelf** [comment]
+1, affected by this as well.
Seems related to #637. Looking at the logs provide a `Non-idempotent computation` on the builder class.

**Comment by kishorekolli** [comment]
+1 seeing this issue with 2019.2 update

**Comment by ajukes** [comment]
+1 seeing same issue

**Comment by padreati** [comment]
+1 same issue on 2019.2; various fixes seems to work but after some amount of time it appears again

**Comment by yohanndumais** [comment]
+1 same issue

**Comment by antonbashir** [comment]
+1 same issue

**Comment by fr1kin** [comment]
OPs example doesn't error for me, but I do get an error like what @Bluecodelf shows. It's caused by the `@Singular` annotation and removing it fixes any builder errors intelliJ flagged. I think the error is being thrown from [here](https://github.com/JetBrains/intellij-community/blob/master/platform/core-impl/src/com/intellij/util/IdempotenceChecker.java#L233). Pretty annoying bug, but the build still compiles and intellisense autocomplete still works as well.

**Comment by thomasdac** [comment]
Hi guys.. I had the same issue, but it disappears when I change the Lombok dependency from compileOnly to compile in build.gradle.

**Comment by fabiocvalente** [comment]
+1 same issue

**Comment by subanasif** [comment]
Removing @Singular annotation worked for me. However I do want @Singular annotation in my class. Its a bug in the plugin.

**Comment by tifoha** [comment]
There is a bug with plugin. When you add @Singular annotation to Collection field Idea begins to complain on static builder() method.
Please fix that.

**Comment by sziszo** [comment]
+1 same issue. If I set the value property of the @Singular annotation then Idea didn't complain. Please fix it.

**Comment by subanasif** [comment]
The problem also goes away if you use @Singular("foo") instead of just @Singular on property called "foo". Its a workaround. The bug is definitely present.

**Comment by fabiocvalente** [comment]
I am already using **@Singular("...")**. In my case the property name is in plural and I used singular in the annotation value like:
```
@Singular("prop")
private List<String> props
```
I changed to use the annotation value exactly as the property name like bellow, but still got the same problem.
```
@Singular("props")
private List<String> props
```
The only way to remove the error is to remove **Singular** annotation.

**Comment by mplushnikov** [comment]
Looks like new check for internal caches made by Intellij in 2019.2 breaks parts of @Singular implementation in the plugin :-( Have to investigate it deeper...

**Comment by gskaplan** [comment]
My experience is the same - if I remove @Singular, the errors go away, but I've come to love that annotation. Hope this gets fixed soon because I've postponed updating IntelliJ until it is.

**Comment by mplushnikov** [comment]
Hello everyone!
Can you please test this build (Only Intellij 2019.2 and hiher) of plugin: https://github.com/mplushnikov/lombok-intellij-plugin/releases/download/0.26.alpha/lombok-plugin-0.26-2019.2.jar
You have to install it manually: Settings->Plugins->Install Plugin from Disk... 

It contains some fixes for general caching. Does it fix you issue in your environment?

**Comment by MicNeo** [comment]
@mplushnikov hey, I just tested it. It looks good. I don't see this error anymore.

**Comment by gskaplan** [comment]
Works for me. Thank you.

**Comment by kishorekolli** [comment]
Works for me as well. Thank you.

**Comment by antonbashir** [comment]
Works for me as well. Thank you.

**Comment by dkorobtsov** [comment]
Works just fine, thanks!

**Comment by mplushnikov** [comment]
Thank you very much for testing!

**Comment by mplushnikov** [comment]
Just released new plugin version (0.26.2) for IntelliJ 2019.2+

**Comment by rt-krz** [comment]
After an update I started experiencing this issue in my project. I see in assets you have to zips:
lombok-plugin-0.26.2-2019.2.1.zip
lombok-plugin-0.26.2-2019.2.zip
Which is actually right one?
Are you sure that you published to marketplace the right version?

**Comment by rt-krz** [comment]
After manual update to `lombok-plugin-0.26.2-2019.2.1.zip` I needed to run `Invalidate Cache and Restart` in IntelliJ and after that it worked again as usual.

**Comment by jbee** [comment]
Look like the issue is back in 2020.03 with plugin 0.32-EAP

**Comment by NoahNyy** [comment]
Android Studio 4.1.2 with plugin 0.34-2020.1 occurs.
Workaround still is Invalidate Cache and Restart.
