### ISSUE TITLE
@Data annotation bug with constructors

### ISSUE THREAD

**Issue by XinAnzzZ** [mplushnikov/lombok-intellij-plugin#653]
### Short description
I don't know how to clearly describe my problem beacause my terrible language expression.
please look the code:

```java

@Data
public class LombokTest {
    private String username;
    private String password;

    public LombokTest(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public static void main(String[] args) {
        // compile success, but lombok for idea plugin show error
        System.out.println(new LombokTest());
    }
}

```

### Expected behavior

@Data include @RequiredArgsConstructor，so it will create noArgConstructor in this test case，so the code will compile success and run normally, but the plugin show the err, so I think it's a bug in the plugin.

![image](https://user-images.githubusercontent.com/38024683/62454180-6fd20600-b7a6-11e9-844d-42eb747ff4a7.png)

### Version information

 * **IDEA Version:** 2019.1.1(ultimate edition)
 * **JDK Version:** JDK 8
 * **OS Type & Version:** macos Mojave 10.14.6
 * **Lombok Plugin Version:** v 0.25 - 2019.1
 * **Lombok Dependency Version:** 1.16.22

### Steps to reproduce

just paste the code into idea editor and run it. It will run successful but idea will show error warning.

```java
@Data
public class LombokTest {

    private String username;

    private String password;

    public LombokTest(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public static void main(String[] args) {
        System.out.println(new LombokTest());
    }
}
```

### Additional information

I'm sorry about my terriable language expression, I am Chinese, so my english not so good.

**Comment by alanachtenberg** [comment]
> @DaTa include @RequiredArgsConstructor，so it will create noArgConstructor in this test case
This is simply incorrect.
No args constructor is not part of @Data annotation. You would need to add it explicitly.

Probably it compiles because your compiler is missing the annotation processing step for lombok. As that code would compile without processing of @Data.
Try adding call to setUsername or setPassword and see if it still compiles.

**Comment by XinAnzzZ** [comment]
@alanachtenberg  Hi, Thanks for your response.
> This is simply incorrect.
Please look at the class file decoded by Idea
![image](https://user-images.githubusercontent.com/38024683/62615168-5e703180-b93f-11e9-96ff-25e63bf9463f.png)
actually, I will generated no args constructor even though I haven't add @NoArgsConstructor.

**Comment by alanachtenberg** [comment]
Apologies i was not aware they changed lombok to also generate a **private** constructor.
Still i think just adding @NoArgsConstructor should resolve it.

**Comment by mplushnikov** [comment]
@XinAnzzZ You are using pretty old version of lombok (1.6.22)

In this version lombok introduced a new "FEATURE: Private no-args constructor for @Data and @Value to enable deserialization frameworks (like Jackson) to operate out-of-the-box. Use lombok.noArgsConstructor.extraPrivate = false to disable this behavior."

But from the next version (1.18.0) lombok made "BREAKING CHANGE: The in 1.16.22 introduced configuration key lombok.noArgsConstructor.extraPrivate is now false by default. "

This lombok plugin for Intellij supports only new behavior. 

My suggestion is to update your lombok dependency and to use @NoArgsConstructor for example to achieve what you want.
