### ISSUE TITLE
Performance problems with IDEA 2018.3/2019.2 in autocomplete/code analysis

### ISSUE THREAD

**Issue by u62-warden** [mplushnikov/lombok-intellij-plugin#660]
### Short description
Severe delay in autocomplete and code analysis in a midsize (5000 classes) project.
WIth IDEA 2018.3 and 2019.2. Could be mended by deactivation Lombok (after getting a hint in the activity monitor of IDEA).

### Expected behavior
Quick and fast, how we want our editors.

### Version information

 * **IDEA Version:** 2019.2
 * **JDK Version:** 1.8.0_71-b15
 * **OS Type & Version:** MacOS Mojave 10.14.5
 * **Lombok Plugin Version:** 0.25-EAP
 * **Lombok Dependency Version:** _What version of lombok.jar are you using?_

### Steps to reproduce
Project size 5000 classes, 40 Maven subprojects.
Lombok annotations are used on around 50 classes.
As the project involves Cobol-Java transformation (semiautomated) we sometimes start with a Java class ~1000 Loc and several hundred errors, which are quickly corrected by introducing parameters etc. Autocomplete is very sluggish and sometimes I can type ahead half a line before Idea shows me the result. Also, inspections are slow.

I started the activity monitor and then saw the Lombok plugin hitting second place behind JIT, sometimes first place. Deactivation helped, now the response time is back to normal.

### Sample project
Can't really include our client project here.

### Additional information
If you tell me how I am willing to participate in providing trace/evidence.

### Stacktrace
none

**Comment by u62-warden** [comment]
Is probably related to: https://github.com/mplushnikov/lombok-intellij-plugin/issues/568

**Comment by u62-warden** [comment]
I can confirm that this is only related to Mac OS. Project staff with IDEA (2019) on Windows do not have that problem.

**Comment by mplushnikov** [comment]
@u62-warden Can you please describe which lombok features are you using? Lombok annotations, lombok.config properties for example...

**Comment by u62-warden** [comment]
We use Lombok annotations only:
Data, Getter (+AccessLevel), Setter, ToString mostly
EqualsAndHashCode, NoArgsConstructor, RequiredArgsConstructor

**Comment by u62-warden** [comment]
Sorry, wrongly closed.

**Comment by mplushnikov** [comment]
@u62-warden can you please test this build (Only Intellij 2019.2 and hiher) of plugin: https://github.com/mplushnikov/lombok-intellij-plugin/releases/download/0.26.alpha/lombok-plugin-0.26-2019.2.jar
It contains some fixes for general caching. I'm intresting in any performance changes in your environment. Changed it something, is it better or badder?

**Comment by u62-warden** [comment]
It seems to have helped with the issue. I will evaluate further, but the performance really has improved. Autocomplete is fast, Inspections seem to take a little longer than without the plugin but that is highly subjective. So it is much better, definitively.
Thanks, Michail

**Comment by mplushnikov** [comment]
Thank you @u62-warden for feedback! I'll close this issue now, feel free to open a new one, if you find out new problems!
