### ISSUE TITLE
Itellij idea 2019.2 lombok 0.25-EAP AllArgsConstructor annotation on enum class doesn't work

### ISSUE THREAD

**Issue by wdmcygah** [mplushnikov/lombok-intellij-plugin#661]
mac system 
Itellij idea 2019.2 
lombok 0.25-EAP 
gradle build

problem: a enum class uses AllArgsConstructor annotation, but complile error,  uses Getter annotation is ok, it seems AllArgsConstructor doesn't work

**Comment by mplushnikov** [comment]
I think this is some kind of aftereffect of issue #648 . Close this as duplicate.
