### ISSUE TITLE
Can Intellij recognize custom annotations for Lombok's extension?

### ISSUE THREAD

**Issue by Frodez** [mplushnikov/lombok-intellij-plugin#666]
### Short description
I'm striving for Lombok's extension. If I add some custom annotations, can Intellij and the plugin recognize them?

### Expected behavior
Some guidelines for Lombok's extension on Intellij(especially with the plugin).

### Version information

 * **IDEA Version:** 2019.2
 * **JDK Version:** OpenJDK12.0.1
 * **OS Type & Version:** windows 10
 * **Lombok Plugin Version:** 0.26.2-2019.2
 * **Lombok Dependency Version:** 1.18.8 or later

**Comment by mplushnikov** [comment]
Unfortunately not. You need to implement your custom support for your annotations. But you can use my plugin as base for it. What do you plan to do?

**Comment by Frodez** [comment]
> Unfortunately not. You need to implement your custom support for your annotations. But you can use my plugin as base for it. What do you plan to do?

Thank you very much.
My coding level is poor. Maybe i will support Eclipse first(only modification of Lombok.jar need), and then i can think of the support on Intellij.

**Comment by Anthwine** [comment]
> Unfortunately not. You need to implement your custom support for your annotations. But you can use my plugin as base for it. What do you plan to do?

Hello, How i can do that ? I need do a copy/past of @Setter but with @SaveSetter
