### ISSUE TITLE
lombok.builder.className config which is added in 1.18.10 is not supported

### ISSUE THREAD

**Issue by yasserg** [mplushnikov/lombok-intellij-plugin#680]
### Short description
Since 1.18.10 Lombok allows configuring default class name for builder classes. See `lombok.builder.className` in https://projectlombok.org/features/Builder but it doesn't seem to be supported in the plugin.

### Version information
 * **IDEA Version:** 2019.2.3
 * **JDK Version:** 1.8.0_212
 * **Lombok Plugin Version:** 0.27-2019.2
 * **Lombok Dependency Version:** 1.18.10

**Comment by mplushnikov** [comment]
Will be available in the next release of plugin: 0.29+
