### ISSUE TITLE
@JsonPOJOBuilder annotated builder incorrect Access warning

### ISSUE THREAD

**Issue by monowai** [mplushnikov/lombok-intellij-plugin#690]
### Short description
Annotating an inner class with @JsonPOJOBuilder to support serialization, IJ will incorrectly suggest `Access can be package private` even if the builder is in use outside of the package

### Expected behavior
No suggestion is required by IJ

### Version information
 * **IDEA 2019.2.3** 
 * **OpenJDK 11.0.2** 
 * **OSX Catalina** 
 * **Lombok Plugin Version: 0.27-2019.2** 
 * **Lombok Dependency Version: 1.18.6** 

### Steps to reproduce
Example
```
package com.project.model;
..
@Data
@Builder
@JsonDeserialize(builder = DateValues.DateValuesBuilder.class)
public class DateValues {
  private String opened;
  private String closed;

  @JsonPOJOBuilder(withPrefix = "")
  // public should not be reported as a problem as it is being used in the Test class
  **public** static class DateValuesBuilder {

  }
}
```
Test class is using the builder
```
package test.project.common
...
    DateValues dateValues = DateValues.builder()
        .opened(dateUtils.today())
        .closed(dateUtils.today())
        .build();
```

**Comment by lppedd** [comment]
@monowai eventually you could suppress if annotated with `JsonPOJOBuilder`.
![image](https://user-images.githubusercontent.com/19871649/71264990-8f2c9280-2345-11ea-9394-fe54d28458f6.png)

**Comment by lppedd** [comment]
Have you tried with IDEA 2019.3.*?

**Comment by monowai** [comment]
This is no longer a problem.  Thanks!
