### ISSUE TITLE
Do not support IntelliJ IDEA 2.4

### ISSUE THREAD

**Issue by ivansong92** [mplushnikov/lombok-intellij-plugin#698]
Your latest release version is 2.3, however the IDEA latest version is 2.4.When I use the latest IDEA, the plugin is not working very well

**Comment by CorwinNewall** [comment]
This affects me too: 2019.2.4 shows a lot of errors in the editor that don't occur when actually building a project with Lombok use. It was fine before updating Intellij and lombok-intellij-plugin from the previous versions.
![image](https://user-images.githubusercontent.com/25069619/68091735-69a80e80-fee8-11e9-87d1-d1d92086d54b.png)

**Comment by sasik-github** [comment]
I have the same issue, after upgrade to newer Idea version

IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019
Runtime version: 11.0.4+10-b304.77 x86_64
macOS 10.15

**Comment by MasterShu** [comment]
> I also have this problem.

```
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019
Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

**Comment by sasik-github** [comment]
Today I have got an update of Lombok plugin. Everything is fine. Thank you.

**Comment by schrek1** [comment]
Yes with 2.4 version is some problem, becouse when it's enabled, intellij not highlight syntax in files, but when I disable lombok plugin it works...

**Comment by Wadeqin** [comment]
Try add  “plugins{id 'io.franzbecker.gradle-lombok' version '3.2.0'}” and "repositories {jcenter() mavenCentral()}", it works for me.

**Comment by mplushnikov** [comment]
duplicate #711 711
