### ISSUE TITLE
0.27-2019.2 regression in constructor processing relating to deserialization

### ISSUE THREAD

**Issue by buddyp450** [mplushnikov/lombok-intellij-plugin#699]
### Short description
Unable to deserialize jackson objects when running 0.27-2019.2 version of Lombok Plugin

### Expected behavior
Expected the lombok plugin to not have different annotation processor handling than the actual lombok annotation processing

### Version information

 * **IDEA Version:** 2019.2.4
 * **JDK Version:** 1.8.0_221
 * **OS Type & Version:** Mac OSX 10.14.5 
* **Lombok Plugin Version:** 0.27-2019.2
 * **Lombok Dependency Version:** 1.18.10

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Invoke `FilterChain.doFilter` on a request object containing a jackson object without any constructors - using the builder pattern.

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
Can confirm that everything works as expected on the previous lombok plugin version.

Workaround is to add the `@AllArgsConstructor` and `@NoArgsConstructor` annotations to the top of my class file.

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```
...
nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.myorg.MyObject` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (PushbackInputStream); line: 1, column: 381] (through reference chain: com.myorg.mynamespace.SomeRequest["someThing"]->java.util.ArrayList[0])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:242)
...
```

**Comment by mplushnikov** [comment]
Verify version of lombok library and configuration you are using. Plugin doesn't generate any code for runtime. https://stackoverflow.com/a/51465038
