### ISSUE TITLE
Do not support IntelliJ IDEA 2.3

### ISSUE THREAD

**Issue by warthur1214** [mplushnikov/lombok-intellij-plugin#701]
Intellij IDEA：2019.2.3
Lombok Plugin: 0.27-2019.2
Lombok：1.18.8

My Data Class:
```ruby
@EqualsAndHashCode(callSuper = true)
@Data
public class RobotTaskParam extends BasePageParam
```

When I switched my git branches, I coudn't import class:
![image](https://user-images.githubusercontent.com/13415982/68193147-84b07680-ffed-11e9-9999-66abf7e639f9.png)

After removed @EqualsAndHashCode annotation,It worked.

**Comment by mplushnikov** [comment]
I think you have some issues with your installation. Try to reinport your project and/or trigger cache invalidation in Intellij.
