### ISSUE TITLE
Support @CustomLog added in 1.18.10 is not supported

### ISSUE THREAD

**Issue by denny2000** [mplushnikov/lombok-intellij-plugin#705]
### Short description
Since 1.18.10 Lombok added the @CustomLog annotation but its use is not supported in the plugin. This results in a red text for the log indicating that the log variable is not found. 

### Expected behavior
Support the @CustomLog similarly to the other @Log annotations

### Version information

 * **IDEA Version:** IntelliJ IDEA 2019.1.1 (Ultimate Edition)
 * **JDK Version:** 1.8_211
 * **OS Type & Version:** Mac Mojave
 * **Lombok Plugin Version:** v027-2019.1
 * **Lombok Dependency Version:** 1.18.10

**Comment by Seriels** [comment]
I also encountered the same problem
**Version information**

1. IDEA Version: IntelliJ IDEA 2019.2.4 (Ultimate Edition)
2. JDK Version: 1.8_211
3. OS Type & Version: Mac Mojave
4. Lombok Plugin Version: v027-2019.2
5. Lombok Dependency Version: 1.18.10

**Comment by mplushnikov** [comment]
This feature is already implemented by #672 . The release containg it will be available next days.
