### ISSUE TITLE
Renaming of fields of class annotated with @Getter or @Setter

### ISSUE THREAD

**Issue by schmas** [mplushnikov/lombok-intellij-plugin#71]
Refactoring a field with @Getter and @Setter doesn't rename accessors methods used in other places.

**Comment by mplushnikov** [comment]
It is already working in IntelliJ 14. 
Do you use IntelliJ 13?

**Comment by schmas** [comment]
I already using intellij 14. I will test it. thanks.

**Comment by schmas** [comment]
It's working, thanks a lot.
