### ISSUE TITLE
Incompatible with IntelliJ 2019.3

### ISSUE THREAD

**Issue by bol-com-pschmitz** [mplushnikov/lombok-intellij-plugin#711]
The plugin is entirely disabled by IntelliJ because it is `Incompatible with the current IntelliJ IDEA version.`

Plugin version: unclear. Under "marketplace", IntelliJ reports 0.28-2019.3 (and says it is "installed"). Under "installed", IntelliJ reports 0.18-2018.1.

IntelliJ version:
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 27, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1631M
Cores: 8

**Comment by cmoro-deusto** [comment]
Works for me with the exact same IntelliJ and Lombok Plugin versions in macOS: 10.13.6.

**Comment by bol-com-pschmitz** [comment]
I noticed that after uninstalling and reinstalling the plugin, it started working. So it looks like it's the automatic update of the plugin that is somehow broken (IntelliJ did not offer to update this plugin, even though it did so for other plugins which were also marked as `Incompatible with the current IntelliJ IDEA version.`. I wonder if the fact that IntelliJ reported two different version numbers had something to do with that.

**Comment by cmoro-deusto** [comment]
You might be right @bol-com-pschmitz and it's something related to the plugin upgrade process. I did just install IntelliJ 2019.3 fresh and, obviously, the plugin as well, so I didn't upgrade the plugin.

**Comment by mplushnikov** [comment]
@bol-com-pschmitz Did you update your Intellij from 2018.1 to 2019.3?  Plugin version "0.18-2018.1" is pretty old and doesn't support 2019 Intellij of course. But you should be able to update it automatically in marketplace. Just execute "Help"->"Check for updates" in IntelliJ.

**Comment by bol-com-pschmitz** [comment]
@mplushnikov No, from 2019.2 to 2019.3. The plugin had apparently never been updated, even though IntelliJ is to set to automatically check for plugin updates, and there are no ignored updates. "Check for updates" didn't flag it for updating either. As far as I could tell, there was no update.

I wonder if the fact that IntelliJ was reporting two different versions (see above) had something to do with that.

**Comment by klporter** [comment]
I am also having an issue after updating to intellij 2019.3 and the latest lombok plugin (0.28-2019.3). Intellij doesn't recognize any of my annotated classes.

**Comment by tryrzhihua** [comment]
Hi @klporter , I meet this issue too. and I solve by:
1. reinstall lombok plugin.
2. upgrade lombok dependency:
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.10</version>
        </dependency>
3. If still not resolve, close IDEA and clear IDEA file(.idea/*), and then restart IDEA.

**Comment by straurob** [comment]
I faced the same problem. I could resolve it by updating the Lombok plugin directly via the IntelliJ "Plugins" dialog. After a restart, the plugin worked smoothly.

![grafik](https://user-images.githubusercontent.com/18437455/71806574-6ad0f580-3069-11ea-9dd0-4bb59224b97f.png)

**Comment by Gorynych** [comment]
Same for me :(

IDEA version Ultimate 19.3.2
Lombok plugin version 0.28-2019.3
Lombok project library version 1.18.10
OS macOS Catalina version 10.15.3

Annotation processing is enabled
Lombok plugin is enabled

Everything was installed, reinstalled, and restarted ). Gradle imports the library, IDEA understands annotations very well, but compiler fails.

**Comment by j-gurda** [comment]
I have the same problem. In my case code navigation works correctly. It looks like an editor "sees" Lombok annotations but when I build the module I get bunch of errors like Lombok annotations is not processed at all.
What's interesting is that it started today on two independent machines. Both of them probably updated Intellij to version 19.3.3.

IDEA version Ultimate 19.3.3
Lombok plugin version 0.28-2019.3
Lombok project library version 1.18.10
Ubuntu 16.10

After downgrading to Intellij 19.2.3 and Lombok plugin 0.27-2019.2.3 still have the problem.

**Comment by j-gurda** [comment]
It was `@UtilityClass` annotation which broke my build (and that one error cascaded to other classes). It's more Lombok-related. The following code breaks build:

```
@UtilityClass
public class ProxyUrlBuilder {
    public String proxyUrl(String baseProxyUrl, String requestPath, String queryString) {
        return baseProxyUrl + requestPath + (isEmpty(queryString) ? "" : "?" + queryString);
    }
}
```

whereas following fixes the build:

```
@UtilityClass
public class ProxyUrlBuilder {

    public static String proxyUrl(String baseProxyUrl, String requestPath, String queryString) {
        return baseProxyUrl + requestPath + (isEmpty(queryString) ? "" : "?" + queryString);
    }
}
```

I hope I save someone hours of investigation.

**Comment by Gorynych** [comment]
> Same for me :(
> 
> IDEA version Ultimate 19.3.2
> Lombok plugin version 0.28-2019.3
> Lombok project library version 1.18.10
> OS macOS Catalina version 10.15.3
> 
> Annotation processing is enabled
> Lombok plugin is enabled
> 
> Everything was installed, reinstalled, and restarted ). Gradle imports the library, IDEA understands annotations very well, but compiler fails.

Solution for me was to switch from "Obtain processors from project classpath", and specify path to lombok jar manually.

**Comment by tafli** [comment]
IDEA version Ultimate 19.3.3
Lombok plugin version 0.28-2019.3

Solution for me was to remove the _.idea_-project folder. After reimporting, the annotation processor worked fine again.

Uninstalling and reinstalling the lombok plugin itself didn't do the trick.

**Comment by Hokan-Ashir** [comment]
IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.39, built on January 21, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-28-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: 
Non-Bundled Plugins: Lombook Plugin, com.intellij.plugins.html.instantEditing, org.intellij.scala

reinstalling plugin, restarting IDEA, removing .idea folder, different versions of lombok itself didn't fix the problem

**Comment by mplushnikov** [comment]
Lombok plugin works very well in IntelliJ 2019.3+
I'm working every day with it, and didn't see any problems.

What are we talking about? What is not working in your environment? 

If you get any compiler-errors, this is nothing what plugin is responsible for. Check and double check your build configuration in maven/gradle or what are you using in the project. 
Check if 'mvn install'/'gradle jar' works on command line. 
Build in Intellij should work without compiler errors, also if you have no plugin installed!( You will see red code in editor, but compile should simple work) 
If some of this steps are not working, something in your configuration is broken, but have nothing to do with the plugin.

Only if everything compiles and you still see red code in editor window, we have to look on plugin.

Plugin make IDEA understand annotations and show autocompletion for code etc. Compatible plugin build for Intelllij 2019.3 is plugin 0.28-2019.3. For Intellij 2019.2  -> 0.28-2019.2 and so one.

**Comment by kcloze** [comment]
> Hi @klporter , I meet this issue too. and I solve by:
> 
> 1. reinstall lombok plugin.
> 2. upgrade lombok dependency:
> 
> ```
>         <dependency>
>             <groupId>org.projectlombok</groupId>
>             <artifactId>lombok</artifactId>
>             <version>1.18.10</version>
>         </dependency>
> ```
> 
> 1. If still not resolve, close IDEA and clear IDEA file(.idea/*), and then restart IDEA.

Thanks,I fixed it by this.

**Comment by pethaniakshay** [comment]
> I noticed that after uninstalling and reinstalling the plugin, it started working. So it looks like it's the automatic update of the plugin that is somehow broken (IntelliJ did not offer to update this plugin, even though it did so for other plugins which were also marked as `Incompatible with the current IntelliJ IDEA version.`. I wonder if the fact that IntelliJ reported two different version numbers had something to do with that.

Worked me for IDEA 2020.1

**Comment by ffrancavilla** [comment]
In my case, it worked after i realized i was trying to test a @Getter annotation over a primitive boolean field.
Apparently, despite it works for other primitive types (int, for instance), IntelliJ 2019.3.4 and Lombok plugin 0.29-2019.3 does not recognize the Getter for my "private boolean enabled" field.

Hope it helps.

**Comment by gggsmith** [comment]
And I've tried to use @Value annotation (expecting from it to generate all-args constructor) and another overloaded version of constructor which used all-args constructor. .
Documentation says:
> any explicit constructor, no matter the arguments list, implies lombok will not generate a constructor.

So, my fault.. It would be nice if lombok plugin would indicate such flow though
