### ISSUE TITLE
Extension methods show up as invalid methods but it still compiles.

### ISSUE THREAD

**Issue by RaymondTracer** [mplushnikov/lombok-intellij-plugin#717]
### Short description
Autocomplete doesn't work with extension methods and when I type it in manually, it shows up as an invalid method.

### Expected behavior
Autocomplete sees the methods within the class I'm using for extension methods and the methods show up as valid methods, able to ctrl+click on methods to jump to them, etc.

### Version information

 * **IDEA Version:** 2019.3.1
 * **JDK Version:** 12.0.1
 * **OS Type & Version:** Windows 7 Ultimate 64-bit SP1
 * **Lombok Plugin Version:** 0.28-2019.3
 * **Lombok Dependency Version:** 1.18.10

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Add Lombok jar to library folder.
 2. Add Lombok plugin to IntelliJ.
 3. Enable annotation processing.
 4. Attempt to use extension methods.

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [X] Sample project provided
 - [x] I am able to reproduce this error on the sample project by following the steps described above

[LombokExtensionTest.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/3982729/LombokExtensionTest.zip)
![Screenshot](https://user-images.githubusercontent.com/6290310/71161683-eb3bdc00-229d-11ea-954b-2b9318d632c7.png)

### Additional information
I'm not using Marvin, Gradle or anything like that.

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```
N/A
```

**Comment by mplushnikov** [comment]
I'm very sorry, but @ExtensionMethod is not supported by plugin 
duplicates #21

**Comment by caoli5288** [comment]
@mplushnikov Are there any plans to support this feature？
