### ISSUE TITLE
Support new setterPrefix for Builder

### ISSUE THREAD

**Issue by lppedd** [mplushnikov/lombok-intellij-plugin#719]
See https://github.com/rzwitserloot/lombok/pull/2174

Syntax:
```
@Builder(setterPrefix = "with")
class ...

builder.withOne(one)
       .withTwo(two)
       .build();
```

@mplushnikov how many hours would you bet on this one?

**Comment by elusiveeagle** [comment]
I would love to have this support as well! I haven't looked at the code for this plugin before, but I'll take a gander.

**Comment by chriswilty** [comment]
Thank you so much for this :grin: 

I realise I'm sounding over-eager, but is there a loose idea of when 0.29 might get released?

**Comment by elusiveeagle** [comment]
> Thank you so much for this 😁
> 
> ~I realise I'm sounding over-eager, but is there a loose idea of when 0.29 might get released?~
> Released already, brilliant 😅

Looks the [new release is out](https://github.com/mplushnikov/lombok-intellij-plugin/releases/tag/releasebuild_0.29-2019.3-2)! Thanks, @mplushnikov!
