### ISSUE TITLE
@Accessors with prefix can break with numbers

### ISSUE THREAD

**Issue by WildOrangutan** [mplushnikov/lombok-intellij-plugin#724]
### Short description
Using `@Accessors(prefix="m")` breaks, when 2nd char in field name is a number and used in combination with other annotations (for example `@Getter`, `@Setter` and others).

### Example
```lang=java
@Accessors(prefix="m")
public class Test {
    @Getter
    float m3Titanic;
}
```

### Actual behavior
Based on example, `@Getter` doesn't generate `get3Titanic()` method.

Warning is produced: `Not generating getter for this field: It does not fit your @Accessors prefix list. `

### Expected behavior
Based on example, `@Getter`, should produce `get3Titanic()`.

Also, dunno if possible, but could warning message also be improved. Or preferably changed to produce an error?

### Version information
 * **IDEA Version:** Android Studio 3.5.3 (Idea 2019-1)
 * **JDK Version:** 1.8.0_202-release-1483-b03
 * **OS Type & Version:** Windows 10
 * **Lombok Plugin Version:** 0.28-2019-1
 * **Lombok Dependency Version:** 1.18.10

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Create class with a field
 2. Annotate class with `@Accessors` and prefix
 3. Add field using prefix from previous step, and name it so that 2nd character has a number
 4. Annotate field with with `@Getter` or `@Setter`, or else
 5. Getter, setter, or similar doesn't generate.

### Additional information
https://github.com/rzwitserloot/lombok/issues/2338

**Comment by mplushnikov** [comment]
Should be fixed with PR by Lekanich in the next release
