### ISSUE TITLE
Intellij 14.0.3 + gradle project

### ISSUE THREAD

**Issue by romanman** [mplushnikov/lombok-intellij-plugin#73]
http://i.imgur.com/Oyk7O2D.png

+ the lambook been installed as a plug-in and all 
the correct checkboxes was assured.

+ looks like the build button doesn't hookup lambook in to the process

**Comment by tryIO** [comment]
are you sure to have enabled the annotation processing? you can find it under Build, Execution, Deployment > Compiler > Annotation Processors

**Comment by romanman** [comment]
@tryIO : thanks, it worked.
