### ISSUE TITLE
I cannot make Lombok to work in Intellij Idea 2019.3.2

### ISSUE THREAD

**Issue by micobarac** [mplushnikov/lombok-intellij-plugin#730]
### Short description
Getters and setters are not recognized in service and repository classes

### Expected behavior
Getters and setters should be recognized in service and repository classes

### Version information

 * **IDEA Version:** 2019.3.2
 * **JDK Version:** 1.8
 * **OS Type & Version:** MacOS Catalina
 * **Lombok Plugin Version:** 0.28-2019.3
 * **Lombok Dependency Version:** 1.18.10

### Steps to reproduce
I followed the suggested steps:

1. Added `Lombok Maven` dependency to `pom.xml`
2. Installed latest `Intellij Idea Lombok plugin`
3. Enabled the `annotation processing`
4. I added Lombok `@Getter @Setter`  class annotations to a domain class

I tried reversing the order of these steps, restarting IDE, deleting .idea directory...
Project rebuild is throwing the errors of not recognising the getters and setters I use via Lombok domain class annotations in service and repository classes.

**Comment by goatleyj** [comment]
Is there an ETA on the fix?

**Comment by micobarac** [comment]
I made it work by enabling annotation processing both for `Default` and `Annotation profile for App`. It looks like the later was mandatory too.

**Comment by goatleyj** [comment]
@micobarac thanks for the reply! where is the setting for `Annotation profile for App`? I've got default enabled already.

**Comment by micobarac** [comment]
@goatleyj It's right below the default settings.

**Comment by MasterChenGitHub** [comment]
why not using kotlin's data class?
