### ISSUE TITLE
Support the lombok.builder.className config option

### ISSUE THREAD

**Issue by kennethjor** [mplushnikov/lombok-intellij-plugin#739]
### Short description
When adding `lombok.builder.className = Builder` to `lombok.config` lombok picks up the default name without having to add it to the annotations, but the IntelliJ plugin does not recognise it.

### Expected behavior
I would like the IntelliJ plugin to behave as if all `@Builder` annotations have this default set.

### Version information

 * **IDEA Version:** 2019.2.4 Build #IU-192.7142.36
 * **JDK Version:** 1.8.0_201
 * **OS Type & Version:** Ubuntu 18.04
 * **Lombok Plugin Version:** 0.28-2019.2
 * **Lombok Dependency Version:** 1.18.10

### Steps to reproduce
 1. Create a class with `@Builder` annotation.
 2. Add `lombok.builder.className = Builder` to `lombok.config`

**Comment by kennethjor** [comment]
While `@SuperBuilder` doesn't have the option to set a different `builderClassName` like `@Builder` does, it appears the config option does affect the generation under the hood.

**Comment by mplushnikov** [comment]
Already fixed with #70 , please update your plugin.

**Comment by mplushnikov** [comment]
Duplicate #680
