### ISSUE TITLE
Sneaky Throws Not Correctly Detected for Anonymous Inner Class

### ISSUE THREAD

**Issue by danielsomerfield** [mplushnikov/lombok-intellij-plugin#74]
There is a particular case with an anonymous inner class that the plugin appears not to correctly detect that the @SneakyThrows annotation should handle the thrown exception.

    package bugReport;
    import lombok.SneakyThrows;
    import java.io.IOException;
    public class BugReport {
        private IInner inner;

        //@SneakyThrows(IOException.class)
        public BugReport() {
             inner = new IInner() {
                 @SneakyThrows(IOException.class)
                 @Override
                 public IInner doSomething() {
                     throw new IOException();
                 }
            };
        }

        interface IInner {
            public IInner doSomething() throws IOException;
        }
    }

If you uncomment the sneaky throws, it will compile in Intellij, but it will fail in javac with the following message: *...exception java.io.IOException is never thrown in body of corresponding try statement.*

**Comment by mplushnikov** [comment]
I've reimplemented @SneakyThrow hander to fix this kind of error, but it will work only in Intellij version 14.0 and greater.

**Comment by mplushnikov** [comment]
Version 0.9.0 of plugin is available now

**Comment by danielsomerfield** [comment]
Looks great! Thanks for the fix.
