### ISSUE TITLE
Support @lombok.Builder (lombok version 1.16)

### ISSUE THREAD

**Issue by geipette** [mplushnikov/lombok-intellij-plugin#75]
Right now the plugin supports @lombok.experimental.Builder

lombok 1.16 deprecates @lombok.experimental.Builder and introduce @lombok.Builder

As a first it would be nice if the plugin just treated both of these annotations equally.

**Comment by lexandro** [comment]
+1

**Comment by Janmm14** [comment]
:+1:

**Comment by zephiransas** [comment]
:+1:

**Comment by dharrigan** [comment]
:+1:

**Comment by cbeams** [comment]
Just reported this same issue on the main Lombok project's tracker before realizing there was a separate repo for the IDEA plugin: https://code.google.com/p/projectlombok/issues/detail?id=780

**Comment by mplushnikov** [comment]
Should be fixed in the next release of plugin.

**Comment by richadams8** [comment]
:+1:

**Comment by jacek99** [comment]
just got bit by this, waiting for this enhancement.

Thanks for your great work on this plugin, I would have to quit IntelliJ if not for it...

**Comment by mplushnikov** [comment]
Version 0.9.0 of plugin is available now

**Comment by jacek99** [comment]
Just tested, works as expected. Thanks!
