### ISSUE TITLE
Inconsistent library versions notice.

### ISSUE THREAD

**Issue by calvinhkf** [mplushnikov/lombok-intellij-plugin#751]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 1 inconsistent library.

Take org.projectlombok:lombok for example, this library is declared as version 1.18.10 in test-manual, 1.18.2 in test-manual/old-lombok and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take org.projectlombok:lombok for example, if we harmonize all the library versions into 1.18.10. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table shows the overall harmonization cost on APIs. It seems your project have no API invokes on this library, which could be safely upgrade to 1.18.10

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|test-manual|0(0)|0(0)|0(0)|
|2|test-manual/old-lombok|0(0)|0(0)|0(0)|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. 

If you are interested, you can have a more complete and detailed report in the attached PDF file.
[mplushnikov lombok-intellij-plugin.pdf](https://github.com/mplushnikov/lombok-intellij-plugin/files/4271300/mplushnikov.lombok-intellij-plugin.pdf)

**Comment by mplushnikov** [comment]
Hi @calvinhkf, this is false positive, it works as expected.

**Comment by calvinhkf** [comment]
Is `test-manual/old-lombok` a deprecated module that will not compiled into the product? If so, sorry for that false positive. Currently we don't consider specific project knowledge into version inconsistency.

**Comment by mplushnikov** [comment]
Yes, absolutely! "test-manual" is as the name said, only for manual tests, and contains also examples for explicit old and deprecated functionality.

**Comment by calvinhkf** [comment]
Thanks for your reply! Will improve our detection method later....
