### ISSUE TITLE
Lombok Dependency is possibly outdated

### ISSUE THREAD

**Issue by dimipaun** [mplushnikov/lombok-intellij-plugin#762]
I'm currently running IntelliJ IDEA 2019.3, and I see the warning:
```
Lombok Dependency is possibly outdated
	Project "EdgeServer" and Module "EdgeServer.test" seem to have outdated lombok dependency added.
	Configured version "1.18.10", but there is at least version "1.18.12" already released
```

I'm using the lastest vesion of the freefair plugin:
```
id "io.freefair.lombok" version "4.1.6"
```

which is supposed to pickup lombok 1.18.12. 

I've tried to force the issue by adding:
```
annotationProcessor 'org.projectlombok:lombok:1.18.12'
```

to no avail.

The warning seems spurious.

**Comment by hellofuturecyj** [comment]
i use version 2019.2.4 and i have the same problem

**Comment by mplushnikov** [comment]
Looked on this issue now deeper:
gradle plugin io.freefair.lombok version "4.1.6" simple use lombok in version 1.18.10 internally. 
The warning is absolutly correct.
You need to update your gradle plugin to 5.2.1 to get the newest lombok version.
