### ISSUE TITLE
The @Slf4j in 0.29-2019.3 version not support for IDEA 2019.3.4 

### ISSUE THREAD

**Issue by 765741668** [mplushnikov/lombok-intellij-plugin#766]
### Short description
The @Slf4j is not support, but the other annotations is working well.

### Version information

 * **IDEA Version: 2019.3.4 Ultimate Edition
 * **JDK Version: 1.8.0_241-b07
 * **OS Type & Version: window10 professional
 * **Lombok Plugin Version: 0.29-2019.3
 * **Lombok Dependency Version: lombok-plugin-0.29-2019.3.jar

**Comment by mplushnikov** [comment]
Cann't reproduce this, @Slf4j is working well.
