### ISSUE TITLE
Plugin not compatible with latest intelli version(IntelliJ IDEA 2020.1 Beta )

### ISSUE THREAD

**Issue by pavelgordon** [mplushnikov/lombok-intellij-plugin#767]
### Short description
Incompatible with latest IntelliJ Idea version
Doesn't generate code for `@Data` (and possibly others) annotations

### Version information

 * **IDEA Version:** IntelliJ IDEA 2020.1 Beta (Ultimate Edition) Build #IU-201.6668.13, built on March 25, 2020
 * **JDK Version:** JDK11
 * **OS Type & Version:** MacOS
 * **Lombok Plugin Version:** 0.29-2019.3
 * **Lombok Dependency Version:** 1.18.4

Do you already have any plans for updating the plugin? Branch etc?

**Comment by lorenzleutgeb** [comment]
Temporary workaround:
 1. Clone this repository.
 2. Run `IDEA_VERSION=LATEST-EAP-SNAPSHOT ./gradlew build`
 3. Open IntelliJ and ["Install plugin from Disk"](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk), choose `lombok-intellij-plugin/build/distribution/lombok-plugin-0.30-EAP.zip` (or similar, there should be only one ZIP file in that folder).

To skip (1.) and (2.) you may use 
[lombok-plugin-0.30-EAP.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4401904/lombok-plugin-0.30-EAP.zip) which is what my machine built. That's of course provided without any responsibility/warranty.

**Comment by rpalcolea** [comment]
Hi!

I verified latest on master following the local installation with

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.60, built on April 1, 2020

Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
Non-Bundled Plugins: Lombook Plugin

The plugin works as expected.

Are you planning to release a new version soon? or until 2020.1 is stable release?

Thanks

**Comment by z0mb1ek** [comment]
today rc1 goes out

**Comment by pavelgordon** [comment]
With RC1 it works.
