### ISSUE TITLE
Support new @Singular annotation for @Builder collection fields

### ISSUE THREAD

**Issue by jkwatson** [mplushnikov/lombok-intellij-plugin#77]
Would love to have this; This is a great new feature in lombok, and IDEA support would be awesome!

**Comment by Cilph** [comment]
+1.

**Comment by bpedman** [comment]
+1

**Comment by TimSchlechter** [comment]
+1

**Comment by pawelkrupinski** [comment]
+1

**Comment by tleveque23** [comment]
+1

**Comment by zshamrock** [comment]
+1

**Comment by pkoperek** [comment]
+1

**Comment by mragab** [comment]
+1

**Comment by RodrigoQuesadaDev** [comment]
+1

**Comment by j-walker23** [comment]
+1

**Comment by j-walker23** [comment]
Can anyone here explain how to add this manually for now, please?

**Comment by jordanjennings** [comment]
Even though it's not fully supported by the plugin, you can actually use
the annotation and the generated method in your code. It won't autocomplete
the method name, so you'll have to manually type it and It'll show up in
red while editing the file, but your code will still run. That's been my
experience using it so far anyway.

**Comment by j-walker23** [comment]
Hey, thanks for your response, appreciate it. I should have worded my question in a way that actually made sense.

What i wanted to ask is if there is a way to manually add that part, really meaning just duplicate what the builder is doing so all of the pseudo errors you mentioned won't show up. And so my colleagues don't lose their minds : )

**Comment by j-walker23** [comment]
I just ended up writing a custom one. Using the other awesome annotations i was able to write the builder with @Singular functionality with very little code. Thanks lombok and plugin people!

**Comment by RodrigoQuesadaDev** [comment]
+1

**Comment by beihaifeiwu** [comment]
+1

**Comment by jkwatson** [comment]
@j-walker23 Are you saying you have changes to the plugin that make it work? Or a separate plugin? Either way, I'm sure a pull request with the changes to this project would be greatly appreciated!

**Comment by dnoggle** [comment]
+1

**Comment by j-walker23** [comment]
@jkwatson I wish i was saying that. I ended up just writing the class manually, but with using 20 other lombok annotations it really ended up being very short anyway.

I am a big time Java noob and am forced into doing full stack because all of our backend devs left. I wouldn't even know where to start with a PR. If i was that cool you guys would be the first to know!

**Comment by WonderCsabo** [comment]
:+1:

**Comment by dnnoggle** [comment]
Is there any rough planned date for 0.10.0?

**Comment by mrcritical** [comment]
+1

**Comment by rcoedo** [comment]
+1

**Comment by spencergibb** [comment]
+1

**Comment by mplushnikov** [comment]
The version 0.9.5 already contains initial support for @Singular. Please verify the functionality.

**Comment by dnoggle** [comment]
@Singular works and so does importing the builder nested class.

Thank you!

**Comment by jkwatson** [comment]
Looks and works great!  Thanks!

**Comment by sunguangran** [comment]
+1

**Comment by spencergibb** [comment]
:+1: worked great!
