### ISSUE TITLE
Latest Lombok 0.29-2019.3 is not compatible with IDEA 2020.1

### ISSUE THREAD

**Issue by cybergeene** [mplushnikov/lombok-intellij-plugin#775]
### Short description
getters and setters do not work correctly - IDEA can't find its behaviour after IDE has been updated to 2020.1 version

### Expected behavior
IDEA marks red getters and setters

### Version information

 * **IDEA Version:** 2020.1
 * **JDK Version:** OpenJDK 64-Bit Server VM (build 25.252-b07, mixed mode)
 * **OS Type & Version:** Ubuntu 20.04
 * **Lombok Plugin Version:** 0.29-2019.3 
 * **Lombok Dependency Version:** 1.18.10

### Steps to reproduce

 1. Update IDEA to 2020.1

**Comment by burka** [comment]
I just updated the intellij dependency and build it locally. For me this [lombok-plugin-0.30-EAP.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4446418/lombok-plugin-0.30-EAP.zip)
works until the official update ist out :-) (Settings➙Plugins➙:gear:➙Install Plugin from Disk...)

**Comment by cybergeene** [comment]
It's works for me. 
Thanks a lot!

**Comment by hgmtrebing** [comment]
Thanks, this helped me as well.

**Comment by twoversionsofme** [comment]
Thanks for the quick workaround on this!

**Comment by skpriyatham58** [comment]
@burka this didn't work on ubuntu, do you have another build?

**Comment by gaetan-auffret** [comment]
@skpriyatham58 https://github.com/mplushnikov/lombok-intellij-plugin/issues/775#issuecomment-610553000 works on **Ubuntu bionic 18.04** in the following environment:
_IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.113, built on April 7, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-45-generic_

**Comment by davidgfolch** [comment]
It's works here, with Ubuntu 18 (but there is another problem with Jdk11 installed by intellij through Snap)

**Comment by mykpatryk** [comment]
@davidgfolch I have the same problem with JDK. It seems like a project doesn't see many things e.g. String, Throwable, @Override etc, but is is building successfully. Have already found a solution to that?

**Comment by davidgfolch** [comment]
Yes, just moved to jdk8 in that project

**Comment by CrystallDEV** [comment]
Works like a charm, thanks

**Comment by burka** [comment]
@skpriyatham58 I used Ubuntu 19.10 with JDK8 and it worked. Maybe you could build it yourself and have a look where the problem is? You can use the branch of my merge request, then only a `./gradlew build` would be neccessary. The result will be in `build/distributions/`.

**Comment by mykpatryk** [comment]
Solution in my case: After InteliJ update to 2020, my JDK was completely crushed / unnoticeable by InteliJ. Once you reinstall JDK everything will be back to normal

**Comment by aygiz** [comment]
Thanks!

**Comment by ldrogou** [comment]
Thanks

**Comment by zlren** [comment]
thanks

**Comment by Aberdeener** [comment]
Thank you!

**Comment by pavankjadda** [comment]
I just updated to IntelliJ 2020.1 on macOS 10.15 and Lombok plugin broke.

**Comment by ruurd** [comment]
> I just updated to IntelliJ 2020.1 on macOS 10.15 and Lombok plugin broke. Using [this](https://github.com/mplushnikov/lombok-intellij-plugin/issues/775#issuecomment-610553000) alternative

Same here...

**Comment by zman0900** [comment]
The EAP release works fine for me: https://github.com/mplushnikov/lombok-intellij-plugin/releases/tag/releasebuild_0.29-2020.1-3

**Comment by jed-meyer** [comment]
> [lombok-plugin-0.30-EAP.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4446418/lombok-plugin-0.30-EAP.zip)

Just wondering: where did you get this link from? I don't see it referenced anywhere nor does googling reveal any such url pattern (.../user/repo/files/...) to me. Is this some unreleased release? Did you upload that file and manage to publish it under the url of this repo? :confused:

**Comment by tr00per** [comment]
> Did you upload that file and manage to publish it under the url of this repo?

@jed-meyer Seems it's an attachment to the issue comment. This is "code from the internet", that people are downloading & running on their machines :P Security risk?

**Comment by dquintela** [comment]
Since https://github.com/mplushnikov/lombok-intellij-plugin/releases already has a build for 2020.1, the solution is uninstall plugin, restart and reinstall plugin - Intellij will pick the right version then.

**Comment by pptom** [comment]
I just reinstalled the Lombok and it‘s work for me.

**Comment by quayegallas** [comment]
Thanks!!!!!

**Comment by feng2r200** [comment]
> I just reinstalled the Lombok and it‘s work for me.

Thanks!!!!! It's works

**Comment by feng2r200** [comment]
> I just reinstalled the Lombok and it‘s work for me.

@pptom Thanks!!!!It's works

**Comment by codelixin** [comment]
@pptom you are right!!

**Comment by chaosmin** [comment]
It works for me! thank you!!

**Comment by tyler-avs** [comment]
Thanks for this tip.  I was a lost soul.

**Comment by panjiesw** [comment]
I just uninstalled lombok plugin -> restarted idea -> re-installed lombok plugin -> restarted again
Then there is notification that there is lombok plugin update,
but upon updating it, there is an error.

![2020-04-10-132909_4480x1440_scrot](https://user-images.githubusercontent.com/1451848/78968763-96afbb80-7b2f-11ea-987f-c64bcb9f35bc.png)

![2020-04-10-132916_4480x1440_scrot](https://user-images.githubusercontent.com/1451848/78968774-9ca59c80-7b2f-11ea-8a25-85639305c7ab.png)

**Comment by jdevreese** [comment]
I have the same problem as panjiesw.
I found this in my log file:
```
2020-04-10 08:17:44,758 [ 395326]   INFO - ateSettings.impl.UpdateChecker - failed to load plugin descriptions from : Malformed URL:  
2020-04-10 08:18:01,273 [ 411841]   INFO - lij.ide.plugins.DynamicPlugins - Plugin Lombook Plugin is not unload-safe because of extension to non-dynamic EP com.intellij.implicit.resource.closer 
2020-04-10 08:18:01,732 [ 412300]   INFO - Settings.impl.PluginDownloader - Plugin Lombook Plugin: current version (max) 0.29-EAP
```

**Comment by jed-meyer** [comment]
> @jed-meyer Seems it's an attachment to the issue comment. This is "code from the internet", that people are downloading & running on their machines :P Security risk?

Seems you're spot on, thanks! Personally, I won't download and run anything like this, but that's just my everyday paranoia. The generated url is more than misleading though as it implies referencing an official repo file. GitHub should at least add something to the path to make it clear this is 3rd party content.

**Comment by akyrey** [comment]
Experiencing the same problem as @panjiesw 

Since I had the same error message when trying to update, I uninstalled the plugin, restarted the Intellij, installed the plugin, restarted again and still had the update notification. If i click on the update button, I receive again the same error.

**Comment by mplushnikov** [comment]
Lombok Plugin Version: 0.29-2019.3 is for Intellij 2019.3 as you can see.
Why do you not update/use version 0.29-EAP, available already from 01.03.2020?

**Comment by larsgrefer** [comment]
@mplushnikov Our IntelliJ installations didn't offer 0.29-EAP as a plugin update until today.

So after upgrading IntelliJ itself to 2020.1 it just complained about the Lombok Plugin (0.29-2019.3) being incompatible, but didn't offer an update for the plugin.

But now my local IntelliJ just updated the Lombok plugin by itself. (Without the need to re-install it, as mentioned above)

**Comment by joffrey-bion** [comment]
@larsgrefer In my case I could not upgrade lombok until today, but IntelliJ didn't do it by itself, it required me to update manually.
By this I mean:
1. Go to the `Preferences... > Plugins`
2. Go to the "Installed" tab
3. Find lombok and hit "Update"
4. Restart IntelliJ

**Comment by burka** [comment]
> > [lombok-plugin-0.30-EAP.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4446418/lombok-plugin-0.30-EAP.zip)
> 
> @burka Just wondering: where did you get this link from?

@jed-meyer I build it and uploaded it as an attachment to my post :-) Exactly as @tr00per said :-)

**Comment by wuzhefang** [comment]
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep

same here

**Comment by romantorkit** [comment]
> I just updated the intellij dependency and build it locally. For me this [lombok-plugin-0.30-EAP.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4446418/lombok-plugin-0.30-EAP.zip)
> works until the official update ist out :-) (Settings➙Plugins➙⚙️➙Install Plugin from Disk...)

Worked on macOS 10.15.4

**Comment by skromberg** [comment]
The last version lombok-plugin-0.30-EAP.zip leads to the following info for _@UtilityClass_ annotated classes with static methods inside IntelliJ

`@UtilityClass already marks methods static.`

If you discard the static on the method, the whole project cannot be built anymore.

**Comment by TahaChehad** [comment]
Verison [](https://github.com/mplushnikov/lombok-intellij-plugin/issues/775) does make Intellij recognize Lombok annotations. However, it you put contradictory Lombok annotations on the same class, there is no compile error at all. Example: add @RequiredArgsConstructor with @NoArgsConstructor compiles correctly.

**Comment by ruurd** [comment]
> Verison lombok-plugin-0.30-EAP.zip does make Intellij recognize Lombok annotations. However, it you put contradictory Lombok annotations on the same class, there is no compile error at all. Example: add @RequiredArgsConstructor with @NoArgsConstructor compiles correctly.

Because as a matter of fact those two annotation do not generate conflicting code at all. Please use the refactoring menu choices to see what Lombok actually generates before making a conclusion.

**Comment by CasaSky** [comment]
> Since https://github.com/mplushnikov/lombok-intellij-plugin/releases already has a build for 2020.1, the solution is uninstall plugin, restart and reinstall plugin - Intellij will pick the right version then.

Thanks for the solution method. It worked well for me!

**Comment by mplushnikov** [comment]
The latest IntelliJ IDE version (2020.1) contains a BUG for several plugins (including plugin for Lombok) were shown as incompatible with the updated version of the IDE.

You can find the issue with a detailed explanation here: https://youtrack.jetbrains.com/issue/IDEA-237113. 

It has already been resolved and the fix will be in the nearest IDE patch (presumably 2020.1.1).

As of now, the workaround is to re-install the plugin in the IDE settings.

**Comment by mplushnikov** [comment]
> The last version lombok-plugin-0.30-EAP.zip leads to the following info for _@UtilityClass_ annotated classes with static methods inside IntelliJ
> 
> `@UtilityClass already marks methods static.`
> 
> If you discard the static on the method, the whole project cannot be built anymore.

Due to a peculiar way javac processes static imports, trying to do a non-star static import of any of the members of a `@UtilityClass` won't work. Either use a star static import: `import static TypeMarkedWithUtilityClass.*;` or don't statically import any of the members.

**Comment by sleberknight** [comment]
Regarding the star imports, if you actually put `static` on methods in classes that use `@UtililtyClass` then it works just fine. We have always done this, and use `@UtilityClass` to generate the private constructor and to indicate the _intent_ of the class. Adding `static` to each method isn't much extra work and once you're down past the top of the class, it helps having the `static` on there. (In my opinion of course.)
