### ISSUE TITLE
Plugin is missing icon

### ISSUE THREAD

**Issue by miparnisari** [mplushnikov/lombok-intellij-plugin#778]
### Short description
The plugin is missing an icon

### Expected behavior
The plugin should have an icon

### Version information

 * **IDEA Version:** IntelliJ IDEA 2020.1 (Community Edition)
 * **JDK Version:** all
 * **OS Type & Version:** all
 * **Lombok Plugin Version:** 0.29-EAP

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5374887/80009912-8fb57100-847e-11ea-9e75-90ea3d2726c8.png)

### Additional information
[As per the IntelliJ docs](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html#plugin-logo-requirements), you need to upload an image of 40x40 into the META-INF folder with the specific name `pluginIcon.svg`.

**Comment by mplushnikov** [comment]
I anybody can make some good icon, I'll add it! 
Or maybe somebody can make 40x40 svg icon from 
![lombok](https://user-images.githubusercontent.com/1204509/79262490-b2012a80-7e91-11ea-82fa-e791f8b4d177.jpg)

**Comment by ghusta** [comment]
There is a SVG in the official repo, but not for the previous image.

It's the one used in the Eclipse plugin : https://github.com/rzwitserloot/lombok/blob/master/src/installer/lombok/installer/lombok.svg

You found yours in the Twitter account isn't it ? ➡️  https://twitter.com/project_lombok
