### ISSUE TITLE
Plugin "Lombok" is incompatible with the newest IntelliJ (until build 193.SNAPSHOT < IU-201.6668.121)

### ISSUE THREAD

**Issue by michalrogozinski** [mplushnikov/lombok-intellij-plugin#779]
### Short description
After Upgrading IntelliJ, I'm getting this error: Plugin Error: Plugin "Lombok" is incompatible (until build 193.SNAPSHOT < IU-201.6668.121). Looks like there is no version of Lombok plugin compatible with the current version of IntelliJ.

### Expected behavior
Support version 2020.1 (from April 2020)

### Version information

 * **IDEA Version:** 
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020

 * **JDK Version:** 
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
GC: ParNew, ConcurrentMarkSweep

 * **OS Type & Version:** 
Windows 10 10.0

 * **Lombok Plugin Version:** 
0.29-EAP

 * **Lombok Dependency Version:** 

### Steps to reproduce

 1. Upgrade IntelliJ with Lombok plugin to newest version
 2. see Event log for error message
 

### Sample project
N/A 

### Additional information
N/A

### Stacktrace
N/A

**Comment by AbdulAzizCr** [comment]
I have the same issue too What is wrong with lombok ? All projects of mine has been suspended of that.

**Comment by AbdulAzizCr** [comment]
So, i just figured that out, you will need to uninstall the current version of your lombok, then go and update your intelliJ to the latest version, then  go to settings -> plugins -> search for lombok -> install -> restart IDE -> fixed <3 xD

**Comment by michalrogozinski** [comment]
Thanks! that worked!

**Comment by vsnikalex** [comment]
Just update your Lombok plugin in Settings > Plugins.
