### ISSUE TITLE
Support for constructors of @Value objects with assigned final fields 

### ISSUE THREAD

**Issue by jkwatson** [mplushnikov/lombok-intellij-plugin#78]
A class defined like this:
```java
@Value
public class Foo {
  String one;
  String two = "foo";
}
```

Has a constructor:
```java
new Foo("one");
```

But, IDEA shows this as an error and is expecting the 2nd (errant) constructor arg.

**Comment by mplushnikov** [comment]
Should be fixed in the next release (0.9.1)
