### ISSUE TITLE
Add a support for Intellij IDEA 2020.1

### ISSUE THREAD

**Issue by sergeivisotsky** [mplushnikov/lombok-intellij-plugin#780]
### Short description
Current Lombok version is incompatible with Intellij IDEA 2020.1

### Expected behavior
Lombok Plugin is fully operating on Intellij IDEA 2020.1

### Version information

 * **IDEA Version:** Intellij IDEA 2020.1
 * **JDK Version:** JDK 11 & JDK 1.8
 * **OS Type & Version:** Windows 10 Pro
 * **Lombok Plugin Version:** 0.29-2019.3
 * **Lombok Dependency Version:** 1.18.10

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Install Intellij IDEA 2020.1
 2. Open Settings / Plugins
 3. See

### Sample project
N/A

### Additional information
N/A

### Stacktrace

```
N/A
```

**Comment by DenisKozachok** [comment]
@sergeivisotsky 
You can add a new version manually.
[lombok-plugin-0.30-EAP.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4468662/lombok-plugin-0.30-EAP.zip)
1) Go to the Preferences... > Plugins
2) Go to the "Installed" tab
3) Find lombok and hit "Update"
4) Restart IntelliJ

**Comment by sergeivisotsky** [comment]
@DenisKozachok  Thanks!

**Comment by arjunsuccena** [comment]
Not able to update even after copying the extracted zip to C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2018.2.5\plugins.
Still see only Disable and Uninstall options in the Plugins UI.

**Comment by sergeivisotsky** [comment]
@arjunsuccena For me it works. Maybe it is specific for Intellij IDEA Community in your case.

**Comment by serious6** [comment]
yes I can confirm the issue will occur with latest IDEA Community Version. For me also only disable and uninstall appear.

**Comment by intellitour** [comment]
@DenisKozachok the solution works in IDEA Ultimate 2020.1. Thank you!

**Comment by habutre** [comment]
@DenisKozachok it works, but on my GNU/Linux box the steps are slightly different, maybe help others:

1. File settings (Ctrl+Alt+s) -> Plugins
1. Go to the _Installed_ tab (same above)
1. Find and highlight Lombok
1. Along with *Installed* tab click on :gear:  icon and choose _Install Plugin from Disk_

**Comment by bitnot** [comment]
Looks like this issue duplicates #775

**Comment by mpbalmeida** [comment]
https://github.com/mplushnikov/lombok-intellij-plugin/issues/775#issuecomment-611823534

**Comment by gustavodiasdev** [comment]
> @sergeivisotsky
> You can add a new version manually.
> [lombok-plugin-0.30-EAP.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4468662/lombok-plugin-0.30-EAP.zip)
> 
> 1. Go to the Preferences... > Plugins
> 2. Go to the "Installed" tab
> 3. Find lombok and hit "Update"
> 4. Restart IntelliJ

Thanks! It worked

**Comment by crpdev** [comment]
Thanks @DenisKozachok . I was able to get pass the error by manually updating the plugin.

**Comment by svenhaag** [comment]
Please release this plugin asap....

**Comment by mpbalmeida** [comment]
@svenhaag @crpdev @gustavodiasdev you don't need to do anything manually, the plugin 029 is compiled for 2020.1 already, just do this 

https://github.com/mplushnikov/lombok-intellij-plugin/issues/775#issuecomment-611823534

**Comment by vberezan** [comment]
Just manually reinstall the plugin if it fails to update. For some reason, some users are experiencing this problem... I just reinstalled it and it works.

**Comment by Miamoto-Musashi** [comment]
> Not able to update even after copying the extracted zip to C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2018.2.5\plugins.
> Still see only Disable and Uninstall options in the Plugins UI.

for me the option is under the gear icon "install plugin from disk", no need to store the zip inside intellij  and it worked

**Comment by Katakurinna** [comment]
> @sergeivisotsky
> You can add a new version manually.
> [lombok-plugin-0.30-EAP.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4468662/lombok-plugin-0.30-EAP.zip)
> 
> 1. Go to the Preferences... > Plugins
> 2. Go to the "Installed" tab
> 3. Find lombok and hit "Update"
> 4. Restart IntelliJ


I have used the version you have linked, and installed it. It works correctly, thanks! 

![asdasda](https://user-images.githubusercontent.com/43810296/79216501-94aa6d00-7e4d-11ea-9b5d-dd0ad8cab279.png)

**Comment by mpbalmeida** [comment]
@Katakurinna @Miamoto-Musashi @vberezan 

https://github.com/mplushnikov/lombok-intellij-plugin/issues/775#issuecomment-611823534

Since https://github.com/mplushnikov/lombok-intellij-plugin/releases already has a build for 2020.1, the solution is uninstall plugin, restart and reinstall plugin - Intellij will pick the right version then.

**Comment by mplushnikov** [comment]
duplicate #775
