### ISSUE TITLE
经常无缘无故出现找不到符号

### ISSUE THREAD

**Issue by Seifon** [mplushnikov/lombok-intellij-plugin#789]
我是在idea里面开启了注解支持的。同样是几个类都标注了@Data注解，可有时候就这个类导致报错

`
@Data
@ApiModel("课时按模板导入请求")
public class LessonImportReq implements Serializable {

	private static final long serialVersionUID = -6253459705421879251L;

	@ApiModelProperty(value = "科目", required = true, example = "2")
	private Integer subjectType;

	@ApiModelProperty(value = "课时Excel数据文件", required = true)
	private MultipartFile file;
	
	@ApiModelProperty(value = "一个随机串，标记本次上传行为", required = true)
	private String importTag;

}
`

`
Error:(205, 85) java: 找不到符号
  符号:   方法 getSubjectType()
  位置: 类型为cn.jojo.cc.admin.model.req.LessonImportReq的变量 lessonImportReq
Error:(206, 32) java: 找不到符号
  符号:   方法 getFile()
  位置: 类型为cn.jojo.cc.admin.model.req.LessonImportReq的变量 lessonImportReq
Error:(206, 59) java: 找不到符号
  符号:   方法 getImportTag()
  位置: 类型为cn.jojo.cc.admin.model.req.LessonImportReq的变量 lessonImportReq
`

**Comment by NekoCaffeine** [comment]
This is a javac part problem, please repost this issue at: https://github.com/rzwitserloot/lombok/issues
And you should describe your problem in English.
