### ISSUE TITLE
IDEA doesn't treat class nested in @UtilityClass as static

### ISSUE THREAD

**Issue by ejain** [mplushnikov/lombok-intellij-plugin#795]
### Short description

When running Gradle tasks in IDEA, classes nested in classes annotated with `UtilityClass` are treated as inner classes rather than static classes.

The editor shows no issues; in fact there is a "UtilityClass already marks inner classes static" warning if the static keyword is added.

### Version information

 * **IDEA Version:** 2020.1.1
 * **JDK Version:** 1.8.0_252
 * **OS Type & Version:** macOS 10.15.8
 * **Lombok Plugin Version:** 0.30-2020.1
 * **Lombok Dependency Version:** 1.18.12

### Steps to reproduce

 1. Run `./gradlew test` in the terminal -> BUILD SUCCESSFUL
 2. Run 'UtilsTest' in IDEA -> BUILD FAILED

### Sample project

 - [x] [Sample project provided](https://github.com/mplushnikov/lombok-intellij-plugin/files/4589812/utilityclass.zip)
 - [x] I am able to reproduce this error on the sample project by following the steps described above

### Stacktrace

```
Testing started at 3:31 PM ...

> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :compileTestJava FAILED
.../utilityclass/src/test/java/UtilsTest.java:8: error: constructor Bar in class Bar cannot be applied to given types;
    new Utils.Bar();
    ^
  required: Utils
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 503ms
2 actionable tasks: 2 executed
```

**Comment by mplushnikov** [comment]
@ejain I can't reproduce your error ("constructor Bar in class Bar cannot be applied to given types")
Your sample project compiles and executes fine, without any errors.. 
Even if I manually remove @UtilityClass annotation, I get other compile error: "Error:(8, 5) java: an enclosing instance that contains Utils.Bar is required"
Can you please verify your submitted sample project?

**Comment by ejain** [comment]
Strangely, I'm able to run the `UtilsTest` via an IDEA run configuration on a different machine (Windows 10, JDK 1.8.0_251,  same version of IDEA + plugins). The failure is still as described when running on macOS.

If you remove the `UtilityClass` annotation, the compilation error `Utils.java:8` is expected.

**Comment by mplushnikov** [comment]
Yes, I'm using Windows too. Unfortunately I don't have MacOs to check it.

**Comment by mplushnikov** [comment]
Can you check it with another JDK on MacOs?

**Comment by ejain** [comment]
Still had this failure after upgrading to IDEA 2020.1.2. Switched the project from OpenJDK (1.8.0_252) to Oracle JDK (1.8.0_251) and the problem went away. Switched back to OpenJDK, and the problem remains gone! Will re-open if I can ever reproduce this again...
