### ISSUE TITLE
@SneakyThrows mistakenly swallow checked exception in lambda without "throws"

### ISSUE THREAD

**Issue by huaouo** [mplushnikov/lombok-intellij-plugin#799]
### Short description
@SneakyThrows mistakenly swallow checked exception in lambda without "throws" in IDEA.

### Expected behavior
Report an error in IDEA.

### Version information

 * **IDEA Version:** _2019.3.3_
 * **JDK Version:** _1.8.0-242_
 * **OS Type & Version:** _Windows 10 Pro, 19041.207_
 * **Lombok Plugin Version:** _0.29-2019.3_
 * **Lombok Dependency Version:** _1.18.12_

### Steps to reproduce
![image](https://user-images.githubusercontent.com/19972269/81540990-0cb07800-93a5-11ea-9863-64b3416a497c.png)

**Comment by hbourada** [comment]
this is a correct behavior for me, the lambda must not throw a checked exception as Runnable.run() did not, if you want use `@SneakyThrows` create a method  encapsulating the body of your runnable and add this annotation on it.

**Comment by huaouo** [comment]
> this is a correct behavior for me, the lambda must not throw a checked exception as Runnable.run() did not, if you want use `@SneakyThrows` create a method encapsulating the body of your runnable and add this annotation on it.

I mean in the screenshot above, there should be a red underscore under `throw new IOException("error");` and an error reported by the IDE.

<img width="577" alt="批注 2020-05-22 174036" src="https://user-images.githubusercontent.com/19972269/82654521-748f7a00-9c53-11ea-83b0-9edd9d2a7962.png">

**Comment by hbourada** [comment]
It’s already the case. There is an error under the throw exception

**Comment by huaouo** [comment]
> It’s already the case. There is an error under the throw exception

If you add @SneakyThrows, the error just disappears. But when compile the code using javac, there will be a same error in line 11 and line 18.

<img width="386" alt="批注 2020-05-22 195737" src="https://user-images.githubusercontent.com/19972269/82665625-c7266180-9c66-11ea-8fdb-0f1716c15850.png">

**Comment by likhoman** [comment]
> > It’s already the case. There is an error under the throw exception
> 
> If you add @SneakyThrows, the error just disappears. But when compile the code using javac, there will be a same error in line 11 and line 18.
> 
> <img alt="批注 2020-05-22 195737" width="386" src="https://user-images.githubusercontent.com/19972269/82665625-c7266180-9c66-11ea-8fdb-0f1716c15850.png">

I think too that this case shouldn't be disabled inspection IDE

**Comment by Lekanich** [comment]
I think I can fix it.
