### ISSUE TITLE
Revert warning @UtilityClass already marks methods static.

### ISSUE THREAD

**Issue by juriad** [mplushnikov/lombok-intellij-plugin#800]
Latest version of IDEA plugin marks `static` keyword on members of class annotated with `@UtilityClass` with warning:
```
@UtilityClass already marks methods static. 
```

This warning looks desirable, however due to bug in javac (https://projectlombok.org/features/experimental/UtilityClass, last paragraph on the page), it brings huge problems.

It is easy to import static a member of a class (or convert a star import into a specific one) in IDEA; sometimes developers do it without even noticing. The code looks fine in IDEA, but compilation blows up later with errors which just point to Lombok not working but none of the errors points to the real cause.

Any developer who blindly accepts the solution of removing `static` can spend quite a long time searching for a solution. This is especially true for refactors of big projects where a developer can work days to make code compilable again.

I therefore advise for removing the warning until `@UtilityClass` is known to play well with javac.

**Comment by mplushnikov** [comment]
I will change this inspection to be disabled by default.
