### ISSUE TITLE
val mis-infers an Optional<T> as Optional<Object> after map

### ISSUE THREAD

**Issue by eboto** [mplushnikov/lombok-intellij-plugin#802]
### Short description
IDEA, but not lombok itself, incorrectly identifies an `Optional<Integer>` as `Optional<Object>` when derived from an `Optional<String>` via `Optional::map`. It produces an inappropriate Quickfix to "fix" the change. Possible repeat of https://github.com/mplushnikov/lombok-intellij-plugin/issues/260 but doesn't seem quite the same since it doesn't involve conditionals.

### Expected behavior
```java
    val strOpt = Optional.of("1");
    val intOptInferredLambda = strOpt.map(str -> Integer.valueOf(str));
    val intOptInferredMethodRef = strOpt.map(Integer::valueOf);
    Optional<Integer> intOptExplicit = intOptInferredMethodRef; // works!
    intOptExplicit = intOptInferredLambda; // Doesn't work, but it should. Err msg is: Required type: Optional. Provided: Optional
```
### Version information

 * **IDEA Version:** IntelliJ Ultimate 2019.3
 * **JDK Version:** 1.8.0_51
 * **OS Type & Version:** Mac 10.14.6
 * **Lombok Plugin Version:** 0.29-2019.3
 * **Lombok Dependency Version:** 1.18.12

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Ensure that you have the Bazel plugin and Lombok plugins installed

 2. Open the sample project https://github.com/eboto/lombok-idea-val-bug

 2. Observe that this is the code in the main method:

```java
import lombok.val;
import java.util.Optional;

public class App {
  public static void main(String... args) {
    val strOpt = Optional.of("1");
    val intOptInferredLambda = strOpt.map(str -> Integer.valueOf(str));
    val intOptInferredMethodRef = strOpt.map(Integer::valueOf);
    Optional<Integer> intOptExplicit = intOptInferredMethodRef;
    intOptExplicit = intOptInferredLambda;

    System.out.println("\n\nThe app built successfully and ran, showing that the compile error was only in idea, not in the code itself or lombok.\n");
  }
}
```

 3. Observe the error on the `intOptExplicit = intOptInferredLambda` line. The error reads:  _Required type: Optional<Integer>. Provided: Optional<Object>_

### Sample project

https://github.com/eboto/lombok-idea-val-bug

 - [x] Sample project provided
 - [x] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
(Taken from my IDE in the sample project)
<img width="753" alt="lombok_idea_bug" src="https://user-images.githubusercontent.com/250233/82162458-8d65ed00-9859-11ea-8908-d734b42adfb9.png">

**Comment by eboto** [comment]
FYI I think I've made a test-case that demonstrates the problem here: https://github.com/mplushnikov/lombok-intellij-plugin/pull/804

**Comment by eboto** [comment]
I'm definitely a little lost here @mplushnikov ... I just pushed a commit that _somehow_ results in not having these spurious QuickFixes for the testcase, but I can not explain at all how calling `getFunctionalInterfaceType()` on the PsiLambdaExpression somehow results in the side-effect of it resolving types properly. I noticed that deep in the callstack there is some sort of thread-local Stack of types that is being managed, so possibly there is some state mismanagement happening in there? Or some implicit expectation about the order in which this plugin calls things while inferring types?

**Comment by eboto** [comment]
Ok I have provided a "fix" that makes the test-case work but can not yet explain how. I'll leave it up to @mplushnikov to decide whether passing test-cases and that lame explanation work well enough for now.

That said, I want to capture my work up until this point. The first obvious question about the solution is: _Why does a call to `LambdaUtil.getFunctionalInterfaceType`, either before or after `psiExpression.getType()` result in fixing the bug? Meaning, why does it cause inferring `stringOpt.map(str -> Integer.valueOf(str))` to correctly result in an `Optional<Integer>` rather than in an `Optional<Object>`?

For bugs like this, the answer is always shared mutable state, and the only relevant shared mutable state I could find is `Map<PsiElement, PsiType> myMap` contained in [ThreadLocalTypes.java](https://github.com/JetBrains/intellij-community/blob/master/java/java-psi-api/src/com/intellij/psi/ThreadLocalTypes.java#L25), invoked by `getFunctionalInterfaceType` [here](https://github.com/JetBrains/intellij-community/blob/master/java/java-psi-api/src/com/intellij/psi/LambdaUtil.java#L347-L348). I have verified that, with the patch in #804, that cache ends up containing the correct value of `Function1<String, Integer>`, but I have not verified that without the patch it does not.

A rat's nest of recursive calls to `ValProcessor.inferType` for this particular assignment has been confounding my analysis so rather then spend more cycles on this without further input, I figured I would supply this change that makes something better but doesn't _seem_ to make anything worse. After all, the tests pass ;)

**Comment by mplushnikov** [comment]
Thank you @eboto for figuring this out!
I'l try to speak with Jetbrains developers to check this issue inside of IntelliJ.

**Comment by mplushnikov** [comment]
Jetbrains developers added a new API to avoid recursion calls and such errors. It should come in one of the next builds of IntelliJ. I also implemented this API and hope the next build will fix this problem.

**Comment by mplushnikov** [comment]
Hello @eboto, you can try new plugin release 0.32 with IntelliJ 2020.3 EAP Build together. It should contains the mentioned fix for your issue.
