### ISSUE TITLE
2020.1 idea cannot build 

### ISSUE THREAD

**Issue by jsczrangel** [mplushnikov/lombok-intellij-plugin#806]
### Short description
2020.1最新版idea无法识别@Data进而build,而maven可以编译

### Expected behavior
_Is there a specific expected behavior?_

### Version information

 * **IDEA Version:2020.1
 * **JDK Version:1.8
 * **OS Type & Version:win
 * **Lombok Plugin Version: 0.30-2020.1
 * **Lombok Dependency Version: 0.30-2020.1

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

STACKTRACE HERE (inside code markup)

```

**Comment by mplushnikov** [comment]
I think you are missing lombok.jar dependency config in your pom.xml.
