### ISSUE TITLE
Lombok 'var' shows error in editor with 2020.2 EAP

### ISSUE THREAD

**Issue by egorklepikov** [mplushnikov/lombok-intellij-plugin#812]
### Short description
Repost from: https://youtrack.jetbrains.com/issue/IDEA-241974

### Expected behavior
**var** statement should be resolved.

### Version information

IntelliJ IDEA 2020.2 EAP (Ultimate Edition)
Build #IU-202.4357.23, built on May 27, 2020
Runtime version: 11.0.7+10-b912.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Lombok plugin version: 0.9.7.15

### Steps to reproduce
Try using the code:

```
import lombok.val;
import lombok.var;

public class TestClass {
    public void a() {
        val a = 123;
        var b = 123; // suggestion to change variable type
    }
}
```

**Comment by mplushnikov** [comment]
Thank you @egorklepikov ! I just released a compatible plugin build for 2020.2 EAP
