### ISSUE TITLE
Lombok IntelliJ can't compile on Windows 10

### ISSUE THREAD

**Issue by perroned** [mplushnikov/lombok-intellij-plugin#817]
### Short description
Lombok doesn't work on Windows 10 + IntelliJ. I have spent the entire day scouring Google and my IntelliJ parses the lombok annotations, I can control + click the import into the jar. But something is missing from the set up instructions that prevents IntelliJ from being able to compile because of `Error:(3, 14) java: package lombok does not exist`. 

I've follow the instructions from here https://projectlombok.org/setup/intellij
 and enabled the processing of annotations and every single answer from stackoverflow. I'm doing this on Windows 10 and my macbook side by side. My mac works no problem. But on windows there's a set up step that has to be missing. 

### Expected behavior
IntelliJ can compile an application using a Lombok import

### Version information

 * **IDEA Version:** : Idea Community 2020.1. Build #IC-201.6668.121

 * **JDK Version:**: I have tried JDK1.8.0_162, Correto-1.8._252, and OpenJDK-14.0.1

 * **OS Type & Version:** : Windows 10 Pro - Version 1903 - OS Build 18362.836

 * **Lombok Plugin Version:** 0.30-2020.1
 * **Lombok Dependency Version:** 1.18.12

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Create a new Maven IntelliJ Project on Windows
 2. Add Lombok plugin
 3. Add Lombok Annotation in Java
4. Add Lombok to pom/have intelliJ automatically add lombok mvn dependency
5. Go enable annotation processing in settings

### Additional information
annotations processing works. But IntelliJ cannot compile when I have a lombok annotation in my code. I can follow the exact same steps and get this to work on my Mac without problem. This problem is specific to Windows. I've tried different lombok versions, different Maven versions, different JDK versions. Nothing works on windows 10. The only cases ive found of it working on windows 10 is using gradle

### Stacktrace
Error:(3, 14) java: package lombok does not exist
Error:(10, 6) java: cannot find symbol
  symbol:   class Data
  location: class a.Main

**Comment by mplushnikov** [comment]
I think you have an error in your maven configuration. Please show us your pom.xml file.
