### ISSUE TITLE
“Lombok Dependency is missing” warning in nōn-Lombok projects

### ISSUE THREAD

**Issue by mirabilos** [mplushnikov/lombok-intellij-plugin#819]
I’ve got the Lombok plugin installed because most of the projects I work with use it. However, some don’t, and there I get the warning **every time I load the project**, big fat box *plus* cluttering the IntelliJ message tool window.

Is the warning even useful? I don’t remember earlier versions of the plugin to have it.

Perhaps an option to globally disable it would be appropriate.

**Comment by mplushnikov** [comment]
You can disable this checks and warnings in plugin settings:
![image](https://user-images.githubusercontent.com/1204509/92332397-2ecdb480-f07e-11ea-98b5-0ababd923de5.png)

**Comment by mplushnikov** [comment]
You can also disable lombok plugin completely for projects which are not using lombok

**Comment by mirabilos** [comment]
It should be able to detect that, though… doing this every time I load one of them into an IDE is going to become tiresome…

**Comment by mplushnikov** [comment]
Should be fixed by 1eca867c1dc01b0b654efd429138f80f0dc29b30 in plugin version 0.33 and 2020.3 EAP
