### ISSUE TITLE
Abstract Class + @Delegate

### ISSUE THREAD

**Issue by zubaliy** [mplushnikov/lombok-intellij-plugin#82]
Abstract Class + @Delegate
Results in a Intellij warning/error "Class 'TestDetailBean' must either be declared abstract or implement abstract method 'getResult()' in AbstractDetailBean"
But the project builds without any problem.

Example (each class should be in separate file to reproduce the warning:
```java
public abstract class AbstractDetailBean<T> {
    protected abstract List<T> getResult();
}



public abstract class AbstractDetailData<T> implements Serializable {
    @Getter
    @Setter
    private List<T> result;
}

public class MyDetailData<T> extends AbstractDetailData<Integer> implements Serializable {
    @Getter
    @Setter
    private String something;
}

public class TestDetailBean extends AbstractDetailBean<Integer> {
    @Delegate
    private MyDetailData detailData;
}
```

This is an example with few line of codes. And I just saw that sometimes Intellij is not showing the warning and is able to see the getResult() method. Sometimes you have to comment and uncomment the @Delegate to reproduce the bug.

In my real application I have a class with more lombok annotations (@Setter, @Getter + also @EJB), but only one @Delegate. Intellij is always showing the warning and the class is underlined with red, however the getResult() is being correctly generated by lombok and is visible in the class.

**Comment by mplushnikov** [comment]
@zubaliy 
I changed some of processing logic, but I'm not sure to correctly identified the problem.
Can you please manually install the plugin-jar and verify it in your case?

https://drive.google.com/file/d/0B98LpaspYu3eZnEyZVZuWFU4bUE/view?usp=sharing

**Comment by zubaliy** [comment]
I installed your version, but did not help

**Comment by mplushnikov** [comment]
I can't reproduce your (or similar) issue with the provided example after last changes.
What is your environment? OS,Intellij version, Java version? Do you have another example?

**Comment by zubaliy** [comment]
It is difficult to reproduce. Zubaliy@gmail.com please send me an email, I will show it
