### ISSUE TITLE
@FieldNameConstants in switch case

### ISSUE THREAD

**Issue by adalbert-h** [mplushnikov/lombok-intellij-plugin#826]
### Short description
IntelliJ reports error 'Constant expression required' when constant from @FieldNameConstants is used in switch case.

### Expected behavior
There shouldn't be any error reported

### Version information

 * **IDEA Version:** IntelliJ IDEA 2020.1.2 (Ultimate Edition), Build #IU-201.7846.76, built on June 1, 2020
 * **JDK Version:** 1.8.0_241
 * **OS Type & Version:** Windows 10 Pro, Version 1909, Build 18363.900
 * **Lombok Plugin Version:** 0.30-2020.1
 * **Lombok Dependency Version:** 1.18.12

### Steps to reproduce

1. Create class with @FieldNameConstants
2. Use field constant in switch case
3. Inspect error

### Sample project

```java
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldNameConstants;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;

@Slf4j
public class TestSwitch {

    @Getter
    @AllArgsConstructor
    @FieldNameConstants
    public static class Foo {
        private String bar;
    }

    private void logFieldValue(Foo foo, String fieldName) {
        switch (fieldName) {
            case Foo.Fields.bar:
                log.info("Field {} contains: {}", fieldName, foo.getBar());
                break;
            default:
                log.warn("Foo class doesn't have field: {}", fieldName);
        }
    }

    @Test
    public void test() {
        Foo foo = new Foo("ABC");
        logFieldValue(foo, "bar");
        logFieldValue(foo, "foo");
    }
}
```

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
![testswitch](https://user-images.githubusercontent.com/17341365/86242064-5a2ab380-bba4-11ea-9a02-f9710cf96c92.png)

**Comment by renekloth** [comment]
+1
