### ISSUE TITLE
The onX  problem

### ISSUE THREAD

**Issue by Hyperion-v** [mplushnikov/lombok-intellij-plugin#830]
### Short description
OnX error,underline not supported,But the function is normal

### Version information

 * **IDEA Version:** 2020.1.3
 * **JDK Version:** adpotopenJDK-11.0.7.10-hotspot
 * **OS Type & Version:** windows10 Enterprise   20H2  19042.330
 * **Lombok Plugin Version:** 0.30.2020.1
 * **Lombok Dependency Version:**1.18.12

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. @Setter(onMethod_ = {@Autowired})

### Sample project
![图片](https://user-images.githubusercontent.com/18093845/87139308-5b5d8e00-c2d2-11ea-95e8-a63ff4473a60.png)

### Additional information
When I switched idea to 2019.3.4 and Lombok's plug-in version to 0.29-2019.3, there was no exception message
![图片](https://user-images.githubusercontent.com/18093845/87139831-2140bc00-c2d3-11ea-8420-eb3b96578015.png)

**Comment by mplushnikov** [comment]
Please verify it with current lombok plugin version. I cannot reproduce it in my environment in Intellij 2020.2.1 or 2020.1.4

**Comment by mplushnikov** [comment]
closed, as no feedback provided
