### ISSUE TITLE
@Builder.Default and final keyword: erroneous ConstantConditions warning

### ISSUE THREAD

**Issue by iProdigy** [mplushnikov/lombok-intellij-plugin#838]
### Short description
In a class annotated with `@Builder`, if `@Builder.Default` is applied to a `final` field, later usage of the field can yield `ConstantConditions` warnings.

### Expected behavior
The warning should not appear.

### Version information
 * **IDEA Version:** 2020.1.4 (Ultimate) #IU-201.8743.12
 * **JDK Version:** Tested on both 1.8.0 & 14.0.2
 * **OS Type & Version:** Windows 10.0.18363
 * **Lombok Plugin Version:** 0.30-2020.1
 * **Lombok Dependency Version:** Tested on 1.18.10 & 1.18.13 (edge)

### Steps to reproduce
1. Annotate a class with `@Builder`
2. Mark a field as final, assign a default value, and annotate it with `@Builder.Default`
3. In a method, do a comparison involving the field's value
4. IDE will warn that `Condition '___' is always '___'`.

Example:
```java
import lombok.Builder;

// @Value
@Builder // @SuperBuilder
public class BadWarning {
	@Builder.Default final boolean b = true;
	@Builder.Default final int i = -1;
	@Builder.Default final String s = "";
	@Builder.Default final Object o = new Object();

	public void test() {
		// Doesn't occur here
		if (b) System.out.println("no warning");

		// But does occur here and with other primitives
		if (b == true) System.out.println("ConstantConditions");
		if (i == 0) System.out.println("ConstantConditions");

		// Does occur on objects
		if (s.isEmpty()) System.out.println("ConstantConditions");
		if (o == null) System.out.println("ConstantConditions");
	}
}
```

### Sample project
 - [x] Sample project provided
 - [x] I am able to reproduce this error on the sample project by following the steps described above

[.idea.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4967924/default.idea.zip)

### Additional information
* Also occurs with `@SuperBuilder` (instead of marking the class as `@Builder`)
* Also occurs with `@Value` (instead of manually marking the fields as final)

**Comment by Lekanich** [comment]
It might be fixed with a highlight filter. I will try...
If you don't find another solution about how to influent the dataflow checks...
