### ISSUE TITLE
Lombok Plugin does not properly find usages of @Getters & @Setters on fields with @Acccessor prefixes

### ISSUE THREAD

**Issue by mplushnikov** [mplushnikov/lombok-intellij-plugin#84]
Reported by malaguy, Feb 13, 2014
https://code.google.com/p/lombok-intellij-plugin/issues/detail?id=99

What steps will reproduce the problem?
1. Create a class with a field named "_foo"
2. Add @Getter, @Setter, and @Accessors(prefix = "_") annotations to the field.
3. Use the generated getter 'getFoo()' in a line of code
3. Use the generated setter 'setFoo(value)' in a line of code
4. Right click on _foo, and select "Find Usages"

Expected Output:

I expect 'Find Usages' to find both the getFoo() usage and the setFoo(value) usage.

Actual Output:

'Find Usages' does not find the use of either getFoo() or setFoo().

This problem is not unique to the variable _foo nor the prefix "_"

System:
IntelliJ 13.0.2
Lombok plugin 0.8.0 (downloaded from IntelliJ repository)
Ubuntu 12.04.4 LTS

Here's code I used to debug the issue:
```java
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

public class Main {
    @Accessors(prefix = "_") @Getter @Setter private Integer _foo;
    @Accessors(prefix = "f") @Getter @Setter private Integer fBar;
    @Getter @Setter private Integer baz;

    private Main() {
        _foo = 10;
        fBar = 20;
        baz = 40;
    }

    public static void main(String[] args) {
        Main m = new Main();
        System.out.println(m.getFoo());
        System.out.println(m.getBar());
        System.out.println(m.getBaz());

        m.setFoo(1);
        m.setBar(2);
        m.setBaz(4);

        System.out.println(m.getFoo());
        System.out.println(m.getBar());
        System.out.println(m.getBaz());
    }
}
```
Using 'Find Usages' on baz properly finds the usage of getBaz/setBaz, but does not do the same for _foo/getFoo/setFoo and fBar/getBar/setBar

**Comment by enigma11** [comment]
I have a similar issue. I use **@Data**, **@Accessors(fluent = true)** on class level (no field annotations used) and I am unable to refactor when I am on the method name, i.e. in the above example it would be m.foo(1). Is this a limitation, a bug or my usage error?
