### ISSUE TITLE
@Singular annotation not resolving

### ISSUE THREAD

**Issue by pstephenmurphy** [mplushnikov/lombok-intellij-plugin#849]
### Short description
@Singular annotation not resolving

### Expected behavior
To be able to access properties annotated with the @Singular annotation

### Version information
 * **IDEA Version:** _IntelliJ IDEA 2020.2 (Ultimate Edition) - Build #IU-202.6397.94, built on July 27, 2020_
 * **JDK Version:** _VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o._
 * **OS Type & Version:** _macOS 10.15.5_
 * **Lombok Plugin Version:** _0.30-EAP_
 * **Lombok Dependency Version:** _0.30-EAP_

### Steps to reproduce
Annotate any List<?> of Collection class with the @Singular annotation

### Sample image
![Screen Shot 2020-07-29 at 11 09 35 AM](https://user-images.githubusercontent.com/6752434/88955974-898b1980-d251-11ea-911f-364adea6a70b.png)

**Comment by mplushnikov** [comment]
IntelliJ 2020.2 has a bug and is incompatible with lombok plugin. Please upgrade to at least IntelliJ IDEA 2020.2.1 RC Build #IC-202.6948.36, built on August 18, 2020
Similar #840
