### ISSUE TITLE
Plugin incompatible with IntelliJ IDEA 2020.2

### ISSUE THREAD

**Issue by ivascaflavius** [mplushnikov/lombok-intellij-plugin#859]
### Short description
Seeing this error with the plugin after upgrading to IntelliJ IDEA 2020.2
```
9:35 AM	Plugin Error: Plugin "Lombok" is incompatible (until build 201.SNAPSHOT < IU-202.6397.94).
```

### Expected behavior
Plugin should work with the latest IntelliJ IDEA (2020.2) which is no longer beta or release candidate.

### Version information

 * **IDEA Version:** _IntelliJ IDEA 2020.2 (Ultimate Edition) Build #IU-202.6397.94, built on July 27, 2020_
 * **JDK Version:** _OpenJDK 64-Bit Server VM by JetBrains s.r.o. / jdk1.8.0_144_
 * **OS Type & Version:** _Windows 10 10.0_
 * **Lombok Plugin Version:** _0.30-2020.1_
 * **Lombok Dependency Version:** _1.16.18_

### Steps to reproduce
 1. Install IntelliJ IDEA 2020.1.x
 2. Install latest Lombok plugin (0.30-2020.1)
 3. Upgrade to IntelliJ IDEA 2020.2
 4. Notice plugin is no longer compatible

### Sample project
N/A

### Additional information
N/A

### Stacktrace
N/A

**Comment by ivascaflavius** [comment]
Duplicate of 855 (sorry did not see the existing issue)

**Comment by ivascaflavius** [comment]
Also for now, as a workaround, I updated the "until-version" from "201.*" to "202.*" in the META-INF/plugin.xml inside the lombok plug-in jar file and restarted IntelliJ IDEA. It seems to be compatible now, though I am not sure if will work 100%, as there were breaking changes introduced in IntelliJ 2020.2, but we'll see. So far so good.

**Comment by inthink** [comment]
> Also for now, as a workaround, I updated the "until-version" from "201._" to "202._" in the META-INF/plugin.xml inside the lombok plug-in jar file and restarted IntelliJ IDEA. It seems to be compatible now, though I am not sure if will work 100%, as there were breaking changes introduced in IntelliJ 2020.2, but we'll see. So far so good.

thx，it works .
