### ISSUE TITLE
IDEA not see @Getter method for protected fields

### ISSUE THREAD

**Issue by GromHoll** [mplushnikov/lombok-intellij-plugin#86]
Protected field with @Getter annotation not available for using in IDEA.
But code successfully compile an run.

![annotation](https://cloud.githubusercontent.com/assets/1131266/6649054/71ecc7cc-c9f3-11e4-8ea1-c4199c89c2d0.png)
![error](https://cloud.githubusercontent.com/assets/1131266/6649056/73d0b454-c9f3-11e4-9d72-b9dc7f631b13.png)

If I set AccessLevel.PUBLIC manually to annotation it works fine.

**Comment by mplushnikov** [comment]
Hello GromHoll,
I can't reproduce it at the moment. Please provide full standalone example, which shows your problem. Do you use any "lombok.config" files in your project?

**Comment by GromHoll** [comment]
Hello,
No, I don't use any lombok.config in my project.
Error not reprodused on my work PC.
I'll check it on my home computer (where I found it) in the evening.

**Comment by GromHoll** [comment]
It was reproduced on my home PC, but was fixed after reindex project.

Thanks for your responce.
