### ISSUE TITLE
Not Support Ultimate 2020.2

### ISSUE THREAD

**Issue by Qk1hpys** [mplushnikov/lombok-intellij-plugin#875]
Too many exceptions to use my Idea... plz support 2020.2 as soon as possible

**Comment by valentinprotiuc** [comment]
Duplicate of #840

**Comment by ruurd** [comment]
Guys would you please do your due diligence on this in future? Don't spam the issue list before concluding someone else reported the bug before you.

**Comment by ruurd** [comment]
👍
