### ISSUE TITLE
Delegating to class with generics using @Delegate annotation

### ISSUE THREAD

**Issue by vbanaitis** [mplushnikov/lombok-intellij-plugin#88]
Delegating to interface with generics return type causes intellij to report class cast problem from Object class. 
Maven build project without problems.

Sample project: https://github.com/vidmantasbanaitis/intellij-lombok-samples/tree/master/lombok-delegate-inteface
       
class with issue: MyWorkerTest

**Comment by mplushnikov** [comment]
New version 0.10 of the plugin was released today and contains fixes and improvements for this issue.
