### ISSUE TITLE
Adding a new final field to a class with @RequiredArgsConstructor gives error "Variable xxx might not have been initialized"

### ISSUE THREAD

**Issue by garypgithub** [mplushnikov/lombok-intellij-plugin#893]
### Short description
I have an existing Spring @Service class with the annotation @RequiredArgsConstructor.  It has a series of private final fields.  These fields should all be in the constructor generated by Lombok.  If I add a new final field like:
  private final String foo;
The field shows up in the generated constructor (I can see it in the Structure view) but I get the error message "Variable 'foo' might not have been initialized".  If I close the project and reopen it, the error has gone away.  This works but is a bit annoying.

### Expected behavior
Adding the new field should not generate an error message.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Licensed to Fox Corporation / Gary Peskin
Subscription is active until May 2, 2021
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2000M
Cores: 4
Registry: decompiler.dump.original.lines=true
Non-Bundled Plugins: Lombook Plugin, com.godwin.json.parser, MavenRunHelper

 * **JDK Version:** _What is your JDK version, including update level?_Amazon Corretto JDK 11.0.8_10

 * **OS Type & Version:** _Are you on Mac/Windows/Linux? Provide as much information as possible about versions_Windows 10 Enterprise 10.0.17134 Build 17134

 * **Lombok Plugin Version:** _What is the version of the plugin installed?`_0.30-EAP

 * **Lombok Dependency Version:** _What version of lombok.jar are you using?_1.18.12

### Steps to reproduce

 1. Start with a working class annotated with @RequiredArgsConstructor and several private final fields.
 2. Add a new private final field like (private final String foo).
 3. Observe "Variable foo might not have been initialized" error.

### Sample project
I am unable to share my existing project.  If you need a sample project, please let me know.
 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_ No.

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

STACKTRACE HERE (inside code markup)

```N/A

**Comment by justlaputa** [comment]
I met same problem recent days. After I upgrade to IDEA 2020.02

**Comment by mplushnikov** [comment]
IntelliJ  2020.2 has a bug and is incompatible with lombok plugin. Please upgrade to at least IntelliJ IDEA 2020.2.1 RC Build #IC-202.6948.36, built on August 18, 2020
Similar #840
