### ISSUE TITLE
Renaming a field with different case doesn't rename getter.

### ISSUE THREAD

**Issue by SupaHam** [mplushnikov/lombok-intellij-plugin#90]
Hey, whenever I try to rename a field, which has a getter generated by Lombok for it, to the same name but with different letter casing, such as myPlayer -> myPLAYER, this doesn't trigger lombok to rename the generated getters. Now, I think this is more of an IDEA bug, since IntelliJ is what prompts you to rename the getters.

I'm hoping Lombok might have a solution to this bug and squash it.

Example code before rename:
``` java
public class PlayerWrapper {
  @Getter
  private Object myPlayer;
}
```
``` java
public class Main {
  public static void main(String[] args) {
    PlayerWrapper wrapper = ...;
    wrapper.getMyPlayer(); // works
  }
}
```

But... after renaming myPlayer to myPLAYER:

``` java
public class Main {
  public static void main(String[] args) {
    PlayerWrapper wrapper = ...;
    wrapper.getMyPlayer(); // it didn't rename the method usage to getMyPLAYER();
  }
}
```

In case you're wondering, the actual reason I'm doing such renaming is because my previous getters used to be something like getMYPlayer(); but Lombok doesn't work like that, so lombok generated them as getMyPlayer(), and I wanted intellij/lombok to easily fix the problems for me.

**Comment by mplushnikov** [comment]
Schould be already fixed in comming 0.9.2 release
