### ISSUE TITLE
@Data and @Wither don't play together

### ISSUE THREAD

**Issue by askoning** [mplushnikov/lombok-intellij-plugin#92]
import lombok.Data;
import lombok.experimental.Wither;

@Data
public class Person {
	private String ssn;
	private String name;
	@Wither private String phone;
}

The @Wither is marked with a "Compilation will fail: no constructor found".
The .withPhone() method is not recognised in the intellij editor, but compiles correctly.

**Comment by mplushnikov** [comment]
Just improved @Wither support a little bit, but in your example you need constructor (like with @AllArgsConstructor) to get it working with lombok.

**Comment by askoning** [comment]
@Data generates the constructor for me. The code compiles (and runs) correctly.

**Comment by mplushnikov** [comment]
Ok, I now understand your issue!

**Comment by mplushnikov** [comment]
Please check your example. It doesn't generate any constructors at the moment, because none of your fields is final and @Data generates only @RequiredArgsConstructor per default.
