### ISSUE TITLE
@RequiredArgsConstructor doesn't work

### ISSUE THREAD

**Issue by donnerpeter** [mplushnikov/lombok-intellij-plugin#930]
See the description at https://youtrack.jetbrains.com/issue/IDEA-250658

**Comment by mplushnikov** [comment]
Hi @donnerpeter , I can't access your link, can you check it please?

**Comment by babhishek21** [comment]
Could this be possibly related to #919 ?

**Comment by mplushnikov** [comment]
@babhishek21 I think the user just forgot to install the plugin or didn't configure it probably
