### ISSUE TITLE
Enable annotation processing warning showing everytime project is opened

### ISSUE THREAD

**Issue by abannach** [mplushnikov/lombok-intellij-plugin#933]
### Short description
Lombok requires annotation processing to be enabled everytime project is opened.

### Expected behavior
After annotation processing is enabled, don't request it again.

### Version information

 * **IDEA Version:** `2020.2.2` (also happened with `2020.2.1`)
<img width="645" alt="image" src="https://user-images.githubusercontent.com/43150303/93251523-eb4c0800-f759-11ea-8712-5475bed0626f.png">

 * **JDK Version:** `corretto-1.8.0_252`, project language level `8`
 * **OS Type & Version:** Mac
<img width="582" alt="image" src="https://user-images.githubusercontent.com/43150303/93249985-bfc81e00-f757-11ea-875e-d127fa852080.png">

 * **Lombok Plugin Version:** `0.31-2020.2`
 * **Lombok Dependency Version:** `1.18.12`

### Steps to reproduce

Intellij setup to _NOT_ enable annotation processing by default for new projects.

1. Import build.gradle and Open as project;
    1. Annotation processing is not enabled at this point.
1. Wait for project to finish indexing/importing
1. See event log warning about needing annotation processing enabled
1. Click `enable`
1. Open preferences to see that annotation processing is enabled
1. Close project
1. Open project again
1. See event log warning about needing annotation processing enabled
1. Without clicking `enable` open preferences, see that annotation processing is still enabled.

### Sample project

https://github.com/mplushnikov/lombok-intellij-plugin

 - [x] Sample project provided
 - [x] I am able to reproduce this error on the sample project by following the steps described above

### Additional information

Interestingly when I setup IntelliJ to enable annotation processing by default for new projects I did not get the warning on initial project import. I disabled annotation processing, closed, and opened the project without deleting anything and the issue showed up.

Preferences show that annotation processing is indeed enabled in the project, but event log still shows warning.
<img width="2107" alt="image" src="https://user-images.githubusercontent.com/43150303/93249411-e46fc600-f756-11ea-8c30-dcda5098a071.png">

I do see that in the Lombok plugin settings there is a checkbox for "Enable annotation processing warning", but would not expect this to force it to always show.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/43150303/93249888-9909e780-f757-11ea-885a-04f8ced45ef9.png">

**Comment by asidoruk** [comment]
Hi!
I faced exactly same issue. And even submitted this [bug](https://youtrack.jetbrains.com/issue/IDEA-251000).
However, in my case it looks like Lombok really doesn't work: for example, for the class annotated with \@Value - when I use generated constructor / getter / etc in the code - Idea doesn't highlight any errors (it "sees" them), while project build (compilation) fails in these places ("cannot find symbol", etc). 
Note: project is gradle-based, with Quarkus plugin - maybe Lombok + Quarkus magic intersects...

**Comment by cosu** [comment]
I've hit the same issue and I've fixed it by switching back to Java SDK8 (had my project configured to use Java SDK11).  Not sure if this helps

**Comment by gimslab** [comment]
Hi
I have the same issue too. I'm waiting for it to be fixed soon. just red warning message is annoying me slightly.
my project is gradle-based also.

**Comment by mbrito-yieldstreet** [comment]
I'm seeing this too. My project is sbt-based, so I guess we can rule out Gradle. The plugin is working fine for me, but I get the "enable annotation processing" message every time I open the project.
