### ISSUE TITLE
Lombok Annotation @Slf4J not being recognized (By IDE and when compiling outside the IDE)

### ISSUE THREAD

**Issue by NedK123** [mplushnikov/lombok-intellij-plugin#937]
I'm using IntelliJ IDEA 2020.2.1 (Ultimate Edition)

I created a very small gradle project for demo purposes (The project literally has one class that logs a message)
and I added Lombok dependency in order to use the @Slf4J annotation

The Annotation is not being recognized

- I made sure Lombok plugin is installed
- I made sure to enable annotation processing under Build, Execution, Deployment > Compiler > Annotation Processors
- I made sure to enable @Log support (@Slf4j, @Log4j, @CommonsLog, etc.) under Lombok Plugin

The gradle.build file is as follows

---
repositories {
mavenLocal()
mavenCentral()
jcenter()
}

dependencies {

    compile group: 'ch.qos.logback', name: 'logback-classic', version: '1.2.3'
    compile group: 'ch.qos.logback', name: 'logback-core', version: '1.2.3'

    compileOnly 'org.projectlombok:lombok:1.18.12'
    annotationProcessor 'org.projectlombok:lombok:1.18.12'

    testCompile 'org.projectlombok:lombok:1.18.12'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.12'
}

---

I ran all gradle command like Clean, build and Reload project (usually it used to be solved when using the gradle reload command) but it didn't work

I restarted intelliJ multiple times (With cash invalidate and without) and each time I get get a message in the Event Log saying that the annotation processing is not enabled (Even though It is). I even clicked on "Enable" link that is next to the log message and it didn't work

In previous projects I used to get annotation recognition problems only for the @Slf4J annotation and the rest of the Lombok annotations work fine
But in this project all annotations are not being recognized

Can you please advise

**Comment by amadorZamora** [comment]
I'm using IntelliJ IDEA 2020.2.2 (Ultimate Edition)

I have a project with Maven and I have the same problem.
No annotation is recognized by the IDE.
The message is : Cannot resolve method 'error(java.lang.String)' depending on level ...error, warning. info, etc.
Is it a bug or is it a problem with the configuration of the IDE?

Thank you for your help

**Comment by mplushnikov** [comment]
Can you share your example projects? I think you just forgot to configure something.

**Comment by mplushnikov** [comment]
Logback-classic module requires the presence of slf4j-api.jar and logback-core.jar in addition to logback-classic.jar on the classpath.
I think you forgot to configure slf4j-api in your project.
You need this dependencies to get lombok @Slf4j working.

**Comment by mplushnikov** [comment]
Closing this as invalid, no new feedback provided
