### ISSUE TITLE
Intellij cannot resolve methods (info, debug) for log (using @Slf4j)

### ISSUE THREAD

**Issue by kvickyk** [mplushnikov/lombok-intellij-plugin#948]
### Short description
Intellij is unable to resolve the log methods for some reason. The `log` variable is being resolved just fine. Version information is below. I installed the plugin using the Intellij marketplace.
![image](https://user-images.githubusercontent.com/246468/94862832-6108d280-03ee-11eb-8770-cd82f0c89883.png)

### Version information

**IDEA Version** 
IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 14, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Non-Bundled Plugins: IdeaVIM, Lombook Plugin, org.jetbrains.kotlin, com.intellij.lang.jsgraphql

 * **JDK Version:** JDK 8 (for project)
 * **OS Type & Version:** OS X 10.15.6
 * **Lombok Plugin Version:** 0.32-2020.2

![image](https://user-images.githubusercontent.com/246468/94862701-33238e00-03ee-11eb-8ada-531286341747.png)
![image](https://user-images.githubusercontent.com/246468/94862736-3f0f5000-03ee-11eb-9ce6-81c0eab5182b.png)

**Comment by Lekanich** [comment]
You don't have a logger implementation in your classpath or at least Idea can't find it.
Please check that you have implementation of logger in your classpath.
For example: for slf4j it's slf4j-simple

**Comment by kvickyk** [comment]
It was in the classpath. I had to reboot my MacBook pro for other reasons and the problem went away.
