### ISSUE TITLE
Fluent Setter Override Error

### ISSUE THREAD

**Issue by RodrigoQuesadaDev** [mplushnikov/lombok-intellij-plugin#95]
Hello, I found an error when overriding a fluent setter:

![lombok_bug_2](https://cloud.githubusercontent.com/assets/5355932/7049714/f50e9786-ddd8-11e4-8df7-cb01d2d309d0.png)

IntelliJ shows that the method is already defined.

Thanks in advance!

**Comment by RodrigoQuesadaDev** [comment]
Same problem with Getter.

**Comment by mplushnikov** [comment]
Should be fixed in the next release 0.9.3
