### ISSUE TITLE
You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.

### ISSUE THREAD

**Issue by akanshapasricha1** [mplushnikov/lombok-intellij-plugin#952]
### Short description
I didn make any changes, Previously it was working fine but when I take a pull of master branch then my all projet stop working and above error start showing at the time of compilation.
This error shown in buildOutput.
In terminal it shows:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile    
### Expected behavior
It should start working as expected

### Version information

 * **IDEA Version:** IntelliJ IDEA 2020.3 EAP (Community Edition)
Runtime version: 11.0.8+10-b1098.1 amd64

 * **JDK Version:** 1.8.0
 * **OS Type & Version:**ubuntu1.18.0
 * **Lombok Plugin Version:** 1.18.0
 * **Lombok Dependency Version:** _What version of lombok.jar are you using?_

### Stacktrace
I am not able to find any solution any where on the net please help me out

```

**Comment by mplushnikov** [comment]
duplicate #950 
This is issue of lombok project. Please look here: rzwitserloot/lombok#2592 and here https://youtrack.jetbrains.com/issue/IDEA-252069
Unfortunately this can be fixed only in lombok self. So we need to wait for new lombok release.

**Comment by rhts01** [comment]
I have the same issue, I have updated my Lombok dependency and it worked for me.
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.16</version>
    <scope>provided</scope>
</dependency>

**Comment by valentinbrasov** [comment]
I had the same nasty problem when I updated today to 2020.3. It is shameful of IDEA to release their update without trying to coordinate with Lombok. Even more nasty is that if you go on idea's download section and click on "Other versions" in order to download the previous version, you get an empty page! Also when the IDE updates a version it would better make a backup of the previous version and offer in the UI an option to rollback to that backup. For who is interested in downloading the previous version (2020.2.4), I downloaded it from here: https://confluence.jetbrains.com/display/IDEADEV/IDEA+2020.2+latest+builds

**Comment by armujahid** [comment]
@valentinbrasov Jetbrains Toolbox provides instant rollback feature for all Jetbrains products if "Keep only latest version" setting is unchecked (this is unchecked by default as far as I remember).
![image](https://user-images.githubusercontent.com/3725386/100995243-564af500-3579-11eb-9b27-349472f6832b.png)

**Comment by armujahid** [comment]
@valentinbrasov Jetbrains Toolbox provides instant rollback feature for all Jetbrains products if "Keep only latest version" setting is unchecked (It's unchecked by default as far as I remember).
![image](https://user-images.githubusercontent.com/3725386/100996327-bd1cde00-357a-11eb-9d4a-6ba4243ea71d.png)

**Comment by bryce-pilcher** [comment]
This has a workaround in this thread [rzwitserloot/lombok#2592](https://github.com/rzwitserloot/lombok/issues/2592) mentioned by @mplushnikov.  

The suggestion here fixed it for me: https://github.com/rzwitserloot/lombok/issues/2592#issuecomment-705449860

> Yes, add -Djps.track.ap.dependencies=false to the build process options.

![Intellij build options](https://user-images.githubusercontent.com/26361984/101645076-f2567f80-3a03-11eb-93de-a67a4bb059b2.png)

**Comment by Debugger-15** [comment]
> This has a workaround in this thread [rzwitserloot/lombok#2592](https://github.com/rzwitserloot/lombok/issues/2592) mentioned by @mplushnikov.
> 
> The suggestion here fixed it for me: [rzwitserloot/lombok#2592 (comment)](https://github.com/rzwitserloot/lombok/issues/2592#issuecomment-705449860)
> 
> > Yes, add -Djps.track.ap.dependencies=false to the build process options.
> 
> ![Intellij build options](https://user-images.githubusercontent.com/26361984/101645076-f2567f80-3a03-11eb-93de-a67a4bb059b2.png)

You, Sir, Saved my day. Thank you so very much  :)

**Comment by sirajmunir10p** [comment]
> > This has a workaround in this thread [rzwitserloot/lombok#2592](https://github.com/rzwitserloot/lombok/issues/2592) mentioned by @mplushnikov.
> > The suggestion here fixed it for me: [rzwitserloot/lombok#2592 (comment)](https://github.com/rzwitserloot/lombok/issues/2592#issuecomment-705449860)
> > > Yes, add -Djps.track.ap.dependencies=false to the build process options.
> > 
> > 
> > ![Intellij build options](https://user-images.githubusercontent.com/26361984/101645076-f2567f80-3a03-11eb-93de-a67a4bb059b2.png)
> 
> You, Sir, Saved my day. Thank you so very much :)

Saved my day. Thank you! 👍

**Comment by ANKIToyo** [comment]
> This has a workaround in this thread [rzwitserloot/lombok#2592](https://github.com/rzwitserloot/lombok/issues/2592) mentioned by @mplushnikov.
> 
> The suggestion here fixed it for me: [rzwitserloot/lombok#2592 (comment)](https://github.com/rzwitserloot/lombok/issues/2592#issuecomment-705449860)
> 
> > Yes, add -Djps.track.ap.dependencies=false to the build process options.
> 
> ![Intellij build options](https://user-images.githubusercontent.com/26361984/101645076-f2567f80-3a03-11eb-93de-a67a4bb059b2.png)

Thanks Buddy!... you are life saver.

**Comment by jain1dit** [comment]
worked from me 👍

**Comment by dpkahuja-jg** [comment]
Thanks for the solution !

**Comment by toudidel** [comment]
Does not work for me. Only downgrade to 2020.2 allows me to run application.
