### ISSUE TITLE
IntelliJ IDEA 2020.3 EAP - You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.

### ISSUE THREAD

**Issue by ivascaflavius** [mplushnikov/lombok-intellij-plugin#955]
### Short description
Using IntelliJ IDEA 2020.3 EAP, Lombok plugin version 0.32 EAP and JDK 1.8 I cannot compile Java code with Lombok annotations anymore due to: 
```
You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
```

### Expected behavior
Compiling Lombok annotated classes should work as before.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2020.3 EAP (Ultimate Edition) Build #IU-203.4449.2, built on October 6, 2020
 * **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
 * **OS Type & Version:** Microsoft Windows [Version 10.0.18363.1082]
 * **Lombok Plugin Version:** 0.32-EAP
 * **Lombok Dependency Version:** 1.18.12

### Steps to reproduce
 1. Install IntelliJ IDEA 2020.3 EAP and Lombok plugin 032-EAP
 2. Use Lombok dependency version 1.18.12 in you Maven / Gradle dependencies
 3. Compile Lombok annotated code

### Sample project
N/A

### Additional information
 * Building the code using Maven from the command line works fine
 * Used to work fine from IntelliJ IDEA as well, until a week or so ago. So I am guessing it might be some incompatibility issue either with the newer IntelliJ IDEA version or Lombok plugin version.
 * Probably related to: https://github.com/rzwitserloot/lombok/issues/2592

### Stacktrace
```
java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: org.jetbrains.jps.javac.$Proxy19
  Lombok supports: OpenJDK javac, ECJ
```

**Comment by ivascaflavius** [comment]
Is there a workaround for this issue?

**Comment by ivascaflavius** [comment]
Closing as it is a duplicate of https://github.com/mplushnikov/lombok-intellij-plugin/issues/950

**Comment by devendrasr** [comment]
> Found a potential workaround in [rzwitserloot/lombok#2592](https://github.com/rzwitserloot/lombok/issues/2592) and https://youtrack.jetbrains.com/issue/IDEA-250718#focus=Comments-27-4418347.0-0
> 
> Go to _File | Settings | Build, Execution, Deployment | Compiler | Build process VM options field_ and add
> 
> ```
> -Djps.track.ap.dependencies=false
> ```

it works!

**Comment by Anilkumar100** [comment]
it woeks

**Comment by agitrubard** [comment]
> Closing as it is a duplicate of #950

It definitely works!

for Mac : IntellIJ IDEA -> Preferences -> Build, Execution, Deployment -> Compiler 
-> User-local build process VM options (overrides Shared options): -Djps.track.ap.dependencies=false

**Comment by devin-jade** [comment]
It definitely works!

**Comment by zuoniduimian** [comment]
> > Found a potential workaround in [rzwitserloot/lombok#2592](https://github.com/rzwitserloot/lombok/issues/2592) and https://youtrack.jetbrains.com/issue/IDEA-250718#focus=Comments-27-4418347.0-0
> > Go to _File | Settings | Build, Execution, Deployment | Compiler | Build process VM options field_ and add
> > ```
> > -Djps.track.ap.dependencies=false
> > ```
> 
> It definitely works!
> 
> for Mac : IntellIJ IDEA -> Preferences -> Build, Execution, Deployment -> Compiler
> -> User-local build process VM options (overrides Shared options): -Djps.track.ap.dependencies=false

it works for mac !!

**Comment by namor-katz** [comment]
don't work.
If don't use this option - not work one module.
If use this option - not wlrk 50% modules...

**Comment by vrisagrepo** [comment]
It really works
