### ISSUE TITLE
Can't find symbol for any lombok generated getter-method when running individual test file/test

### ISSUE THREAD

**Issue by blindahl** [mplushnikov/lombok-intellij-plugin#960]
### Short description
When trying to run individual Spock-tests no lombok generated getter methods are found. It's only getter methods that seem to be the problm.

### Expected behavior
It works in previous EAP-version as well as stable version. IntelliJ should find all methods generated with lombok annotation, . If I'm not running individual test file/tests but instead run mvn clean package it works. 

### Version information

 * **IDEA Version:** Tested with previous EAP version: 203.4449.2 and latest: 203.4818.26 with same result.
 * **JDK Version:** 1.8.
 * **OS Type & Version:** Windows 10 Enterprise
 * **Lombok Plugin Version:** 0.32-EAP
 * **Lombok Dependency Version:** Not sure how to find that out.

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Click the gutter icon for run/debug a single test or whole test file

### Sample project
-

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
It works in prior versions of Intellij, include previous EAP-version. Not sure if the error is in intellij or lombok.

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.
For most/all generated getters I get: 
```
java: cannot find symbol
  symbol:   method getType()
  location: variable <variable name> of type <variable type>

```

**Comment by youngyajun** [comment]
I'm in the same situation as you. Have you solved the problem?

**Comment by blindahl** [comment]
Unfortunately not. I will install new EAP version released yesterday and give it a go.

**Comment by blindahl** [comment]
No, the problem is still present using IntelliJ 2020.3 EAP build 203.4818.26 with Lombok v0.32-EAP.  0.32-EAP was release September 24th so I guess it need som modifications to work with latest IntelliJ EAP.

**Comment by blindahl** [comment]
I saw another issue where solution was to invalidate cache and restart but it didn't help in this situation. 
Since lombok 0.32EAP was released in September it would be nice to hear from maintainers if it's future proof to use with future EAP versions as well?

**Comment by blindahl** [comment]
> I'm in the same situation as you. Have you solved the problem?

Do you have the possiblility to provide an example project where you experience the issue? I'm not and that will help maintainers and the probability to get it addressed.

**Comment by youngyajun** [comment]
> > I'm in the same situation as you. Have you solved the problem?
> 
> Do you have the possiblility to provide an example project where you experience the issue? I'm not and that will help maintainers and the probability to get it addressed.

I have submitted an issue and you can visit this address https://youtrack.jetbrains.com/issue/IDEA-253011.I'm not sure if it's a plug-in or an IDE problem.

**Comment by mplushnikov** [comment]
Plese verify you are using the latest lombok version in your project (1.18.16)
Lombok versions before 1.18.16 will not work with IntelliJ 2020.3 EAP!

**Comment by blindahl** [comment]
> Plese verify you are using the latest lombok version in your project (1.18.16)
> Lombok versions before 1.18.16 will not work with IntelliJ 2020.3 EAP!

Ok, that explains it. We're still on an old version of lombok (1.16.22) due to the fact that we're on java 8 for a while longer. It isn't possible to use newer lombok with java 8, right?

**Comment by mplushnikov** [comment]
@blindahl You can simple use latest version of lombok in your java 8 project, it should be fully compatible. Just try it out!

**Comment by blindahl** [comment]
@mplushnikov my bad. I tried it and it worked just fine. I've lived under the misconception that later versions than the one we used din't work with java 9 and forward after someone in my team read it somewhere after he ran into some issues. That is awesome. Closing the issue. Thanks for clearing this out.

**Comment by blindahl** [comment]
Unfortunately I spoke too early. When setting lombok to latest version with Java 8, I get this: 
```
[INFO] Scanning dependency org.projectlombok:lombok:jar:1.18.16 for annotated classes...
[ERROR] Error while scanning!
java.io.IOException: invalid constant type: 19 at 6
    at javassist.bytecode.ConstPool.readOne (ConstPool.java:1236)
    at javassist.bytecode.ConstPool.read (ConstPool.java:1167)
    at javassist.bytecode.ConstPool.<init> (ConstPool.java:175)
    at javassist.bytecode.ClassFile.read (ClassFile.java:777)
    at javassist.bytecode.ClassFile.<init> (ClassFile.java:118)
```

**Comment by mplushnikov** [comment]
The best way is to update your lombok.jar
But you can also try this workaround: https://youtrack.jetbrains.com/issue/IDEA-252069#focus=Comments-27-4428455.0-0
