### ISSUE TITLE
Two constructors being shown when using @Builder and @AllArgsConstructor together

### ISSUE THREAD

**Issue by RodrigoQuesadaDev** [mplushnikov/lombok-intellij-plugin#97]
Hello, I just found this other bug:

![lombok_bug_3](https://cloud.githubusercontent.com/assets/5355932/7089545/e92c5246-df59-11e4-8164-ccee5a961451.png)

In this particular case, it should only show the private constructor and therefor not autocomplete the constructor outside this class and show it as being available for package-wide use.

Thanks,

**Comment by mplushnikov** [comment]
Should be fixed in the next release 0.9.3
