### ISSUE TITLE
Problem with @RequiredArgsConstructor, @Slf4j and non-static log fields

### ISSUE THREAD

**Issue by peritbezektoptal** [mplushnikov/lombok-intellij-plugin#978]
### Short description
When Lombok is configured to generate a non-static log field, having a `@RequiredArgsConstructor` together with `@Slf4j` confuses IntelliJ. IntelliJ assumes that the constructor should have a `org.slf4j.Logger` parameter. The actual constructor generated by Lombok does not have it and you can build it and run it using normal build tools, but IntelliJ shows this as a compile error.

### Expected behavior
There should be no error reported by IntelliJ.

### Version information

 * **IDEA Version:** 2020.2.3 (Ultimate Edition), Build # IU-202.7660.26
 * **JDK Version:** 11.0.8+10-b994.34 (used by the IDE), 1.8.0_265 (build 1.8.0_265-8u265-b01) and 11.0.8+10 used by different projects
 * **OS Type & Version:** Running inside WSL 2 Ubuntu 20.04 on Windows 10 Enterprise (20H2)
 * **Lombok Plugin Version:** 0.33-2020.2
 * **Lombok Dependency Version:** lombok 1.18.6 in a project compiled/executed by JDK 8, lombok 1.18.4 in another project compiled/executed by JDK 11

### Steps to reproduce

 1. Create a lombok.config file with the following contents:
```
lombok.log.fieldIsStatic = false
```
 2. Create a class having both `@RequiredArgsConstructor` and `@Slf4j`:
```java
@RequiredArgsConstructor
@Slf4j
public class Demonstration {
  private final String sampleField;
}
```
 3. Try calling it's constructor:
```java
@RequiredArgsConstructor
@Slf4j
public class Demonstration {
  private final String sampleField;

  public static void main(String... args) {
    new Demonstration("demo");
  }
}
```
 4. You can actually run this class, it's main method, but IntelliJ shows a compile error.

**Comment by anton31kah** [comment]
I'm also facing this issue. I was able to download the previous version of lombok but then I updated Intellij to 2020.3 and the issue came back. Any updates or an ETA for a fix?
