### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by ruurd** [mplushnikov/lombok-intellij-plugin#987]
### Short description
Lombok plugin being standard part of IntelliJ IDE

### Expected behaviour
Congratulations are in order

### Version information
 * **IDEA Version:** 2020.3

### Steps to reproduce
Read the README.md

To everyone working on Lombok and this plugin: CONGRATULATIONS!!!!!

**Comment by materemias** [comment]
And thanks for helping out and supporting so many of us!

**Comment by kseh0220** [comment]
I also congratulate you on this. But do I have to delete the Lombok plug-in before updating it to 2020.3? There's a warning in the update window as below.
![image](https://user-images.githubusercontent.com/69245379/100950089-f4759580-354e-11eb-8556-25922409cc34.png)

**Comment by lealceldeiro** [comment]
> I also congratulate you on this. But do I have to delete the Lombok plug-in before updating it to 2020.3? There's a warning in the update window as below.
> ![image](https://user-images.githubusercontent.com/69245379/100950089-f4759580-354e-11eb-8556-25922409cc34.png)

 I faced the same issue. I just uninstalled it and updated IntelliJ IDEA. It worked OK.

**Comment by kseh0220** [comment]
> > I also congratulate you on this. But do I have to delete the Lombok plug-in before updating it to 2020.3? There's a warning in the update window as below.
> 
> I faced the same issue. I just uninstalled it and updated IntelliJ IDEA. It worked OK.

Thanks a lot! Have a good day.

**Comment by Anricx** [comment]
So, is Community Edition also bundled?

**Comment by daald** [comment]
From some (unofficial?) release notes:
> Lombok is now bundled with IntelliJ IDEA **Community Edition** 2020.3. [IDEA-257311]

For reference, the jetbrains ticket (solved): https://youtrack.jetbrains.com/issue/IDEA-257311


The drawback of all this: I waited until today because my intelliJ 2020.2.3 was still showing the incompatibility warning. Maybe there should be kind of a transition update package for the plugin without functionality?
But I like seeing it integrated now 👍
