### ISSUE TITLE
Lombok plugin is not integrated in the IntelliJ IDEA 2020.3 (Community Edition)

### ISSUE THREAD

**Issue by ydq** [mplushnikov/lombok-intellij-plugin#990]
IntelliJ IDEA 2020.3 (Community Edition)
Build #IC-203.5981.155, built on December 1, 2020

![iShot2020-12-04 12 10 46](https://user-images.githubusercontent.com/8097340/101121763-e34e8680-362b-11eb-8512-0738b60e3429.png)

**Comment by Sunyb01** [comment]
So, I need to roll back to 2020.2, right?

**Comment by koelnconcert** [comment]
Another option is to upgrade to 2020.3 but downgrade the lombok plugin to 0.32-EAP.
