### ISSUE TITLE
lombok will not work and has been disabled

### ISSUE THREAD

**Issue by Sunyb01** [mplushnikov/lombok-intellij-plugin#991]
### Short description
_Provide a short description of the issue here. Do not include stacktraces in this sectrion_

After updating IDEA 2020.3, my project cannot start! 
Tip: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: com.sun.proxy.$Proxy23
  Lombok supports: sun/apple javac 1.6, ECJ

### Expected behavior
_Is there a specific expected behavior?_

### Version information

 * **IDEA Version:** Community 2020.3
 * **JDK Version:** 1.8
 * **OS Type & Version:** mac
 * **Lombok Plugin Version:** 0.32-EAP
 * **Lombok Dependency Version:** 1.16.22

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. update idea to Community 2020.3
 2. run project
 3. java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: com.sun.proxy.$Proxy25
  Lombok supports: sun/apple javac 1.6, ECJ

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [ ] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

STACKTRACE HERE (inside code markup)

```

**Comment by kirangeorgeb** [comment]
please upgrade lombok as mentioned below. 
https://github.com/mplushnikov/lombok-intellij-plugin/issues/988

**Comment by novicedev7291** [comment]
@kirangeorgeb We are using spring boot and lombok version provided by spring pom, what should we do?

**Comment by kirangeorgeb** [comment]
Lombok Dependency Version: 1.16.22

Upgrade lombok to 1.18.16

**Comment by Sunyb01** [comment]
> @kirangeorgeb我们正在使用spring pom提供的spring boot和lombok版本，该怎么办？

The current community version of 2020.3.eAP does not support or use Lombok, but uninstalling older Lombok plug-ins in the non-community version is not affected.

**Comment by novicedev7291** [comment]
> The current community version of 2020.3.eAP does not support or use Lombok

@Sunyb01 how did you confirm this?

**Comment by Sunyb01** [comment]
> > 当前社区版本2020.3.eAP不支持或使用Lombok
> 
> @ Sunyb01您如何确认的？

I'm using both versions. Last week, my community version was updated to 2020.3. The Lombok plug-in failed after EAP, but my non-community version was updated to 2020.3 and uninstalled Lombok, compiling and starting without any impact.

**Comment by novicedev7291** [comment]
@Sunyb01 ok, thanks for confirming this, I was struggling for quite a time to make it work.

**Comment by mplushnikov** [comment]
Problems with lombok plugin not installed with Community version are handled here:  https://github.com/mplushnikov/lombok-intellij-plugin/issues/989#issuecomment-741903275 and here https://youtrack.jetbrains.com/issue/IDEA-257311

For Ultimate you just need to use the last version (1.18.16) of lombok library to get it compilling.
