### ISSUE TITLE
Lombok plugin incompatible with 2019.1 Intellij Idea

### ISSUE THREAD

**Issue by Zengzehao** [mplushnikov/lombok-intellij-plugin#992]
### Short description
I try to add some new features to the Lombok plugins and I download the master code and rebuild, get the lombok-plugin-0.34-EAP.zip, but it can not incompatible.

### Expected behavior
Lombok plugin compatible

### Version information

IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
Licensed to   *******
Subscription is active until June 29, 2021
For educational use only.
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.6
 
### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. from github website download the source code
 2. import the IDEA
 3. build it
 4. IDEA install the **.zip plugins

### Others
Can you tell me how to build the Lombok plugins

**Comment by mplushnikov** [comment]
Yes, master is for current IntelliJ Build only (2020.3+ at the moment)
If you really need an older version, you can use a corresponding "backported" branch: https://github.com/mplushnikov/lombok-intellij-plugin/tree/backport_intellij_2018.1 for example.
