### ISSUE TITLE
Add lombok.NonNull to the list of annotations supported by IntelliJ

### ISSUE THREAD

**Issue by CC007** [mplushnikov/lombok-intellij-plugin#996]
### Short description
In IntelliJ you can configure which annotations are detected for determining nullability of parameters/methods/fields. This can be configured in `Settings -> Editor -> Inspections -> Java -> Probable bugs -> Nullability problems -> Configure Annotations -> NotNull annotations`.

It would be nice if installing the Lombok plugin would automatically add lombok.NonNull to this list, so that the user of Lombok doesn't have to enable this manually.

### Additional information
Lombok's `@NonNull` annotation guarantees that the parameter/method/field is not null, by adding an `Objects.requireNonNull()` check, so it is really guaranteed that the value is not null, since an exception will be thrown otherwise. Therefore there would not be any negative side effects of adding this annotation to the list in IntelliJ

**Comment by mplushnikov** [comment]
Fixed inside of IntelliJ (https://github.com/JetBrains/intellij-community/commit/f6a7019606223ef6a555b8523dbc23f8f7037217) 
Should be available in next major IntelliJ Release (2021.1)
