### ISSUE TITLE
Icon cannot be found 'icons/lombok.svg

### ISSUE THREAD

**Issue by LiuHeLiang** [mplushnikov/lombok-intellij-plugin#998]
com.intellij.diagnostic.PluginException: Icon cannot be found in 'icons/lombok.svg', action 'class com.intellij.openapi.actionSystem.DefaultActionGroup'

**Comment by thankyoumyteens** [comment]
com.intellij.diagnostic.PluginException: Icon cannot be found in 'icons/lombok.svg', action 'class com.intellij.openapi.actionSystem.DefaultActionGroup' [Plugin: Lombook Plugin]

**Comment by mplushnikov** [comment]
What is the IntelliJ version you are using?

**Comment by thankyoumyteens** [comment]
2018.3
